### ISSUE TITLE
Ran into memory corruption running tests

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#259] opened 2015-10-14 08:02 UTC
![image](https://cloud.githubusercontent.com/assets/95136/10477909/c2c685a2-720e-11e5-926b-a4d15320eb9c.png)

Didn't happen twice in a row though.

**Comment by halter73** [comment] 2015-10-16 21:47
It seems like the same issue came up in an AppVeyor build:

**Comment by victorhurdugaci** [comment] 2015-10-16 23:29
Happened on the CI too:

```
 [xunit-test] Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.async_send(UvAsyncHandle handle)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.KestrelThread.Post[T](Action`1 callback, T state)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.ScheduleWrite()
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Write(ArraySegment`1 buffer, Action`3 callback, Object state, Boolean immediate, Boolean socketShutdownSend, Boolean socketDisconnect)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.End(ProduceEndType endType)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.Connection.Microsoft.AspNet.Server.Kestrel.Http.IConnectionControl.End(ProduceEndType endType)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.Frame.ProduceEnd(Exception ex)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__77.MoveNext()
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.WebSockets.Client.Test.KestrelWebSocketHelpers.<>c.<<CreateServer>b__0_1>d.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\WebSockets\test\Microsoft.AspNet.WebSockets.Client.Test\KestrelWebSocketHelpers.cs:line 39
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.WebSockets.Client.Test.WebSocketClientTests.<>c__DisplayClass5_0.<<SendMediumData_Success>b__0>d.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\WebSockets\test\Microsoft.AspNet.WebSockets.Client.Test\WebSocketClientTests.cs:line 124
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<ReceiveAsync>d__36.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\WebSockets\src\Microsoft.AspNet.WebSockets.Protocol\CommonWebSocket.cs:line 288
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<ReadNextFrameAsync>d__37.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\WebSockets\src\Microsoft.AspNet.WebSockets.Protocol\CommonWebSocket.cs:line 348
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.WebSockets.Protocol.CommonWebSocket.<EnsureDataAvailableOrReadAsync>d__38.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\WebSockets\src\Microsoft.AspNet.WebSockets.Protocol\CommonWebSocket.cs:line 376
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishContinuations()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.FinishStageThree()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
[13:39:57]E:				 [xunit-test]    at Microsoft.AspNet.Server.Kestrel.Http.SocketInputExtensions.<ReadAsync>d__0.MoveNext()
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.InnerInvoke()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.Execute()
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
[13:39:57]E:				 [xunit-test]    at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
[13:39:57]E:				 [xunit-test]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[13:39:57]E:				 [xunit-test]    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
[13:39:57] :				 [xunit-test] 
[13:39:57] :				 [xunit-test] fail: Exit code -1073741819 from cmd
[13:39:57] :				 [xunit-test] fail: Stack trace: 
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.Dnx(String command, String dnxDir) in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 1099
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.DnxTest(String projectFile, Boolean testParallel) in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 2352
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.<RenderViewLevel0>b__ed(String projectFile) in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 11994
[13:39:57] :				 [xunit-test]    at System.Collections.Generic.List`1.ForEach(Action`1 action)
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.<RenderViewLevel0>b__eb() in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 11994
[13:39:57] :				 [xunit-test]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.StartingTarget(String name) in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 3723
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.<RenderViewLevel0>b__8b() in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 4350
[13:39:57] :				 [xunit-test]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.StartingTarget(String name) in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 3723
[13:39:57] :				 [xunit-test]    at View1408fc3d762847729f1dfdc8a36d9927.<RenderViewLevel0>b__91() in d:\b\temp\buildTmp\d52d6b0f0a4e4284b0c1c76486cedb2f-1.cs:line 4455
[13:39:57] :				 [xunit-test]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
[13:39:57] :				 [xunit-test]    at Sake.Engine.SakeEngine.Execute(Options options)
[13:39:57] :				 [xunit-test]    at Sake.Engine.SakeEngine.Execute(String[] args)
[13:39:57] :				 [xunit-test]    at Sake.Program.Main(String[] args)
[13:39:57] :				 [xunit-test] 
```

**Comment by halter73** [comment] 2015-10-16 23:36
I've also seen some segfaults on travis which I think are related:  https://travis-ci.org/aspnet/KestrelHttpServer/builds/84413500, https://travis-ci.org/aspnet/KestrelHttpServer/builds/81208161

**Comment by halter73** [comment] 2015-10-29 21:41
It happened again :cry: I think these could be caused by our "rude" shutdowns.

        Microsoft.AspNet.Server.KestrelTests.MultipleLoopTests.ServerPipeDispatchConnections [SKIP]
          Waiting for adding support for multi loop in libuv
    Information: [LoaderContainer]: Load name=Microsoft.Extensions.Primitives, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Primitives, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 0ms
    Information: [LoaderContainer]: Load name=System.Threading.Timer, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    Information: [PathBasedAssemblyLoader]: Loaded name=System.Threading.Timer, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 1ms
    Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Http.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libc
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=ws2_32.dll
    Information: [LoaderContainer]: Load unmanaged library name=ws2_32.dll
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=ws2_32.dll
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libuv
    Information: [ProjectAssemblyLoader]: Loaded unmanaged library=libuv in 0ms
    Information: [LoaderContainer]: Load unmanaged library name=libc

    Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
       at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.async_send(UvAsyncHandle handle)
       at Microsoft.AspNet.Server.Kestrel.Networking.UvAsyncHandle.Send()
       at Microsoft.AspNet.Server.Kestrel.KestrelThread.Post[T](Action`1 callback, T state)
       at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.ScheduleWrite()
       at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Write(ArraySegment`1 buffer, Action`3 callback, Object state, Boolean immediate, Boolean socketShutdownSend, Boolean socketDisconnect)
       at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.End(ProduceEndType endType)
       at Microsoft.AspNet.Server.Kestrel.Http.Connection.Microsoft.AspNet.Server.Kestrel.Http.IConnectionControl.End(ProduceEndType endType)
       at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__82.MoveNext()
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
       at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
       at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
    fail: Exit code -1073741819 from cmd
    fail: Stack trace:
       at View0d896d923b724a7a9036f1b853c4d685.Dnx(String command, String dnxDir, String dnvmUse) in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 1873
       at View0d896d923b724a7a9036f1b853c4d685.DnxTest(String projectFile, Boolean testParallel) in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 2368
       at View0d896d923b724a7a9036f1b853c4d685.<RenderViewLevel0>b__ed(String projectFile) in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 12014
       at System.Collections.Generic.List`1.ForEach(Action`1 action)
       at View0d896d923b724a7a9036f1b853c4d685.<RenderViewLevel0>b__eb() in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 12014
       at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
       at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
       at View0d896d923b724a7a9036f1b853c4d685.StartingTarget(String name) in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 3731
       at View0d896d923b724a7a9036f1b853c4d685.<RenderViewLevel0>b__8b() in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 4362
       at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
       at View0d896d923b724a7a9036f1b853c4d685.<RenderViewLevel0>b__83() in c:\Users\shalter\AppData\Local\Temp\a92bb20ef1d249d6b0887748abd9d1b8-1.cs:line 4218
       at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
       at Sake.Engine.SakeEngine.Execute(Options options)
       at Sake.Engine.SakeEngine.Execute(String[] args)
       at Sake.Program.Main(String[] args)

**Comment by benaadams** [comment] 2015-11-06 14:07
Resolved by #337

**Comment by muratg** [comment] 2015-12-21 22:54
Do we still have crashes?  It looks like @halter73 has a check-in for this already. Is this good to close?

**Comment by benaadams** [comment] 2015-12-21 22:55
All the ones I experienced where resolved by @halter73's change

**Comment by muratg** [comment] 2015-12-21 23:11
Thanks @benaadams!  Closing this one but folks can reopen if they see a failure.

**Closed by muratg** 2015-12-21 23:11 UTC
