### ISSUE TITLE
Deadlocks in production under linux

### ISSUE THREAD

**Issue by hheexx** [aspnet/KestrelHttpServer#1663] opened 2017-04-12 21:36 UTC
We moved out site to production recently.
When rps goes above ~1req/sec process starts deadlocking.
I had to start 4 processes and distribute load between them and implement watchdog to remain up. 

I tried under windows also.
There process often deadlocks on start if initial rush of traffic is large but if it starts it does not deadlock.

Application is angular2 spa with node prerendering and simple webapi using EF.

What would be way of debugging deadlock under linux?

**Comment by davidfowl** [comment] 2017-04-13 08:21
@hheexx What version of Kestrel?

**Comment by hheexx** [comment] 2017-04-13 14:01
1.1.1
Is there any way to test newer?

**Comment by davidfowl** [comment] 2017-04-16 00:38
That's the latest release. What can you provide some more information on the symptoms of the deadlock?

> What would be way of debugging deadlock under linux?

You could try attaching the vs remote debugger https://blogs.msdn.microsoft.com/visualstudioalm/2017/01/26/debugging-net-core-on-unix-over-ssh/

**Comment by hheexx** [comment] 2017-04-17 23:57
Ok I have process stuck now. I can't attach debugger to it.
> Unable to start debugging. Program path '' is missing or invalid.
https://i.gyazo.com/7ecc3a28c9ea71a617882f1045e7a605.png



Symptom is that I can't connect to Kastrel any more.
Unable to connect error in Firefox.

The most interesting part is I get error from EF right before/after deadlock:
`Apr 17 21:59:54 cxpublicdev[22287]: System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)`
I'm not sure is that cause or effect. SQL server is available for sure, only that process loses connection.

**Comment by davidfowl** [comment] 2017-04-18 05:14
@hheexx so the server doesn't respond to new connections. 

> Unable to start debugging. Program path '' is missing or invalid.

Can you make sure you have `unzip` installed on the server?

**Comment by hheexx** [comment] 2017-04-18 11:04
I do.
`hex@cxpublicdev:~$ unzip
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`

**Comment by hheexx** [comment] 2017-04-18 20:31
I tried from different machine. Same error.
Target is fully updated Ubuntu 16.04 server. Only thing installed beside dotnet is mono.


btw. are there any server variables/statistics I can print to console from time to time to help debugging? Something like number of requests executing, number of free threads etc.

**Comment by muratg** [comment] 2017-04-18 22:07
Assigning to @natemcmaster for investigation.

**Comment by natemcmaster** [comment] 2017-05-01 22:50
@hheexx when your process deadlocks, can you gather a process dump? This will help us to examine where the threads have deadlocked. 

This is the best step through I've found so far on how to gather and inspect a process dump on Linux:

http://blogs.microsoft.co.il/sasha/2017/02/26/analyzing-a-net-core-core-dump-on-linux/

Also, checkout https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md on steps for gathering information on your app's performance.

**Comment by hheexx** [comment] 2017-05-03 05:43
Thanks @natemcmaster!
Looks like exactly what I need!

I'm on vacation now, will try both solutions in a week.
I hope performance tracing will tell me what's wrong.

**Comment by hheexx** [comment] 2017-05-09 12:56
@natemcmaster I tried perfview. But it looks like most of data is not recorded. This is all I got.
https://i.gyazo.com/be10af94b30e971c137b2fe1cebb5876.png

I will try process dump now. How to submit it to you?

**Comment by natemcmaster** [comment] 2017-05-09 17:06
@hheexx sorry, here's the best answer I've found so far on creating the dump: http://stackoverflow.com/a/42494906/2526265. .NET Core Linux tooling is woefully undocumented.

**Comment by natemcmaster** [comment] 2017-06-20 17:29
@hheexx I did a little more digging and found better instructions for inspecting a .NET Core process on Linux.

Source: https://blogs.msdn.microsoft.com/wushuai/2017/03/13/debug-asp-net-core-via-lldb-on-ubuntu/

If you have a deadlocked process, you can attach to it using lldb and gather information about threads and stacks to help identify where the deadlock is coming from.

### Steps

#### Install and attach lldb

1. Install .NET Core: https://dot.net/core
2. Install lldb. For .NET Core  `sudo apt install lldb-3.6`.
3. Attach lldb do to your running process.
   ```
    sudo lldb-3.6
    (lldb) process attach $PID
    ```
4. Load the .NET Core plugin. (adjust path to your version of Microsoft.NETCore.App)
    ```
     (lldb) loadplugin plugin load /usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libsosplugin.so
     (lldb) setclrpath /usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/
    ```

The debugger is now attached and ready to use. To see available commands run `soshelp` from the lldb prompt or [this doc](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension)

#### Gather thread stacks
You can use some of the following commands to gather info about the running process.

- `eestack -EE`: shows the stack trace for all running threads (`-EE` filters the list to managed stacks only) 
- `clrstack`: shows the stack managed stack trace for the current select thread
- `thread list`: list all threads
- `clrthread`: list all managed threads. Left most column is maps to the thread number from `thread list`
- `thread select <n>`: change active thread.

**Example**
```
(lldb) clrthread
        ThreadCount:      4
        UnstartedThread:  0
        BackgroundThread: 2
        PendingThread:    0
        DeadThread:       1
        Hosted Runtime:   no
                                                                                                                Lock  
            ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
        1    1 1289 0000000000A40620  2020020 Preemptive  0x7f0b2ff0f238:0x7f0b2ff10060     00000000009FC660 0     Ukn 
        8    2 1290 00000000009C1440    21220 Preemptive  (nil):(nil)                       00000000009FC660 0     Ukn (Finalizer) 
        10    3 1292 0000000000B355C0    21220 Preemptive  0x7f0b2ff0cd98:0x7f0b2ff0e060     00000000009FC660 0     Ukn 
        XXXX    4    0 0000000000B39980  1031820 Preemptive  (nil):(nil)                       00000000009FC660 0     Ukn (Threadpool Worker) 

(lldb) thread select 1

(lldb) clrstack
    
    OS Thread Id: 0x1289 (1)
            Child SP               IP Call Site
    00007FFF28BF6B90 00007f0cbb567360 [HelperMethodFrame_1OBJ: 00007fff28bf6b90] System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean)
    00007FFF28BF6CC0 00007F0C4048194D System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)
    00007FFF28BF6CE0 00007F0C4048181F System.Threading.WaitHandle.WaitOne(Int32, Boolean)
    00007FFF28BF6D10 00007F0C40977585 Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost, System.Threading.CancellationToken, System.String)
    00007FFF28BF6E10 00007F0C409729D9 Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost)

(lldb) thread select 10

(lldb) clrstack

    OS Thread Id: 0x1292 (10)
            Child SP               IP Call Site
    00007F0CA2E0B7E8 00007f0cba9f0499 [InlinedCallFrame: 00007f0ca2e0b7e8] Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv+NativeMethods.uv_run(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle, Int32)
    00007F0CA2E0B7E8 00007f0c40984a9a [InlinedCallFrame: 00007f0ca2e0b7e8] Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv+NativeMethods.uv_run(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle, Int32)
```

**Comment by hheexx** [comment] 2017-06-20 17:49
Hi @natemcmaster ,

Thanks for detailed instructions!
We tested a lot and found the problem to probably be around HttpClient or a way solr-express library uses HttpClient in a sync way. 

We will try 2.0 soon and I hope it would help.

**Comment by natemcmaster** [comment] 2017-06-20 17:52
Ok, I'm going to close as it sounds like the issue isn't in Kestrel. We can re-open for more investigation if you find more issues.

**Closed by natemcmaster** 2017-06-20 17:52 UTC
Labels: 1 - Ready
