### ISSUE TITLE
index.html on wwwroot

### ISSUE THREAD

**Issue by VictorRicha** [aspnet/KestrelHttpServer#99] opened 2015-05-11 16:49 UTC
I'm trying to create an app serving only static files, so i put the app.UseStaticFiles(); in my Startup.cs file and put an index.html in my wwwroot folder.

What happens is, when i run the app using iisexpress on Windows and access localhost:5000 it works perfectly and serves the index.html in the root folder.
The problem is when i run the exact same app in Mac OSX using Kestrel. When i access localhost:5000, it doesnt find the index.html and throws a 404 error. When i go to localhost:5000/index.html though, it works.
Is there any way of telling Kestrel to use index.html without having to write the file name in address?

**Comment by Tratcher** [comment] 2015-05-11 16:53
Try UseFileServer() instead. It includes support for default files.

**Comment by Tratcher** [comment] 2015-05-11 16:55
Duplicate of https://github.com/aspnet/StaticFiles/issues/10

Also, on IIS express the native module ends up serving the file for you, not UseStaticFiles

**Closed by Tratcher** 2015-05-11 16:55 UTC
Labels: question
