### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4047 EPIPE broken pipe

### ISSUE THREAD

**Issue by ThomasArdal** [aspnet/KestrelHttpServer#1179] opened 2016-10-25 11:10 UTC
I'm hosting a web app on Azure App Services using ASP.NET Core, Kestrel and IISIntegration. Everything is based on the template given when creating a new ASP.NET Core project through Visual Studio 2015. From time to time, I'm experiencing the following error on my web app:

```
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4047 EPIPE broken pipe
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.write2(UvRequest req, UvStreamHandle handle, uv_buf_t* bufs, Int32 nbufs, UvStreamHandle sendHandle, uv_write_cb cb)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvWriteReq.Write2(UvStreamHandle handle, ArraySegment`1 bufs, UvStreamHandle sendHandle, Action`4 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.DispatchConnection(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.OnConnection(UvStreamHandle listenSocket, Int32 status)
```

The error is logged through Microsoft.Extensions.Logging and doesn't provide more data than the message and stack trace.

What can be the problem here?

**Comment by ThomasArdal** [comment] 2016-10-25 11:37
Tried requesting the URL from Postman a couple of times. I see a random pattern, where the service answers in most cases, but sometimes hang for the configured timeout in Postman and then log the UvException.

**Comment by halter73** [comment] 2016-10-25 17:56
A few questions to start.

- What Kestrel and IISIntegration packages are you using? 1.0.1 and 1.0.0 respectively?
- Do you only see these on Azure App Services?
- Can you give an approximate percentage of requests that fail? Is there anything at all unique about the requests that time out?

Thanks.

**Comment by ThomasArdal** [comment] 2016-10-26 05:36
I'm using version 1.0.0 of both Kestrel and IISIntegration. Will try to update to the newest versions there.

I'm only seeing these errors on App Services, yes.

I cannot give a percentage, since it seems random.

Will let you know when I try out the new versions.

**Comment by davenewza** [comment] 2016-10-26 07:32
I have the same problem. Our logs are riddled with this error.

**Comment by ThomasArdal** [comment] 2016-10-26 10:00
After upgrading to Kestrel 1.0.1, I start getting the following errors:

```
System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<>c.b__6_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<>c.b__6_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
```

It seems to be related to when I return NotFound() from my controller. If I'm correct about this, the error is logged through Microsoft.Extensions.Logging and users probably aren't affected, since they get back the 404 as expected. But I'm tired of having these errors in my log anyway.

**Comment by Tratcher** [comment] 2016-10-26 16:54
@ThomasArdal  https://github.com/aspnet/IISIntegration/issues/239#issuecomment-239543690
This is harmless, we're trying to find a way to deal with it.

**Comment by ThomasArdal** [comment] 2016-10-26 17:07
@Tratcher Is the 4047 also harmless?

**Comment by halter73** [comment] 2016-10-26 17:31
I'm less sure about the EPIPE error being harmless. My current theory is that it's the equivalent to an ECONNRESET in the Azure App Service environment which would be fairly benign error indicating the client terminated the connection abnormally. I will need to reproduce this issue to verify.

**Comment by ThomasArdal** [comment] 2016-10-26 17:52
@halter73 Here's the client code if that helps:

```
var client = new HttpClient
{
    BaseAddress = new Uri("http://example.com/"),
    Timeout = new TimeSpan(0, 0, 0, 10),
    DefaultRequestHeaders = { {"Accept", "application/json"} }
};
var response = await client.PostAsJsonAsync("/some/url", new { query });
if (!response.IsSuccessStatusCode) return NotFound();

return Ok(await response.Content.ReadAsAsync<MyType>());
```

Could it be if the request takes longer than 10 seconds?

**Comment by imperugo** [comment] 2016-10-27 07:27
Same here.
This morning my log was full of these errors.

```console
TcpListenerPrimary.OnConnection
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4047 EPIPE broken pipe
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvWriteReq.Write2(UvStreamHandle handle, ArraySegment`1 bufs, UvStreamHandle sendHandle, Action`4 callback, Object state)
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.DispatchConnection(UvStreamHandle socket)
  at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.OnConnection(UvStreamHandle listenSocket, Int32 status)
```

 The app is the same, so probably is something related to the server.
In my case is Azure App Service

**Comment by owenneil** [comment] 2016-10-31 20:48
We are seeing a similar issue on two different services. It is happening on Kestrel 1.0.0 and 1.0.1 (both with IISIntegration 1.0.0). When we restart the process it's usually more than an hour before we see one, but after a while (over the weekend for example) it is >50% of the time. We do see some of those -4047 errors in logs, although it doesn't seem like there are enough to account for the number of 502s.

**Comment by muratg** [comment] 2016-10-31 21:43
cc @davidebbo

**Comment by muratg** [comment] 2016-10-31 21:55
This is a dup of https://github.com/aspnet/KestrelHttpServer/issues/1182.... Since there are more discussions there, closing this one. Please continue the discussion over on #1182

**Closed by muratg** 2016-10-31 21:55 UTC
Labels: 1 - Ready, bug
