### ISSUE TITLE
[1.1.1] Fix Crash under high load (#1327)

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1346] opened 2017-02-07 20:35 UTC
#1327

@Eilon

**Comment by Eilon** [comment] 2017-02-08 22:53
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Closed** 2017-02-13 19:47 UTC
Labels: 3 - Done, bug, patch-approved

**Comment by newbie2006** [comment] 2017-02-17 01:46
I'm doing load test using VS2015 for an application that we're developing.  The application is behind IIS/Kestrel.  After couple mins, the server stopped responding, however, CPU and memory usage are fairly low.  The thread count under the Resource Monitor went up to several thousands.  I'm assuming this is caused by the similar issues that were discussed here regarding the thread lock on Kestrel.  Does anyone have any recommendations on what I should do to resolve the issues?  Thanks.

**Comment by Eilon** [comment] 2017-02-17 16:59
@newbie2006 if it's the same issue as what @halter73 fixed in this bug, we'll have the patch out in 2 - 3 weeks.

**Comment by cesarbs** [comment] 2017-02-17 18:44
I think @newbie2006 is referring to #1278.

Are you using static files? One solution some people found is to serve static files from a different IIS website without Kestrel.

Are you passing `HttpContext.RequestAborted` to any `WriteAsync()` calls in your code?

**Comment by halter73** [comment] 2017-02-17 20:15
@cesarbs is likely right. The bug referenced in this issue causes Kestrel's process to die instead of becoming unresponsive. Fortunately, both issues will be fixed in the same patch releases.

**Comment by newbie2006** [comment] 2017-02-17 20:22
Do you happen to have a rough estimate when the patch will be release?  We are almost ready to release our new app until we hit this problem during load testing.  Our backup plan was to take everything that we got and move it to MVC5 but that's the last option.

**Comment by newbie2006** [comment] 2017-02-17 20:31
@cesarbs, the static files that we have are the *.css, *.js. under wwwroot folder.

**Comment by halter73** [comment] 2017-02-17 20:35
@Eilon gave the rough estimate as 2 - 3 weeks. #1278 will be fixed by the same patch.

The workaround that might be a bit easier than moving to MVC5 in the meantime is to serve static files (e.g. *.css, *.js or whatever else is under the wwwroot folder) using IIS's static file handler instead of using ASP.NET Core's UseStaticFiles/UseDefaultFiles/UseDirectoryBrowser methods until the patched packages are released.

**Comment by newbie2006** [comment] 2017-02-17 20:48
@halter73, so does this mean that I would set up another app under IIS that would hold and serve these static files, then just reference these files from the ASP.NET core app and remove the app.UseStaticFiles() from the Startup.cs?

**Comment by newbie2006** [comment] 2017-02-17 23:23
I've followed the instructions in this thread https://weblogs.asp.net/imranbaloch/leveraging-iis-static-file-feature-in-aspnetcore.  Is that the right way to do it?

**Comment by halter73** [comment] 2017-02-18 00:12
@newbie2006 That looks right to me. Make sure you have the extensions for all the static files you're serving configured. By removing app.UseStaticFiles(), it should be pretty obvious if you haven't since you'd likely see 404s.

**Comment by newbie2006** [comment] 2017-02-18 00:46
@halter73 
I was able to get it to work in VS2015 but when deploying to IIS 8.5, I got the 500 internal server error due to the section below in the web.config file.  Am I missing something on the server?

    <rewrite>
      <rules>
        <rule name="wwwroot">
          <match url="([\S]+[.](svg|js|css|png|gif|jpg|jpeg))" />
          <action type="Rewrite" url="wwwroot/{R:1}" />
        </rule> 
      </rules>
    </rewrite>

**Comment by benaadams** [comment] 2017-02-18 01:05
500 probably suggests misconfigured web.config; can you browse the site on localhost (e.g. via rdp) as that would tell you more.

You have the `<rewrite>` in the right section?
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
```
And only a single `<system.webServer>` and `<rewrite>` at route? (rather than in a `<location>` subsection)

**Comment by newbie2006** [comment] 2017-02-18 01:31
This is the content of the web.config.  When browsing on the server, it's showing error 500.19 with the Config Source:
   -1: 
    0: 
 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
  	<staticContent>
      <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="360.00:00:00" />
    </staticContent>
    
    <rewrite>
      <rules>
        <rule name="wwwroot">
          <match url="([\S]+[.](svg|js|css|png|gif|jpg|jpeg))" />
          <action type="Rewrite" url="wwwroot/{R:1}" /> 
        </rule> 
      </rules>
    </rewrite>
    
    <handlers>
    	<add name="StaticFileModuleSvg" path="*.svg" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleJs" path="*.js" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleCss" path="*.css" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleJpeg" path="*.jpeg" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleJpg" path="*.jpg" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModulePng" path="*.png" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleGif" path="*.gif" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />      
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="MyApp.exe" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true" />
    <httpProtocol>
      <customHeaders>
        <add name="X-Frame-Options" value="SAMEORIGIN" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
  <system.web>
    <httpCookies httpOnlyCookies="true" />
    <customErrors mode = "off" />
  </system.web>
</configuration>

**Comment by newbie2006** [comment] 2017-02-18 01:55
Installed the URLRewrite extension and that fixed the problem.  Thanks for all the help!
