### ISSUE TITLE
Dev HTTPS Certificate not loading when assembly name differs from project name.

### ISSUE THREAD

**Issue by Naragato** [aspnet/KestrelHttpServer#2727] opened 2018-07-16 15:45 UTC
If your project name differs from the assembly name the dev ssl certificate isn't loaded.  A certificate is created with the project name, but the library uses the assembly name.

The result is the following exception:

```System.InvalidOperationException: 'Unable to configure HTTPS endpoint. No server certificate was 
specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.'
```

Renaming said certificate to the assembly works, until the certificate is recreated.  As a temporary work around I'm using a symbolic link.

**Comment by Tratcher** [comment] 2018-07-16 15:49
@javiercn? The dev cert doesn't use the project or assembly name, it's a general cert for all dev projects.

Is this a docker scenario?

**Comment by Naragato** [comment] 2018-07-16 15:52
Yes apologizes I neglected to included that detail.

**Comment by javiercn** [comment] 2018-07-17 16:34
@tratcher The cert is reused for all projects, but that’s an implementation detail. The file name for the cert needs to match HostingEnvironment.Name

This is by design, unless tooling is not using the right name when exporting the cert.

**Comment by muratg** [comment] 2018-08-10 19:39
Closing based on @javiercn's comment.

**Closed by muratg** 2018-08-10 19:39 UTC
