### ISSUE TITLE
Hosting problems on azure

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#698] opened 2016-03-15 16:53 UTC
_From @vsotov on March 15, 2016 16:39_

I've deployed project to Azure App Service, everything went ok, except after some random amount of time kestrel seems to loose requests. 

In logs I see something like
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://renta-api.azurewebsites.net/projects  

without any continuation. Than after some time everything is working ok.
Maybe this is an issue with HttpPlatformHandler.

Here is its configuration 
`<handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log"
   `

PS I use standard right-click deploy project method.

_Copied from original issue: aspnet/Hosting#650_

**Comment by vsotov** [comment] 2016-03-16 16:37
Tried to deploy the same solution using dnx46 or dnxcore50 - no difference. Really seems like a problem with IIS <> Kestrel communication problem

**Comment by muratg** [comment] 2016-03-16 17:12
@vsotov Did you see any exceptions like the following in your logs?
```
fail: Microsoft.AspNet.Server.Kestrel[0]
      DispatchPipe.Accept
      Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4050 ENOTSOCK socket operation on non-socket
         at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
         at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.accept(UvStreamHandle server, UvStreamHandle client)
         at Microsoft.AspNet.Server.Kestrel.Http.ListenerSecondary.ReadStartCallback(UvStreamHandle handle, Int32 status)
```

This is possibly a dup of https://github.com/aspnet/KestrelHttpServer/issues/582

**Comment by vsotov** [comment] 2016-03-16 17:49
No, I searched through logs and found this exception
```
warn: Microsoft.AspNet.Server.Kestrel[0]
      Connection processing ended abnormally
      Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Microsoft.AspNet.Server.Kestrel.Http.ISocketOutput.Write(ArraySegment`1 buffer, Boolean immediate)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.WriteChunkedResponseSuffix()
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<ProduceEnd>d__96.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
```

**Comment by cesarbs** [comment] 2016-04-20 21:09
@vsotov A few questions:

1) It seems you're on RC1. Have you tried it with the latest development bits?
2) Any other exceptions in the logs?
3) Are you using HTTPS?

**Comment by stefangordon** [comment] 2016-04-21 22:44
I can confirm this is happening on latest in cidev and is fixed by forcing single threaded per #582

**Comment by cesarbs** [comment] 2016-04-22 00:54
@stefangordon Thanks! So hopefully they're both the same issue and should go away when Azure has the fix available on their side.

**Comment by cesarbs** [comment] 2016-05-02 20:53
@vsotov Which region is your app deployed to?

**Comment by vsotov** [comment] 2016-05-03 12:56
@cesarbs It's deployed to West Europe region

**Comment by cesarbs** [comment] 2016-05-03 23:50
@vsotov Ok. The fix is not available in all regions yet, but it should be in a few days. I'll close this for now since there's no more action required on our side.

**Comment by cesarbs** [comment] 2016-05-03 23:50
ping @muratg @Eilon

**Closed by cesarbs** 2016-05-03 23:50 UTC

**Comment by muratg** [comment] 2016-05-03 23:54
@cesarbs thanks, I was sure there was one more bug about this issue, but didn't get the time to search for it yet :)

**Comment by cesarbs** [comment] 2016-05-09 20:04
@vsotov I've just verified my test web app for this issue and it looks like it's fixed in West Europe. Can you check that you don't see the errors anymore when running without the ThreadCount = 1 workaround?

**Comment by vsotov** [comment] 2016-05-11 11:27
@cesarbs I've checked my application, no errors. Everything works great.

**Comment by cesarbs** [comment] 2016-05-11 18:58
@vsotov Thanks!
