### ISSUE TITLE
Test failure: LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#2860] opened 2018-08-28 02:01 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=540403&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) occasionally with the following error:
```
System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStream(Stream rawStream, Uri requestUri, Boolean validateCertificate) in /_/test/Kestrel.InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 129
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/test/Kestrel.InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 34
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/test/Kestrel.InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 29
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.LoggingConnectionAdapterTests.LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter() in /_/test/Kestrel.InMemory.FunctionalTests/LoggingConnectionAdapterTests.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter at 2018-08-28T01:06:46
| [0.036s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.048s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.049s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
| [0.102s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGCGA35HG4L" started.
| [0.229s] LoggingConnectionAdapter Debug: ReadAsync[5] 16 03 01 01 3E 
|                                          \x16\x03\x01\x01>
| [0.237s] LoggingConnectionAdapter Debug: ReadAsync[318] 01 00 01 3A 03 03 D8 C9 CE BC E2 CF 20 80 30 2F 6B 90 0E 17 CF 7A F5 D6 78 3D 5C 22 D7 3F CA 3A 6A 9F E2 84 65 45 00 00 AA C0 30 C0 2C C0 28 C0 24 C0 14 C0 0A 00 A5 00 A3 00 A1 00 9F 00 6B 00 6A 00 69 00 68 00 39 00 38 00 37 00 36 00 88 00 87 00 86 00 85 C0 32 C0 2E C0 2A C0 26 C0 0F C0 05 00 9D 00 3D 00 35 00 84 C0 2F C0 2B C0 27 C0 23 C0 13 C0 09 00 A4 00 A2 00 A0 00 9E 00 67 00 40 00 3F 00 3E 00 33 00 32 00 31 00 30 00 9A 00 99 00 98 00 97 00 45 00 44 00 43 00 42 C0 31 C0 2D C0 29 C0 25 C0 0E C0 04 00 9C 00 3C 00 2F 00 96 00 41 C0 11 C0 07 C0 0C C0 02 00 05 00 04 C0 12 C0 08 00 16 00 13 00 10 00 0D C0 0D C0 03 00 0A 00 FF 01 00 00 67 00 00 00 0E 00 0C 00 00 09 6C 6F 63 61 6C 68 6F 73 74 00 0B 00 04 03 00 01 02 00 0A 00 1C 00 1A 00 17 00 19 00 1C 00 1B 00 18 00 1A 00 16 00 0E 00 0D 00 0B 00 0C 00 09 00 0A 00 23 00 00 00 0D 00 20 00 1E 06 01 06 02 06 03 05 01 05 02 05 03 04 01 04 02 04 03 03 01 03 02 03 03 02 01 02 02 02 03 00 0F 00 01 01 
|                                          \x01\0\x01:\x03\x03ØÉÎ¼âÏ 0/k\x0e\x17ÏzõÖx=\"×?Ê:jâeE\0\0ªÀ0À,À(À$À\x14À
|                                          \0¥\0£\0¡\0\0k\0j\0i\0h\09\08\07\06\0\0\0\0À2À.À*À&À\x0fÀ\x05\0\0=\05\0À/À+À'À#À\x13À    \0¤\0¢\0 \0\0g\0@\0?\0>\03\02\01\00\0\0\0\0\0E\0D\0C\0BÀ1À-À)À%À\x0eÀ\x04\0\0<\0/\0\0AÀ\x11À\x07À\u000cÀ\x02\0\x05\0\x04À\x12À\x08\0\x16\0\x13\0\x10\0
À
À\x03\0
|                                          \0ÿ\x01\0\0g\0\0\0\x0e\0\u000c\0\0    localhost\0\u000b\0\x04\x03\0\x01\x02\0
|                                          \0\x1c\0\x1a\0\x17\0\x19\0\x1c\0\x1b\0\x18\0\x1a\0\x16\0\x0e\0
\0\u000b\0\u000c\0    \0
|                                          \0#\0\0\0
\0 \0\x1e\x06\x01\x06\x02\x06\x03\x05\x01\x05\x02\x05\x03\x04\x01\x04\x02\x04\x03\x03\x01\x03\x02\x03\x03\x02\x01\x02\x02\x02\x03\0\x0f\0\x01\x01
| [0.260s] LoggingConnectionAdapter Debug: WriteAsync[1192] 16 03 03 00 42 02 00 00 3E 03 03 E4 F0 B6 43 B9 D4 F0 D0 2F 22 E8 B5 BD B7 47 37 CC 75 87 62 1E C8 19 62 AA 2D 19 C9 F0 29 00 6B 00 C0 30 00 00 16 FF 01 00 01 00 00 0B 00 04 03 00 01 02 00 23 00 00 00 0F 00 01 01 16 03 03 03 01 0B 00 02 FD 00 02 FA 00 02 F7 30 82 02 F3 30 82 01 DF A0 03 02 01 02 02 10 32 B6 9D 2C 9F C5 0F AF 4F 1D A2 21 1D 5F 70 E1 30 09 06 05 2B 0E 03 02 1D 05 00 30 14 31 12 30 10 06 03 55 04 03 13 09 6C 6F 63 61 6C 68 6F 73 74 30 1E 17 0D 31 35 30 39 31 36 30 36 32 31 30 39 5A 17 0D 31 36 30 39 31 36 30 36 32 31 30 38 5A 30 14 31 12 30 10 06 03 55 04 03 13 09 6C 6F 63 61 6C 68 6F 73 74 30 82 01 22 30 0D 06 09 2A 86 48 86 F7 0D 01 01 01 05 00 03 82 01 0F 00 30 82 01 0A 02 82 01 01 00 9A 51 99 A1 A0 D6 08 E5 D9 58 35 E5 C1 A5 09 8C 6B DF 76 95 29 C5 87 68 1B 18 87 06 25 28 C2 BF E5 F9 F8 C5 AB EC 69 AA 08 D2 FF 95 52 5D DE B8 AA AD C4 AE 87 CE 73 BC 94 AD 31 40 34 C7 59 1B A7 55 7F 34 5A A0 73 57 39 94 23 9A F6 C6 30 E3 8E 25 0C 38 CD CF C1 B7 90 D3 AB 27 91 B7 8E B6 83 12 CF FC 79 08 13 8E 4D 13 CA 91 BE C1 FA B9 4D 41 37 5A BF A4 7C 6C 9E 46 
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-28 02:01
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by halter73** [comment] 2018-08-28 18:06
This seems to be a logging error. Here's the test output that's cut off:

```
| [1.159s] Microsoft.AspNetCore.Server.Kestrel Error: Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
| System.AggregateException: An error occurred while writing to logger(s). (Index was outside the bounds of the array.) ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
|    at Serilog.Parsing.MessageTemplateParser.ParsePropertyToken(Int32 startAt, String messageTemplate, Int32& next)
|    at Serilog.Parsing.MessageTemplateParser.Tokenize(String messageTemplate)+MoveNext()
|    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
|    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
|    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
|    at Serilog.Events.MessageTemplate..ctor(String text, IEnumerable`1 tokens)
|    at Serilog.Parsing.MessageTemplateParser.Parse(String messageTemplate)
|    at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    --- End of inner exception stack trace ---
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.LoggingStream.Log(String method, ReadOnlySpan`1 buffer) in /_/src/Kestrel.Core/Adapter/Internal/LoggingStream.cs:line 184
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.LoggingStream.ReadAsync(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Adapter/Internal/LoggingStream.cs:line 110
|    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
|    at System.Net.Security.SslState.ThrowIfExceptional()
|    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
|    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
|    at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
|    at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
|    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
| --- End of stack trace from previous location where exception was thrown ---
|    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context) in /_/src/Kestrel.Core/Internal/HttpsConnectionAdapter.cs:line 174
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ApplyConnectionAdaptersAsync() in /_/src/Kestrel.Core/Internal/HttpConnection.cs:line 318
| ---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
|    at Serilog.Parsing.MessageTemplateParser.ParsePropertyToken(Int32 startAt, String messageTemplate, Int32& next)
|    at Serilog.Parsing.MessageTemplateParser.Tokenize(String messageTemplate)+MoveNext()
|    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
|    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
|    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
|    at Serilog.Events.MessageTemplate..ctor(String text, IEnumerable`1 tokens)
|    at Serilog.Parsing.MessageTemplateParser.Parse(String messageTemplate)
|    at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
| [1.226s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGCGA35HG4L" disconnecting.
| [1.436s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [1.460s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGCGA35HG4L" stopped.
| [1.486s] TestLifetime Information: Finished test LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter in 1.4854447s
```

@BrennanConroy

**Comment by muratg** [comment] 2018-08-29 17:45
@pakrym can you take a look at the possible logging fail here?

**Comment by pakrym** [comment] 2018-09-06 18:41
I think this is caused by kestrel logging binary content in format string directly, Serilog tries to parse format string and fails. We'll need to verify if having it as formatting argument helps.

**Comment by Tratcher** [comment] 2018-09-06 18:50
Do we know what character range is causing the error? The repro is inconsistent.

**Comment by pakrym** [comment] 2018-09-06 19:09
It's not just a character, it's a combination of characters, it's parsing property token so I guess it's a combination of `{` with other characters.

**Comment by aspnet-hello** [comment] 2018-09-22 01:51
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559029&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1:
- LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Tratcher** [comment] 2018-09-24 23:19
This most recent failure looks unrelated. Some kind of cert validation error.

```
System.UnauthorizedAccessException : Access to the path '/home/aspnetagent/.dotnet/corefx/cryptography/x509stores/my' is denied.
---- System.IO.IOException : Bad file descriptor
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.CloneTo(X509Certificate2Collection collection)
   at System.Security.Cryptography.X509Certificates.X509Store.get_Certificates()
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.FindCandidates(X509Certificate2 leaf, X509Certificate2Collection extraStore, HashSet`1 downloaded, HashSet`1 systemTrusted, TimeSpan& remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslState.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.LoggingConnectionAdapterTests.LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter() in /_/test/Kestrel.FunctionalTests/LoggingConnectionAdapterTests.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
```

**Comment by muratg** [comment] 2018-09-25 00:06
Is that the dev cert for SSL?

**Comment by Tratcher** [comment] 2018-09-25 00:29
It shouldn't be, the tests don't use the dev cert.

**Comment by Tratcher** [comment] 2018-09-25 15:36
The server cert is checked in with the tests.
https://github.com/aspnet/KestrelHttpServer/blob/01b35bc3913204ebbd308b4719a20168466d0183/test/shared/TestResources.cs#L13

But this error is happened on the client when it tries to validate the chain trust (BuildChainAndVerifyProperties). It tries to open the local cert store to find root certs and gets access denied, even though we didn't need the local cert store because the server cert was self-signed.

**Comment by aspnet-hello** [comment] 2018-10-18 22:11
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=580161&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 1:58:41 PM:
- LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter

**Closed** 2018-10-23 17:13 UTC
Labels: 3 - Done, Branch:2.1, test-failure
