### ISSUE TITLE
Test Kestrel's ability to handle bursts of new connections being established

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#610] opened 2016-02-01 23:08 UTC
Most of Kestrel's benchmarking so far has focused processing requests as quickly as possible on a fixed number of connections (using wrk). We should also test Kestrel's ability to handle bursts of new connections being established and then also disconnecting under high load.

Possibly related: #604

**Comment by benaadams** [comment] 2016-02-01 23:25
This is a good scenario; fast connection churn is a horrible use-case for aspnet4.5+ websockets (due to native pinning); which is mitigated by using pooled buffers. However; Kestrel shouldn't suffer from this (even in websocket scenario); but it does use pinned buffers so it is a good buffer to confirm.

Also connection+disconnection is heavier weight than keep-alive requests.

**Comment by benaadams** [comment] 2016-02-13 03:16
Allocations with 1M non keep-alive connections

![no-keepalive-a](http://aoa.blob.core.windows.net/aspnet/no-keepalive-0.png)
![no-keepalive-b](http://aoa.blob.core.windows.net/aspnet/no-keepalive-1.png)
![no-keepalive-c](http://aoa.blob.core.windows.net/aspnet/no-keepalive-2.png)

**Comment by benaadams** [comment] 2016-02-13 03:57
Breaking out System.Object as its very non-specific

![system-object](http://aoa.blob.core.windows.net/aspnet/system-object.png)

**Comment by benaadams** [comment] 2016-02-13 05:40
This was one of the causes for the server GC around 8 secs into this video https://www.youtube.com/watch?v=BTHimgTauwQ

**Comment by SajayAntony** [comment] 2016-02-23 02:03
@taoliseki #652 might be related to this. Please keep this on your radar.

**Comment by halter73** [comment] 2016-02-29 20:49
@mikeharder Not sure you want to take a look at this. It might be better to add these kinds of non-TechEmpower related stress tests/benchmarks to the https://github.com/aspnet/Performance/ repository.

**Comment by SajayAntony** [comment] 2016-02-29 20:51
@mikeharder - specifically this is where the targeted tests are - https://github.com/aspnet/Performance/tree/dev/testapp

**Comment by taoliseki** [comment] 2016-03-01 18:22
The scenario we were measuring from perf side is:
1. Constant load: 10k users with 10k persistent connections and 1 request per 10 seconds per user 
2. Bursty load: 1k users kick in and leave

For the bursty part, 1k WCAT threads were used to disconnect/reconnect per request during a one-hour time window, which resulted in around 3k connection/disconnections per second. I did not see any obvious perf/stress issues (e,g, memory footprint stays stable).  

I did run into some 503 issues at some point. Those issues were fixed by tweaking IIS configurations. You can refer to #652 for more details if you are interested.

**Comment by benaadams** [comment] 2016-03-02 06:26
Probably worth doing some https testing in similar fashion since it is part of the repo.

We did experience memory growth->heavy GC in this area previously (stress testing, not production); but that was prior to the SocketInput memory block release, so hopefully its resolved now.

**Comment by SajayAntony** [comment] 2016-03-02 06:51
Tao could you also provide the memory foot print and how it varied over time. I think @yuwaMSFT has a neat way to capture this over time.

**Comment by yuwaMSFT** [comment] 2016-03-02 18:07
For Windows we can collect memory related perf counters.

For Linux we can use top/atop to get the memory foot print over time.

**Comment by benaadams** [comment] 2016-03-02 18:21
For linux you are probably better using `/proc/xxx` e.g. `/proc/[pid]/status` 

http://www.linuxhowtos.org/manpages/5/proc.htm

**Comment by muratg** [comment] 2016-07-25 20:10
This issue was moved to aspnet/Performance#165

**Closed by muratg** 2016-07-25 20:10 UTC
Labels: stress

**Comment by foragerr** [comment] 2017-06-01 00:57
@benaadams what are the screenshots you posted from? Is that windows only? Could I view similar metrics for a kestrel instance running on linux?

**Comment by halter73** [comment] 2017-06-01 18:53
@foragerr The screenshots are from dotTrace which is currently Windows only. Linux .NET core profiling tools haven't yet caught up with their Window's counterparts, but it's possible to [debug Linux .NET core processes using lldb and libsosplugin.so](http://blogs.microsoft.co.il/sasha/2017/02/26/analyzing-a-net-core-core-dump-on-linux/). You can also [collect CPU samples on Linux and view them with PerfView on Windows](https://blogs.msdn.microsoft.com/vancem/2016/10/07/collecting-performance-data-on-linux-using-perfcollect-and-perfview/).
