### ISSUE TITLE
Establish which ipv4/ipv6 socket addresses to open

### ISSUE THREAD

**Issue by lodejard** [aspnet/KestrelHttpServer#7] opened 2014-06-28 02:59 UTC
Assumption is localhost should be ipv4+ipv6 loopback, numeric addresses should be that address in ipv4 or ipv6, and any other name including + and * should be ipv4+ipv6 any ip

**Comment by Eilon** [comment] 2015-10-06 04:58
This is a super old bug but it was in the alpha4 milestone, so moving to RC1 to reevaluate.

**Comment by Tratcher** [comment] 2015-10-06 21:43
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/231

**Comment by stevedesmond-ca** [comment] 2015-11-10 19:25
this and aspnet/Announcements#80 have the milestone as rc1, but based on the description of aspnet/Announcements#80, should they be beta8 instead / in addition?

**Comment by Eilon** [comment] 2015-11-10 19:26
@Tratcher ?

**Comment by Tratcher** [comment] 2015-11-10 20:02
Updated. The initial change was in beta8: https://github.com/aspnet/KestrelHttpServer/commit/f0137b7b9ea25ee4769931da1e8d255a47605e85

**Closed by Tratcher** 2015-11-10 20:02 UTC
Labels: 0 - Backlog, bug, duplicate

**Comment by guyajun0** [comment] 2015-11-11 09:13
var remoteIp = context.Connection.RemoteIpAddress.ToString();
why it is always null after I upgrade it from beta7 to beta8? Thank you!

**Comment by guyajun0** [comment] 2015-11-11 09:16
I Used asp.net 5, VS beta8 and dnx beta8 get null remote ip, when I use dnx beta7,it is ok to get the remote ip address,I am confused.
