### ISSUE TITLE
Kestrel server hang due to Deadlock on disconnect handling

### ISSUE THREAD

**Issue by yuwaMSFT** [aspnet/KestrelHttpServer#700] opened 2016-03-17 06:49 UTC
I was running a stress test for simple POST request with 100 clients. Hit the deadlock in several minutes. What happened would be the racing in the two call back threads:
Thread 6 got signal of disconnection, and started to abort the current connection (holding lock on content, but waiting lock on connection state obj); meanwhile thread 8 was executing writeAsync callback and saw error, and started to shut down as well (holding lock on connection state obj, but waiting lock on content obj). Apparantly this causes deadlock due to race condition.

dump is shared offline. This is build rc2-16595:
  *    1.0.0-rc2-16595   coreclr x64          win
 

```
0:008> !syncblk

Index SyncBlock MonitorHeld Recursion Owning Thread Info  SyncBlock Owner

   25 000000e92195fd18            3         1 000000e92338c6e0 20a0   8   000000e6fc833c78 System.Object

   26 000000e92195fd68            3         1 000000e92338e620 c24   6   000000e6fc833e00 System.Object

 

Basically, thread 8 was holding connection state lock on object 000000e6fc833c78, and was waiting on Context lock on object 000000e6fc833e00 (owned by thread 6); 

0:008> !clrstack

OS Thread Id: 0x20a0 (8)

        Child SP               IP Call Site

000000e924c1e5d8 00007ffeb16f0c6a [GCFrame: 000000e924c1e5d8] 

000000e924c1e710 00007ffeb16f0c6a [GCFrame: 000000e924c1e710] 

000000e924c1e748 00007ffeb16f0c6a [HelperMethodFrame_1OBJ: 000000e924c1e748] System.Threading.Monitor.Enter(System.Object)

000000e924c1e860 00007ffe364ec1ff Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput.WriteAsync(System.ArraySegment`1<Byte>, System.Threading.CancellationToken, Boolean, Boolean, Boolean, Boolean) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\SocketInputExtensions.cs @ 17]

000000e924c1e960 00007ffe364f4b5f Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput.End(Microsoft.AspNetCore.Server.Kestrel.Http.ProduceEndType)

000000e924c1e9f0 00007ffe364ecaa4 Microsoft.AspNetCore.Server.Kestrel.Http.Connection.Microsoft.AspNetCore.Server.Kestrel.Http.IConnectionControl.End(Microsoft.AspNetCore.Server.Kestrel.Http.ProduceEndType) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\ConnectionContext.cs @ 23]

000000e924c1ea50 00007ffe361a4db0 Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__2[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].MoveNext() [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\FrameOfT.cs @ 144]

000000e924c1eab0 00007ffe361a4b32 Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__2[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].MoveNext() [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\FrameResponseHeaders.cs @ 77]

000000e924c1eba0 00007ffe8ffed0e3 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

000000e924c1ec10 00007ffe900569d1 System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()

000000e924c1ec60 00007ffe90056a9d System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()

000000e924c1ec90 00007ffe364ef5bd Microsoft.AspNetCore.Server.Kestrel.Infrastructure.LoggingThreadPool.<.ctor>b__4_0(System.Object) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Infrastructure\LoggingThreadPool.cs @ 51]

000000e924c1ecd0 00007ffe8ffed0e3 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

000000e924c1ed40 00007ffe90167e24 System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

000000e924c1ed80 00007ffe900532e7 System.Threading.ThreadPoolWorkQueue.Dispatch()

000000e924c1f1f0 00007ffe9594c6f3 [DebuggerU2MCatchHandlerFrame: 000000e924c1f1f0]

 

0:008> !mdt 000000e6fc833d48

000000e6fc833d48 (Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput)

    _thread:000000e7fc782078 (Microsoft.AspNetCore.Server.Kestrel.KestrelThread)

    _socket:000000e6fc833b08 (Microsoft.AspNetCore.Server.Kestrel.Networking.UvTcpHandle)

    _connection:000000e6fc833b88 (Microsoft.AspNetCore.Server.Kestrel.Http.Connection)

    _connectionId:000000e6fc833c90 (System.String) Length=13, String="0HKQDSETAK3CS"

    _log:000000e7fc77f7a0 (Microsoft.AspNetCore.Server.Kestrel.KestrelTrace)

    _threadPool:000000e7fc781410 (Microsoft.AspNetCore.Server.Kestrel.Infrastructure.LoggingThreadPool)

    _returnLock:000000e6fc833de8 (System.Object)

    _head:000000e7fc7d1af0 (Microsoft.AspNetCore.Server.Kestrel.Infrastructure.MemoryPoolBlock)

    _tail:000000e7fc7d1af0 (Microsoft.AspNetCore.Server.Kestrel.Infrastructure.MemoryPoolBlock)

    _lastStart:(Microsoft.AspNetCore.Server.Kestrel.Infrastructure.MemoryPoolIterator) VALTYPE (MT=00007ffe35fda7b0, ADDR=000000e6fc833dd0)

    _contextLock:000000e6fc833e00 (System.Object)

    _writePending:false (System.Boolean)

    _cancelled:false (System.Boolean)

    _numBytesPreCompleted:0x65 (System.Int32)

    _lastWriteError:NULL (System.Exception)

    _nextWriteContext:NULL (Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput+WriteContext)

    _tasksPending:000000e6fc833e18 (System.Collections.Generic.Queue`1[[Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput+WaitingTask, Microsoft.AspNetCore.Server.Kestrel]])

    _writeContextPool:000000e6fc834660 (System.Collections.Generic.Queue`1[[Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput+WriteContext, Microsoft.AspNetCore.Server.Kestrel]])

    _writeReqPool:000000e7fc7949a8 (System.Collections.Generic.Queue`1[[Microsoft.AspNetCore.Server.Kestrel.Networking.UvWriteReq, Microsoft.AspNetCore.Server.Kestrel]])

 

 

thread 6 was holding Context lock on object 000000e6fc833e00, and was waiting on connection state lock on object 000000e6fc833c78 (owned by thread 8).

0:006> !clrstack

OS Thread Id: 0xc24 (6)

        Child SP               IP Call Site

000000e923dceee8 00007ffeb16f0c6a [GCFrame: 000000e923dceee8] 

000000e923dcf020 00007ffeb16f0c6a [GCFrame: 000000e923dcf020] 

000000e923dcf058 00007ffeb16f0c6a [HelperMethodFrame_1OBJ: 000000e923dcf058] System.Threading.Monitor.Enter(System.Object)

000000e923dcf170 00007ffe364f50f5 Microsoft.AspNetCore.Server.Kestrel.Http.Connection.Abort() [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\Connection.cs @ 203]

000000e923dcf1d0 00007ffe364ee96d Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput.OnWriteCompleted(WriteContext) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\SocketOutput.cs @ 318]

000000e923dcf220 00007ffe364ee8aa Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput+WriteContext.CompleteWithContextLock() [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Http\SocketOutput.cs @ 641]

000000e923dcf270 00007ffe364eded1 Microsoft.AspNetCore.Server.Kestrel.Networking.UvWriteReq.UvWriteCb(IntPtr, Int32) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Infrastructure\HttpComponentFactory.cs @ 18]

000000e923dcf300 00007ffe360ce2e7 DomainBoundILStubClass.IL_STUB_ReversePInvoke(Int64, Int32)

000000e923dcf480 00007ffe9594c80a [InlinedCallFrame: 000000e923dcf480] Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods.uv_run(Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle, Int32)

000000e923dcf480 00007ffe360c466e [InlinedCallFrame: 000000e923dcf480] Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv+NativeMethods.uv_run(Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle, Int32)

000000e923dcf450 00007ffe360c466e DomainBoundILStubClass.IL_STUB_PInvoke(Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle, Int32)

000000e923dcf520 00007ffe360c45a5 Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.run(Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle, Int32) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Networking\Libuv.cs @ 166]

000000e923dcf550 00007ffe360c3a82 Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart(System.Object) [D:\b\work\b056445a7a030b99\src\Microsoft.AspNetCore.Server.Kestrel\Infrastructure\KestrelThread.cs @ 238]

000000e923dcf5c0 00007ffe8ffed0e3 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

000000e923dcf7f0 00007ffe9594c6f3 [GCFrame: 000000e923dcf7f0] 

000000e923dcfa80 00007ffe9594c6f3 [DebuggerU2MCatchHandlerFrame: 000000e923dcfa80]

 

0:006> !mdv

Frame 0x8: (Microsoft.AspNetCore.Server.Kestrel.Http.Connection.Abort()):

[A0]:this: <UNAVAILABLE> (Microsoft.AspNetCore.Server.Kestrel.Http.Connection)

[L0]:(null):000000e6fc833c78 (System.Object)

[L1]:(null): <UNAVAILABLE> (System.Boolean)
```

**Comment by halter73** [comment] 2016-03-17 14:48
This is a dupe of #684 (You can see the same stacks [here](https://github.com/aspnet/KestrelHttpServer/issues/684#issuecomment-194594910) which was fixed by #690.

@cesarbs Can probably help find the first build number with the fix in.

**Closed by halter73** 2016-03-17 14:48 UTC
