### ISSUE TITLE
Allow to replace the server cert at runtime

### ISSUE THREAD

**Issue by iftahbe** [aspnet/KestrelHttpServer#2103] opened 2017-10-08 12:29 UTC
Right now, the SSL certificate that Kestrel will use is here:

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Https/Internal/HttpsConnectionAdapter.cs#L25-L26

There are certain scenarios that we want to support replacing the certificate while the server is still running. This can be done quite easily if we could set the `_serverCertificate` so all new connections will be able to use that.

Scenarios for that include using Let's Encrypt certificates and not having to restart every 3 months.

While making it public is one option, I think it would be better to _not_ hold a reference to the `_serverCertificate` from the options but use the value in the options itself. That will mean that the caller could hold on to the options and change the certificate value used without messing with any internal state.

**Comment by Tratcher** [comment] 2017-10-08 13:46
As an alternative, we hope to get SNI support at some point and one of the API proposals is for a callback where you can select your own cert for each connection. This would allow you to change the cert dynamically.

**Comment by Drawaes** [comment] 2017-10-08 15:41
I would say at worst, this should wait until the "option bag" for SslStream is completed, then you could expose that or pass it into Kestrel. At best you will get the callback as mentioned above...

**Comment by Tratcher** [comment] 2017-10-08 17:08
I doubt the new options bag will be exposed by kestrel APIs. For now it's Core only.

**Comment by davidfowl** [comment] 2017-10-08 17:17
The middleware could expose a callback today but before we do anything, somebody should hack together a lets encrypt connection adapter for kestrel so that we can see all of the touch points.

**Comment by ayende** [comment] 2017-10-09 22:37
I implemented a very rough draft here:
https://github.com/ayende/Kestrel.LetsEncrypt

No error handling and this is mostly to see that I _could_ do it. 
Pretty much the only thing that I actually needed to do was to change the way Kestrel is getting the certificate. But in order to do that I had to pretty much bring all of `Kestrel.Https`

**Comment by davidfowl** [comment] 2017-10-10 04:50
@ayende Sweet! 

> But in order to do that I had to pretty much bring all of Kestrel.Https

Yea, but that's not a big deal it's only a few files. This should also let us prove out if a callback is enough.

**Comment by ayende** [comment] 2017-10-10 05:38
A callback for the certificate would be enough, yes.

**Comment by davidfowl** [comment] 2017-10-10 05:43
This looks kinda crazy https://github.com/ayende/Kestrel.LetsEncrypt/blob/f9facd8159f61aecd5053d49776ad3538d460b92/Kestrel.LetsEncrypt/Internal/LetsEncryptCertificateFetcher.cs.

**Comment by ayende** [comment] 2017-10-10 05:53
The major issue here is that we need some way to prove to Let's Encrypt that we are the owners of the domain. We can do that in various ways, but the easiest from our perspective at this point is to use the `http-01` challenge.

This basically means that we ask Let's Encrypt for a certificate, and we need to prove we own this domain. We do that by getting a token from Let's Encrypt and asking it to call back to us (over HTTP, using port 80) and thus proving how this can happen.

I thought about having a kestrel instance that is always on using port 80, but it seems easier to just open it to the few seconds we need to do the verification.

It would probably be easier to do this using DNS, but that require you to use some API and bind you to a specific DNS provider. 

I couldn't find a way to make Kestrel route based on the listen source anyway, and I don't think it matters too much.

**Comment by Drawaes** [comment] 2017-10-10 07:14
https://github.com/dotnet/corefx/issues/22510

Can't use protected data. Like secure string it either throws or just isn't  (secure)

**Comment by Drawaes** [comment] 2017-10-10 07:15
Let me qualify that. On anything other than windows

**Comment by ayende** [comment] 2017-10-10 07:20
The actual problem here is that we need to persist the cert to disk. We can do that with OS permissions so only the current user can touch it, or provide callbacks to the user to handle caching the certificate if they want to customize that (such as storing in a vault).

**Comment by Drawaes** [comment] 2017-10-10 07:22
Why does it need to go to disk? Can't you just use the bytes [] ?

**Comment by ayende** [comment] 2017-10-10 07:25
Let's Encrypt encourages you to keep the same certificate around, rather than renew it on every start.
Otherwise, you might hit rate limits.

**Comment by Drawaes** [comment] 2017-10-10 07:28
I guess that's a problem for people with crappy code that restart often of which I am sure yours is not ;). Maybe make an option to "persist certificates to disk"

**Comment by ayende** [comment] 2017-10-10 07:48
@Drawaes Consider the case of a user running in development mode. 
They still want to use HTTPS, and while they can run with a self signed, it is much easier all around to be able to use a real one from Let's Encrypt. In that case, it is easy to have a debug / run cycle that will hit the limits.

For that matter, even CI that continuously deploy will have to deal with this, in production.
I think that a better option would indeed be to update the code there to use a callback, instead of making this decision.

**Comment by ayende** [comment] 2017-10-10 07:57
I updated the code, so this should be clearer now.

**Comment by Drawaes** [comment] 2017-10-10 08:01
Yeah dev it's fine...

**Comment by Soarc** [comment] 2017-10-10 20:45
@ayende for development mode user could use staging let's encrypt [environment](https://letsencrypt.org/docs/staging-environment/).

**Comment by Drawaes** [comment] 2017-10-10 21:15
Actually the more I think about it, when does a Dev have a publicly facing DNS to get a cert in the first place?

**Comment by Soarc** [comment] 2017-10-11 06:17
@Drawaes In my case when Dev is developing let's encrypt's automated certificate renewal :)

**Comment by benaadams** [comment] 2017-10-11 06:36
> Let's Encrypt encourages you to keep the same certificate around, rather than renew it on every start.
Otherwise, you might hit rate limits.

They only issue domain validated certs and [only for 90 days at a time](https://letsencrypt.org/2015/11/09/why-90-days.html). Rate is 5 times a week for same cert; 20 times for domain and all its sub-domains; which is quite low for a test server - so you'd want to be caching it.

@ayende's use ASP.NET's [`IDataProtectionProvider` and `IDataProtector`](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/overview)?

**Comment by ayende** [comment] 2017-10-11 11:43
@Soarc Except that you want to hit your website in the browser (or from you manager's browser) and have it Just Work.

@Drawaes dynamic DNS would do quite well for these cases. Or CI deployments, etc.

@benaadams Yes, you have to cache that.
I couldn't find how  `IDataProtecter` would work on Linux, and anyway, I just externalize all of that so user can handle it on their own.

**Comment by benaadams** [comment] 2017-10-11 11:52
It works via DI so is its externalized to the users choice of mechanism; though you'd probably need to change the `LetsEncryptCertificateFetcher` to a service to grab it?

**Comment by ayende** [comment] 2017-10-11 12:09
The problem is that at this point you'll need to provide Not just how to protect it but also _where_ to protect it.
The fetcher is also going to start a whole new Kestrel instance to do the `http-01` validation, so confusing with regards to whose service provider to use.

**Comment by benaadams** [comment] 2017-10-18 04:58
Apache has gone built-in for let's encrypt https://letsencrypt.org/2017/10/17/acme-support-in-apache-httpd.html

**Comment by muratg** [comment] 2017-11-27 20:50
@joshfree To implement this, we'll need SNI on Core to support something like this in a future release. Heads-up.

cc @shirhatti

**Comment by joshfree** [comment] 2017-12-04 19:54
@saurabh500 @corivera

**Comment by saurabh500** [comment] 2017-12-04 20:10
SNI uses the SSLStream from .Net Core to transmit data. I am not sure how SNI is relevant here.

**Comment by muratg** [comment] 2017-12-04 20:22
@saurabh500 Proposal at [this issue](https://github.com/dotnet/corefx/issues/24553) would possibly enable this.   @Tratcher can share some more details.

@shirhatti @DamianEdwards Let's decide if we want this feature in 2.2 which would drive feature requirements from the CoreFX side.

**Comment by Tratcher** [comment] 2017-12-04 20:25
We know this feature is not the intended purpose of SNI, however the the proposed SNI API with the delegate callback would also enable this scenario.

**Comment by saurabh500** [comment] 2017-12-04 20:25
Ah OK. The SNI here is `Server Name Indication` and not the SNI that SQL server uses. SNI in Sql server is an acronym for SQL Network Interface. @joshfree We are not the right team here :)

**Comment by Tratcher** [comment] 2017-12-04 20:31
IIS for reference: https://weblog.west-wind.com/posts/2016/feb/22/using-lets-encrypt-with-iis-on-windows

**Comment by muratg** [comment] 2018-02-13 23:55
Closing this one. We'll revisit the bigger scenario in the future.

**Closed by muratg** 2018-02-13 23:55 UTC
Labels: enhancement
