### ISSUE TITLE
Remove PathBase logic from Kestrel

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1403] opened 2017-02-27 05:17 UTC
Kestrel no longer needs the logic to split path and path base. That is handled in the IIS integration middleware.

**Comment by cesarbs** [comment] 2017-02-27 17:21
Dupe of https://github.com/aspnet/KestrelHttpServer/issues/1050

**Closed by cesarbs** 2017-02-27 17:21 UTC
