### ISSUE TITLE
error on connection in kestrel (non-ascii or null character)

### ISSUE THREAD

**Issue by SHAliakbari** [aspnet/KestrelHttpServer#949] opened 2016-07-02 19:40 UTC
I install visual studio 2015 update and dot net core 1 in my station (windows 10). But when i start visual studio and create default asp.net core site and run it without changing a bit , i get following error :

info: 

`Microsoft.AspNetCore.Server.Kestrel[17]

 Connection id "0HKT2L6GCL845" bad request data: "The input string contains non-ASCII or null characters." Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters. at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end) at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeMessageHeaders(SocketInput input, FrameRequestHeaders requestHeaders) at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame1.<RequestProcessingAsync>d__2.MoveNext()
  warn: Microsoft.AspNetCore.Server.Kestrel[0]
        Connection processing ended abnormally
  Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
     at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end)
     at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeMessageHeaders(SocketInput input, FrameRequestHeaders requestHeaders)
     at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame1.d__2.MoveNext()`

but in other station every thing is ok

**Comment by Tratcher** [comment] 2016-07-05 16:46
Can you use fiddler to capture the request headers?

**Comment by SHAliakbari** [comment] 2016-07-06 06:47
I found problem . cookies . 
When i remove all cookies from browser , the problem gone .
thanks

**Comment by superlogical** [comment] 2016-07-28 03:02
I've just had this issue when running under Docker 

````
web_1     | 2016-07-28 02:58:25 [Information] Request starting HTTP/1.1 POST http://localhost:5000/api/v1/message multipart/form-data; boundary="3577c707-e79d-43d6-a796-f546a4995d91" 134191
web_1     | 2016-07-28 02:58:25 [Information] Executing action method "Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web)" with arguments (["System.Threading.CancellationToken"]) - ModelState is Valid
web_1     | 2016-07-28 02:58:25 [Information] Executing ObjectResult, writing value "Microsoft.AspNetCore.Mvc.ControllerContext".
web_1     | 2016-07-28 02:58:25 [Information] Executed action "Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web)" in 70.0806ms
web_1     | 2016-07-28 02:58:25 [Information] Request finished in 70.6151ms 500 application/json; charset=utf-8
web_1     | 2016-07-28 02:58:25 [Information] Connection id ""0HKTMIBDFS13J"" bad request data: ""The input string contains non-ASCII or null characters.""
web_1     | Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(SocketInput input)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
web_1     | 2016-07-28 02:58:25 [Warning] Connection processing ended abnormally
web_1     | Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(SocketInput input)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
````

**Comment by davidfowl** [comment] 2016-07-28 03:05
What do your headers look like? You can turn on connection logging to see the raw bytes printed out https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L42

**Comment by superlogical** [comment] 2016-07-28 03:29
@davidfowl Hmm not sure if that's going to be a good idea uploading the logs... The file that I am uploading is a JPEG, with connection logging turned it spews out hundreds and hundreds of lines of incomprehensible text

This is the file I'm using to test with...

![doge](https://cloud.githubusercontent.com/assets/287641/17200266/daa1c1da-54d7-11e6-9453-aa268dcc5aa8.jpg)

**Comment by davidfowl** [comment] 2016-07-28 03:30
> web_1     | Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.

Would be great if you can get the headers then.

**Comment by superlogical** [comment] 2016-07-28 03:32
https://gist.github.com/superlogical/0cc8e505bb1ff853eaaa20432ca4bfea

**Comment by davidfowl** [comment] 2016-07-28 03:41
Where's the exception in that trace?

**Comment by superlogical** [comment] 2016-07-28 04:00
I've updated that gist with an actual failed request.. sorry!
https://gist.github.com/superlogical/0cc8e505bb1ff853eaaa20432ca4bfea

Client side I get this back from the sever:

[15:58:00 ERR] Failed to send. Body: {"messageId":null,"totalUploadElapsed":"00:00:00","uploadResults":null,"args":null,"validationResults":[{"memberNames":[],"errorMessage":"System.IO.IOException: Unexpected end of stream.\n   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.<ReadAsync>d__36.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Xero.Mail.Web.Controllers.MessageController.<PostMessage>d__6.MoveNext()"}],"ok":false}

**Comment by superlogical** [comment] 2016-07-28 20:00
@davidfowl Not sure what I should do to try and debug this. I could get a ubuntu VM and try and reproduce the bug?

I'm sending the request using HttpClient so seems it's a bug in Kestrel. Works fine on Windows 10.

**Comment by davidfowl** [comment] 2016-07-28 22:46
That exception looks different. Are you still seeing the original exception or just this new one? 

> @davidfowl Not sure what I should do to try and debug this. I could get a ubuntu VM and try and reproduce the bug?

Can you reproduce the bug on demand reliably? Is it only on non windows?

> I'm sending the request using HttpClient so seems it's a bug in Kestrel. Works fine on Windows 10.

Sure, let's get a repro and some data.

> Is there any way to get the connection logging to log to a file instead? Might be easier to get you a dump that way.

Not currently, but you can copy the source code and make it do that. 
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Filter/KestrelServerOptionsConnectionLoggingExtensions.cs

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Filter/LoggingConnectionFilter.cs

**Comment by superlogical** [comment] 2016-07-28 22:47
We've just updated to the latest version of the sample upload controller here:
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Controllers/FileController.cs

We are seeing it read the same `fileSection` multiple times through the while loop. This is where we are logging:
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Controllers/FileController.cs#L71-L75

Check these logs:

````
web_1     | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
web_1     |       Request starting HTTP/1.1 POST http://localhost:5000/api/v1/message multipart/form-data; boundary=----WebKitFormBoundaryJgCy9H7FZiZhlWox 129839
web_1     | dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
web_1     |       Request successfully matched the route with name '' and template 'api/v1/message'.
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
web_1     |       Executing action Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web)
web_1     | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
web_1     |       Executing action method Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web) with arguments (System.Threading.CancellationToken) - ModelState is Valid
web_1     | 2016-07-28 22:43:20 [Information] Parsed file @"{ Name = attachment, FileName = doge.jpg, key = 53de5239-6f35-4ef2-b25c-21fed1ca6c6a, mimeType = image/jpeg, length = 15929 }"
web_1     | 2016-07-28 22:43:20 [Information] Parsed file @"{ Name = attachment, FileName = doge.jpg, key = b903587c-1086-4ca6-bdcd-bb6fcda17909, mimeType = image/jpeg, length = 15933 }"
web_1     | 2016-07-28 22:43:20 [Information] Parsed file @"{ Name = attachment, FileName = doge.jpg, key = eef04cf1-bb92-4bba-bdca-5f11baddcf52, mimeType = image/jpeg, length = 15933 }"
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[4]
web_1     |       Connection id "0HKTN71RSM9IU" paused.
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
web_1     |       Executed action method Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web), returned result Microsoft.AspNetCore.Mvc.ObjectResult.
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[4]
web_1     |       No information found on request to perform content negotiation.
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[2]
web_1     |       Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
web_1     | info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
web_1     |       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
web_1     | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
web_1     |       Executed action Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web) in 66.9419ms
web_1     | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
web_1     |       Request finished in 69.049ms 500 application/json; charset=utf-8
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[9]
web_1     |       Connection id "0HKTN71RSM9IU" completed keep alive response.
web_1     | info: Microsoft.AspNetCore.Server.Kestrel[17]
web_1     |       Connection id "0HKTN71RSM9IU" bad request data: "The input string contains non-ASCII or null characters."
web_1     | Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(SocketInput input)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
web_1     | warn: Microsoft.AspNetCore.Server.Kestrel[0]
web_1     |       Connection processing ended abnormally
web_1     | Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(SocketInput input)
web_1     |    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[10]
web_1     |       Connection id "0HKTN71RSM9IU" disconnecting.
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[7]
web_1     |       Connection id "0HKTN71RSM9IU" sending FIN.
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[8]
web_1     |       Connection id "0HKTN71RSM9IU" sent FIN with status "0".
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[2]
web_1     |       Connection id "0HKTN71RSM9IU" stopped.
````

**Comment by superlogical** [comment] 2016-07-28 22:51
Yeah we  can reproduce it every time when we run it in a Docker container.  

We are using the `microsoft/dotnet:1.0.0-core` container.

We are in the process of setting up a Ubuntu VM. I will see if it has issues there to. I'll make a sample repo and upload it to Github.

**Comment by Tratcher** [comment] 2016-07-28 22:57
@cesarbs

**Comment by halter73** [comment] 2016-07-29 07:02
@superlogical Does this happen with a single request? If so, it seems that the server thinks that the request ended before it actually did and returns a 500:

```
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
web_1     |       Executed action method Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web), returned result Microsoft.AspNetCore.Mvc.ObjectResult.
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[4]
web_1     |       No information found on request to perform content negotiation.
web_1     | dbug: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[2]
web_1     |       Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
web_1     | info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
web_1     |       Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
web_1     | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
web_1     |       Executed action Xero.Mail.Web.Controllers.MessageController.PostMessage (Xero.Mail.Web) in 66.9419ms
web_1     | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
web_1     |       Request finished in 69.049ms 500 application/json; charset=utf-8
web_1     | dbug: Microsoft.AspNetCore.Server.Kestrel[9]
web_1     |       Connection id "0HKTN71RSM9IU" completed keep alive response.
```

It's only then that Kestrel tries to read to "following" request and sees garbage data in what it thinks is the start line. Is there a `Content-Length` header set on the request, or is it chunked?

**Comment by cesarbs** [comment] 2016-08-01 21:20
@superlogical Are you running Docker on Windows?

**Comment by superlogical** [comment] 2016-08-01 21:24
Yeah we find this issue when running Docker on Windows.

Yesterday we got a Ubuntu 16.04  64-bit VM running, and tested it without any issues.

So we are now going to try running Docker in the Ubuntu VM and test those containers out there. If we don't see any problems doing that today then we will probably conclude that it is a Docker for Windows issue.

**Comment by cesarbs** [comment] 2016-08-01 21:32
@superlogical It's very likely you're running into this issue: https://github.com/aspnet/Home/issues/1678

The latest Docker for Windows should have it fixed.

**Comment by superlogical** [comment] 2016-08-01 21:45
@cesarbs That's cool! Glad we got to the bottom of this.

By the way we just tested the same setup running Docker on Ubuntu -- And we don't see any issues.

**Comment by halter73** [comment] 2016-08-03 18:00
@muratg Should we close this since it's been resolved?

**Closed** 2016-08-03 21:06 UTC

**Comment by mbpakalin** [comment] 2017-05-02 06:59
Is this problem solved ? 
The problem same as like you, when i delete cookies it worked fine.

**Comment by davidfowl** [comment] 2017-05-02 07:00
Kestrel doesn't support non asciii headers.
