### ISSUE TITLE
[Patch] Flaky: RequestTargetProcessingTests.NonPathRequestTargetSetInRawTarget(requestTarget: "../.") 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KestrelHttpServer#1704] opened 2017-04-17 21:28 UTC
```
System.AggregateException : One or more errors occurred. (Safe handle has been closed)
---- System.ObjectDisposedException : Safe handle has been closed
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
```

**Comment by pranavkm** [comment] 2017-04-17 21:28
cc @pakrym  \ @muratg

**Comment by pranavkm** [comment] 2017-04-17 21:28
This is on Ubuntu

**Comment by muratg** [comment] 2017-04-17 22:02
@pakrym could you take a look?

**Comment by pakrym** [comment] 2017-04-17 23:55
@muratg I'd like to wait for @halter73 fix for shutdown first

**Comment by mikeharder** [comment] 2017-04-19 18:06
Saw a similar error on "Partner Acquisition -> Build: Linux 20886":

```
[Step 3/3] [xUnit.net 00:00:12.3550683] 
	 [Test collection for Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.BadHttpRequestTests (1)] BadRequestIfHostHeaderDoesNotMatchRequestTarget(requestTarget: "GET http://contoso.com/", host: "http://contoso.com") (7s)
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_async_send(UvAsyncHandle handle)
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.async_send(UvAsyncHandle handle)
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvHandle.ReleaseHandle()
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvHandle.ReleaseHandle()   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
[Step 3/3] Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.async_send(UvAsyncHandle handle)   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvHandle.ReleaseHandle()   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()   at System.Runtime.InteropServices.SafeHandle.Finalize()
[Step 3/3] The active test run was aborted. Reason: Unable to communicate with test host process.
[Step 3/3] Test Run Failed.
```

http://aspnetci/viewLog.html?buildId=204841&tab=buildResultsDiv&buildTypeId=CoreCLR_Linux

This is impacting a lot of our builds so fixing this should be a priority.

**Comment by pakrym** [comment] 2017-04-19 18:49
@mikeharder While failure looks similar we had so many changes in dev that I expect it to be different. There is also @halter73 fix for shutdown in PR that can fix it.

**Comment by halter73** [comment] 2017-04-20 22:28
#1707 Is the PR that should fix this. It was merged yesterday evening.

**Comment by pranavkm** [comment] 2017-04-25 19:48
@halter73 the fix went in to dev, this one talks about seeing this issue in patch branches. Was the fix back ported \ skipped?

**Comment by halter73** [comment] 2017-04-26 18:57
@pranavkm Which patch? Has it been seen at all since it was first reported?

#1707 fixes a regression that was introduced in dev, it wouldn't fix anything in 1.0 or 1.1.

**Comment by Eilon** [comment] 2017-04-27 16:54
Should we consider disabling the test? Would we be losing any significant coverage?

**Comment by halter73** [comment] 2017-04-27 21:56
@Eilon I don't think this is flakyness in NonPathRequestTargetSetInRawTarget specifically. We either have to fix this issue (assuming it hasn't been fixed by #1707), or disable all the Kestrel functional tests.

ObjectDisposedExceptions were somewhat common for the past 2 weeks until #1707 was merged in dev. I am surprised this was seen in a patch branch. I wonder if the "[Patch]" in the tile was a mixup one the issue was created. It's unfortunate the original issue doesn't include a link to the CI failure.

@pranavkm Do you have a link to this test failing in a patch branch at any point in time? Or even in the dev branch within the last week?

**Comment by pranavkm** [comment] 2017-04-28 21:13
Here's  a link - http://aspnetci/viewLog.html?buildId=203576. That said the test has a 99.5% pass rate in the patch, so perhaps it's not entirely too flaky.

**Comment by Eilon** [comment] 2017-05-02 23:57
Moving this out.

**Comment by pakrym** [comment] 2017-05-31 21:29
Closing because issue is not specific to `NonPathRequestTargetSetInRawTarget` test and test itself is not entirely too flaky. Please reopen if found otherwise.

**Closed by pakrym** 2017-05-31 21:29 UTC
Labels: 1 - Ready, task
