### ISSUE TITLE
Kestrel tests fail in VSTS

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#2755] opened 2018-07-26 15:55 UTC
We tried enabled Kestrel in VSTS. Something in that environment does not agree with the way we've written tests. I've disabled VSTS altogether because it is not a useful PR validation check if it always fails.

https://dotnet.visualstudio.com/public/_build/index?context=allDefinitions&path=%5Caspnet%5CKestrelHttpServer&definitionId=66&_a=completed

<img src="https://user-images.githubusercontent.com/2696087/43273532-8634c62a-90b1-11e8-97da-9220393f1c3a.png" width="300" />

**Comment by halter73** [comment] 2018-07-27 00:32
The most common failure I see is happening on Windows and looks like the following:

```
2018-07-26T01:45:43.7323594Z   [xUnit.net 00:00:27.66]     RequestFeatureContainsRawTarget(requestTarget: "/path") [FAIL]
2018-07-26T01:45:43.7411615Z   Failed   RequestFeatureContainsRawTarget(requestTarget: "/path")
2018-07-26T01:45:43.7955393Z RUNDOTNET : error Message:  [D:\a\.dotnet\buildtools\korebuild\2.2.0-preview1-17099\KoreBuild.proj]
2018-07-26T01:45:43.7972574Z    System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
2018-07-26T01:45:43.7973154Z   ---- System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
2018-07-26T01:45:43.8009137Z   Stack Trace:
2018-07-26T01:45:43.8013188Z      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
2018-07-26T01:45:43.8019093Z      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2018-07-26T01:45:43.8029028Z      at System.IO.StreamReader.ReadBufferAsync()
2018-07-26T01:45:43.8040099Z      at System.IO.StreamReader.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
2018-07-26T01:45:43.8040621Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2018-07-26T01:45:43.8074522Z      at Microsoft.AspNetCore.Testing.TestConnection.ReceiveEnd(String[] lines) in /_/test/shared/TestConnection.cs:line 157
2018-07-26T01:45:43.8115510Z      at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTargetProcessingTests.RequestFeatureContainsRawTarget(String requestTarget) in /_/test/Kestrel.FunctionalTests/RequestTargetProcessingTests.cs:line 85
2018-07-26T01:45:43.8304200Z   --- End of stack trace from previous location where exception was thrown ---
2018-07-26T01:45:43.8316209Z   ----- Inner Stack Trace -----
2018-07-26T01:45:43.8322672Z   
2018-07-26T01:45:43.8372665Z   Standard Output Messages:
2018-07-26T01:45:43.8383651Z    | [0.001s] TestLifetime Information: Starting test RequestFeatureContainsRawTarget-/path at 2018-07-26T01:45:33
2018-07-26T01:45:43.8390651Z    | [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
2018-07-26T01:45:43.8397257Z    | [9.179s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
2018-07-26T01:45:43.8442337Z    | [9.179s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2018-07-26T01:45:43.8446239Z    | [9.409s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJ5VM0FEN" started.
2018-07-26T01:45:43.9550574Z    | [9.591s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///path  
2018-07-26T01:45:43.9567347Z    | [9.622s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJ5VM0FEN" completed keep alive response.
2018-07-26T01:45:43.9691164Z    | [9.622s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 31.031ms 200 
2018-07-26T01:45:43.9694248Z    | [9.970s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFIJ5VM0FEN" received FIN.
2018-07-26T01:45:43.9696226Z    | [10.000s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJ5VM0FEN" disconnecting.
2018-07-26T01:45:43.9703553Z    | [10.000s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFIJ5VM0FEN" sending FIN.
2018-07-26T01:45:43.9709366Z    | [10.001s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFIJ5VM0FEN" stopped.
2018-07-26T01:45:43.9715065Z    | [10.072s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
2018-07-26T01:45:43.9753675Z    | [10.251s] TestLifetime Information: Finished test RequestFeatureContainsRawTarget-/path in 10.2506703s
2018-07-26T01:45:43.9754254Z   
```

https://dotnet.visualstudio.com/public/_build/results?buildId=8157&view=logs
https://dotnet.visualstudio.com/public/_build/results?buildId=8059&view=logs
https://dotnet.visualstudio.com/public/_build/results?buildId=7006&view=logs

I don't recall seeing any "The I/O operation has been aborted because of either a thread exit or an application request." errors on any of the other CI's. According to the server logs, the server is trying to keep the connection open with a keep-alive response and it was the _client_ that sent a FIN. It looks like it's only failing with the libuv transport. I'm not sure how to even begin trying to diagnose the root cause for this.

CanRebindToEndpoint is an actually flaky test which is more flaky than usual on VSTS.

**Comment by natemcmaster** [comment] 2018-08-02 23:26
> I'm not sure how to even begin trying to diagnose the root cause for this.

If this were not in VSTS, what would you look for? 

Latest run shows 22 of 61,712 tests failing.

<img src="https://user-images.githubusercontent.com/2696087/43616283-a105e8d4-9670-11e8-9a68-a047ddebbdf6.png" width="400" />

https://dotnet.visualstudio.com/public/_build/results?buildId=10329&_a=summary&view=ms.vss-test-web.test-result-details

cc @muratg @Tratcher

**Comment by halter73** [comment] 2018-08-03 18:04
I'm working on a major test refactor as part of my work for #2635 to make the tests more reliable. I don't expect it will fix this issue, but it might reduce the failures simply do to us establishing less real socket connections. Once that's complete, I'll look into this.

The biggest issue in VSTS seems to be the uptick in "SocketException : The I/O operation has been aborted because of either a thread exit or an application request.". The first I remember seeing this kind of error reported was in #2701. I think I'm going to need to start a thread with some bcl folks about this. I'm looking to gather more details, like a firmer date for when these exceptions started, and if we consumed any new runtime builds immediately prior.

If there's a way to gather a network capture on VSTS using wireshark or similar, that might be helpful assuming it doesn't ruin the repro.

**Comment by natemcmaster** [comment] 2018-08-03 18:51
There is nothing built-in to VSTS to capture this data, but if you can write code to launch wireshark as a console command to capture data as a log file, we can probably get it to run in VSTS.

**Comment by muratg** [comment] 2018-09-06 19:54
@halter73 can you please take a look?

**Comment by halter73** [comment] 2018-09-06 22:15
@muratg The issue with VSTS is rooted in dotnet/corefx#30691. We can't really fix that ourselves. For some reason the frequency of this failure was higher on the VSTS agents. @natemcmaster mentioned we're beefing up the agents, so that might help. Another reason the failure rate should also be lower is because now we have most of the functional tests running in-memory.

Maybe we should just reenable them and see how flaky the tests still are.

**Comment by muratg** [comment] 2018-10-19 21:28
Closing this one, as we think this is not going to happen anymore. 

We have another bug to enable VSTS for check-in tests.

**Closed by muratg** 2018-10-19 21:28 UTC
Labels: Flaky, flaky test, test-failure
