### ISSUE TITLE
Flaky Test: DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2668] opened 2018-06-14 17:10 UTC
https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/dev/job/osx-Configuration_Debug_prtest/208/consoleFull
```
0:04:08    Failed   DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse
10:04:08  RUNDOTNET : error Message:  [/Users/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17087/KoreBuild.proj]
10:04:08     System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
10:04:08    Stack Trace:
10:04:08       at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
10:04:08       at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
10:04:08    --- End of stack trace from previous location where exception was thrown ---
10:04:08       at System.Net.Security.SslState.ThrowIfExceptional()
10:04:08       at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
10:04:08       at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
10:04:08       at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
10:04:08       at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_2(IAsyncResult iar)
10:04:08       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
10:04:08    --- End of stack trace from previous location where exception was thrown ---
10:04:08       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
10:04:08       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
10:04:08       at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
10:04:08       at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 576
10:04:08    --- End of stack trace from previous location where exception was thrown ---
10:04:08    Standard Output Messages:
10:04:08     | [0.001s] TestLifetime Information: Starting test DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse at 2018-06-14T17:04:01
10:04:08     | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
10:04:08  RUNDOTNET : | [0.074s] Microsoft.AspNetCore.Server.Kestrel warning : Overriding address(es) 'http://127.0.0.1:0'. Binding to endpoints defined in UseKestrel() instead. [/Users/dotnet-bot/.dotnet/buildtools/korebuild/2.2.0-preview1-17087/KoreBuild.proj]
10:04:08     | [0.080s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
10:04:08     | [0.080s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests
10:04:08     | [0.082s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLEI32HAVP3J" started.
10:04:08     | [0.082s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLEI32HAVP3J" received FIN.
10:04:08     | [0.083s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLEI32HAVP3J" sending FIN.
10:04:08     | [0.085s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
10:04:08     | [0.086s] HttpsConnectionAdapter Debug: Failed to authenticate HTTPS connection.
10:04:08     | System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
10:04:08     |    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
10:04:08     |    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
10:04:08     |    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
10:04:08     |    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
10:04:08     |    at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
10:04:08     |    at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
10:04:08     |    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
10:04:08     |    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
10:04:08     |    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
10:04:08     |    at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
10:04:08     |    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.InnerOnConnectionAsync(ConnectionAdapterContext context) in /_/src/Kestrel.Core/Internal/HttpsConnectionAdapter.cs:line 170
10:04:08     | [0.088s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLEI32HAVP3J" stopped.
10:04:08     | [0.101s] TestLifetime Information: Finished test DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse in 0.099813s
```

**Comment by shirhatti** [comment] 2018-06-15 19:32
@halter73 will have a look. Might be a dupe

**Comment by halter73** [comment] 2018-06-15 22:04
The logs show the server received a FIN from the client prior to the HTTPS authentication failure. This seems to be a pretty clear dupe of #2635

**Closed by halter73** 2018-06-15 22:04 UTC
Labels: duplicate, flaky test
