### ISSUE TITLE
Running benchmarks against Kestrel results in socket read/write errors at concurrency levels above ~32

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/KestrelHttpServer#142] opened 2015-07-23 02:02 UTC
Running the plaintext test in the aspnet/benchmarks repo we start to see socket read/write errors reported by wrk once we the connection count goes above 32. As the concurrency goes higher, so do the errors. Subsequent runs at the same concurrency level appear to show increased error counts too.

E.g. command: `wrk -c 64 -t 8 -d 10 http://10.0.0.100:5001/plaintext`

Eg. output:

```
Running 10s test @ http://10.0.0.100:5001/plaintext
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.18ms    1.77ms  45.24ms   98.33%
    Req/Sec     7.83k   810.60    11.00k    88.04%
  613559 requests in 10.10s, 67.29MB read
  Socket errors: connect 0, read 0, write 296, timeout 0
Requests/sec:  60750.59
Transfer/sec:      6.66MB
```

**Comment by halter73** [comment] 2015-09-22 21:44
I tried to repo this with the benchmark repo and the same wrk command with no luck.

@DamianEdwards have you seen these read/write errors recently?

**Comment by DamianEdwards** [comment] 2015-09-23 00:18
@halter73 I believe I was still seeing this issue. Someone else appears to have the Smurf Lab in a particular state right now so I don't want to reset it to try again without their blessing.

**Comment by halter73** [comment] 2015-09-24 02:11
These seem to be connect failures masquerading as write failures. Wrk uses a nonblocking version of connect and only sees failures during the first write. When the first write fails with errorno 111 "Connection refused", wrk then reconnects.

After removing [this line](https://github.com/wg/wrk/blob/7cdede916a53da253c995767a92eec36a245a2cc/src/wrk.c#L241) from wrk.c, I went from seeing only write errors like in the original bug report, to seeing they are all really connect errors.

    $ ./wrk -c 512 -t 32 -d 5 http://10.0.0.100:5001/plaintext
    Running 5s test @ http://10.0.0.100:5001/plaintext
      32 threads and 512 connections
      Thread Stats  Avg     Stdev Max  +/-      Stdev
        Latency     5.19ms  3.06ms     65.47ms  92.83%
        Req/Sec     3.06k   626.12     6.73k    88.46%
      479464 requests in 5.10s, 531.80MB read
      Socket errors: connect 45, read 0, write 0, timeout 0
    Requests/sec:  94031.85
    Transfer/sec:    104.30MB

Despite all the connection failures, tracing reveals that our connection callback that we pass to uv_listen only gets called 513 times as expected if you leave wrk unchanged. If you removed the line to make connect(2) a non-blocking call then our connection callback gets called (513 - connect errors) times.

@lodejard thinks this might be related to [Constants.ListenBacklog](https://github.com/aspnet/KestrelHttpServer/blob/c4bf10d6e9d77f75fd2a413c87a6186ac52d3c69/src/Microsoft.AspNet.Server.Kestrel/Infrastructure/Constants.cs#L8) which is passed to [uv_listen](http://docs.libuv.org/en/latest/stream.html#c.uv_listen). However, increasing this constant doesn't seem to cause any significant reduction in connect failures.

P.S. I'm unable to reproduce this issue with Kestrel running on my Windows 10 laptop and wrk's concurrency level set as high as 1000. When testing on the SmurLab server, I don't start seeing these errors until about 256 connections which is well above the 64 connections this was originally reproduced with.

**Comment by benaadams** [comment] 2015-09-24 07:02
Are you running out of file descriptors? Try something like:

````# ulimit -n 99999````

**Comment by halter73** [comment] 2015-09-24 18:45
@benaadams `ulimit -a` reports the current open file limit is 100,000 on the linux machine running wrk. In my test, the 512 connections are eventually established concurrently. The errors occur during the initial connection ramp up, but after the initial connection failures, wrk is able to successfully establish all 512 connections within the first second of the test.

**Comment by halter73** [comment] 2015-09-28 21:52
We've verified that a simple node.js app and haywire (both use libuv) exhibit this same behavior. I'm moving this out of beta8 to give us more time to investigate.

**Comment by kcraft** [comment] 2015-11-24 18:28
I've experienced a similar issue using apache's "ab" tool for load testing.

**Comment by muratg** [comment] 2015-12-11 18:48
Anything we can do in Kestrel about this?  Or is it purely libuv problem?

**Comment by halter73** [comment] 2015-12-11 19:34
I remember seeing similar issues in our perflab when running against node.js. Maybe we should re-verify that the behavior is the same. Obviously, if it is, it points to it being a libuv problem.

**Comment by DamianEdwards** [comment] 2016-01-22 18:28
post RC2

**Comment by benaadams** [comment] 2016-05-10 14:50
I've stopped seeing this - does it still occur?

**Comment by muratg** [comment] 2016-05-10 15:05
cc @sivagms

**Comment by halter73** [comment] 2016-05-19 18:45
We've seen these errors on our internal CI servers as recently as today.

**Comment by benaadams** [comment] 2016-05-19 18:55
Yeah, I've started seeing it again - isn't a app startup thing either as is a wrk start-up thing

**Comment by muratg** [comment] 2017-04-07 19:34
Dup of https://github.com/aspnet/KestrelHttpServer/issues/1360

**Closed by muratg** 2017-04-07 19:34 UTC
Labels: bug, stress
