### ISSUE TITLE
Kestrel Not Opening Port on Ubuntu

### ISSUE THREAD

**Issue by dexterhussain** [aspnet/KestrelHttpServer#2255] opened 2018-01-12 08:33 UTC
Dear All, 
I have an application which is running fine on one machine using ubuntu 16 and I am trying to deploy the same application on the other freshly installed machine. When i run the application it shows me successful message 

exilliumwebserver@ExilliumWebServer:~/exiadmin$ dotnet Admin.dll
Hosting environment: Production
Content root path: /home/exilliumwebserver/exiadmin
Now listening on: http://localhost:5001
Application started. Press Ctrl+C to shut down.

But nor the 5001 port opens neither the web runs. I have tried checking it my using nmap. All the other machines on which I am running kestrel web server doesnt show any of such error. Please enlighten !

**Comment by dexterhussain** [comment] 2018-01-12 08:58
No UFW or any other firewall is installed. SSH is properly working on the same machine

**Comment by Drawaes** [comment] 2018-01-12 09:00
Due to the port number you will need to run as sudo. Try sudo dotnet
admin.dll

**Comment by dexterhussain** [comment] 2018-01-12 09:03
No Benefit. I already tried it 
@Drawaes 

exilliumwebserver@ExilliumWebServer:~/elforExillium$ sudo dotnet Elp.dll
[sudo] password for exilliumwebserver:
Hosting environment: Production
Content root path: /home/exilliumwebserver/elforExillium
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Last login: Fri Jan 12 14:01:15 2018 from 103.255.4.55
pgc@sqanercore:~$ nmap 192.168.7.18

Starting Nmap 7.01 ( https://nmap.org ) at 2018-01-12 14:02 PKT
Nmap scan report for 192.168.7.18
Host is up (0.00064s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

**Comment by dexterhussain** [comment] 2018-01-12 09:03
Now I have made services for both using systemctl but still they are not opening port

**Comment by dexterhussain** [comment] 2018-01-12 09:04
Jan 12 14:03:47 ExilliumWebServer exiel[4934]: Hosting environment: Production
Jan 12 14:03:47 ExilliumWebServer exiel[4934]: Content root path: /home/exilliumwebserver/elforExillium
Jan 12 14:03:47 ExilliumWebServer exiel[4934]: Now listening on: http://localhost:5000
Jan 12 14:03:47 ExilliumWebServer exiel[4934]: Application started. Press Ctrl+C to shut down.

**Comment by dexterhussain** [comment] 2018-01-12 09:55
Dotnet version 2.0
exilliumwebserver@ExilliumWebServer:~/exiadmin$ systemctl status exel.service
● exel.service - ELforexilliumrunning
   Loaded: loaded (/etc/systemd/system/exel.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-01-12 14:54:48 PKT; 5s ago
 Main PID: 2498 (dotnet)
    Tasks: 49
   Memory: 39.1M
      CPU: 514ms
   CGroup: /system.slice/exel.service
           └─2498 /usr/bin/dotnet /home/exilliumwebserver/elforExillium/Elp.dll

Jan 12 14:54:48 ExilliumWebServer exiel[2498]: warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXm
Jan 12 14:54:48 ExilliumWebServer exiel[2498]:       Using an in-memory repository. Keys will not be persisted to
Jan 12 14:54:48 ExilliumWebServer exiel[2498]: warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyMana
Jan 12 14:54:48 ExilliumWebServer exiel[2498]:       Neither user profile nor HKLM registry available. Using an e
Jan 12 14:54:48 ExilliumWebServer exiel[2498]: warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyMana
Jan 12 14:54:48 ExilliumWebServer exiel[2498]:       No XML encryptor configured. Key {76598f06-8bbf-4666-b9ee-e6
Jan 12 14:54:48 ExilliumWebServer exiel[2498]: Hosting environment: Production
Jan 12 14:54:48 ExilliumWebServer exiel[2498]: Content root path: /home/exilliumwebserver/elforExillium
Jan 12 14:54:48 ExilliumWebServer exiel[2498]: Now listening on: http://localhost:5000
Jan 12 14:54:48 ExilliumWebServer exiel[2498]: Application started. Press Ctrl+C to shut down.

**Comment by dexterhussain** [comment] 2018-01-15 09:25
this is a seriously strange issue i installed same dotnet core 2.0 on ubuntu 14 and ubuntu 16. Fresh installations . Deployed same application. It started running without any issues on 14 and opened port and on same issue on 16 port doesnt opens.

**Comment by dexterhussain** [comment] 2018-01-15 09:26
@javiercn  It looks like some bug in kestrel. @halter73 @migueldeicaza @shanselman

**Comment by muratg** [comment] 2018-02-07 00:22
@dexterhussain Could you clarify why you think this is a Kestrel bug? I wasn't able to reproduce on Ubuntu 16.04 with ASP.NET Core 2.0. If you have a simple app that reproduces this issue on Ubuntu, please let me know.  Putting this one in Discussions milestone for now.

**Comment by dexterhussain** [comment] 2018-02-07 04:54
@muratg  I fixed it. There are some routing differences between windows and ubuntu. Like App and app and in configration of timezones. Windows need +5 and Ubuntu need Asia/Karachi and many others I fixed each one of them and ran it.

**Comment by javiercn** [comment] 2018-02-07 06:07
Seems like this is fixed, so I'm closing it.

**Closed by javiercn** 2018-02-07 06:07 UTC
