### ISSUE TITLE
Virtual Memory consumption on CentOS

### ISSUE THREAD

**Issue by strohlaj** [aspnet/KestrelHttpServer#1266] opened 2016-12-20 18:46 UTC
We have a client that pointed out that our application was consuming multiple gigabytes of virtual memory. Upon further inspection the default asp.net core app using kestrel consumes just as large quantities of virtual memory as our app. This isn't necessarily a problem because it's not actually using those levels of memory, but I have been tasked with understanding why we're seeing so much being used/allocated/reserved. Here is a screenshot from TOPS: 

![dotnet_virtualmemory](https://cloud.githubusercontent.com/assets/7318452/21362360/0b192c72-c6b6-11e6-9497-e8c2ff553efd.png)

The application shown was the basic asp.net core template application. When running a 'hello world' application from dotnet we did not see the same problems. It was only when we used kestrel that we saw the virtual memory jump. 

What is causing this?

We were using CentOS version: 7.2
16 Gigabytes of physical memory.
running .net Core version 1.0.0.
no reverse proxy was being used. 

Thank you!

**Comment by cesarbs** [comment] 2016-12-20 18:57
Is this Kestrel 1.1.0? If so, it's possibly this: https://github.com/aspnet/KestrelHttpServer/issues/1260

**Comment by strohlaj** [comment] 2016-12-20 19:35
Unfortunately it was found in version 1.0. This is an exact snippet of our project.json file: 
![tmisjsonsnippet](https://cloud.githubusercontent.com/assets/7318452/21365039/72b81144-c6c1-11e6-8585-0c4ea70a4035.JPG)

Would it behoove me to try this set up with the latest version of kestrel?

**Comment by benaadams** [comment] 2016-12-20 19:45
> no reverse proxy was being used.

> Would it behoove me to try this set up with the latest version of kestrel?

Yes... though you might want fix #1260 in it; but you definitely want to be using 1.1.0 rather than 1.0.0 in this deployment.

**Comment by strohlaj** [comment] 2017-01-03 20:01
I was able to reproduce this problem using the latest version of Kestrel.

**Comment by cesarbs** [comment] 2017-01-03 23:33
By latest do you mean development packages/built from source?

**Comment by strohlaj** [comment] 2017-01-04 15:17
No, I mean the latest version available on nuget, version 1.1.0.

**Comment by cesarbs** [comment] 2017-01-10 18:12
@strohlaj Thanks, I got worried for a moment 😀 The fix will be shipped in 1.1.1.

**Comment by cesarbs** [comment] 2017-01-10 18:13
Closing as dupe of https://github.com/aspnet/KestrelHttpServer/issues/1260

**Closed by cesarbs** 2017-01-10 18:13 UTC
Labels: duplicate
