### ISSUE TITLE
Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by sandersaares** [aspnet/KestrelHttpServer#1351] opened 2017-02-09 07:28 UTC
Steps to reproduce:

1. In VS 2015, create a new Console Application project targeting .NET Framework 4.6.2
1. Add the *Microsoft.AspNetCore.Server.Kestrel* NuGet package (latest stable, v1.1.0).
1. Copy-paste the code for the Program and Startup classes shown below.

*Program class*

```c#
static void Main(string[] args)
{
	var builder = new WebHostBuilder()
        .UseStartup<Startup>()
		.UseUrls("http://*:8080;https://*:8081")
		.UseKestrel();

	var host = builder.Build();

	host.Run();
}
```

*Startup class*

```c#
public void Configure(IApplicationBuilder app)
{
}
```

Then press F5 to start the app.

**Actual behavior**

An exception will be thrown in Run().

```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)
       at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
       at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
       at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
       at ConsoleApplication6.Program.Main(String[] args) in C:\Source\ConsoleApplication6\ConsoleApplication6\Program.cs:line 21
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233052
       Message=Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
       Source=Microsoft.AspNetCore.Server.Kestrel
       TypeName=""
       StackTrace:
            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_size()
            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
            at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
       InnerException: 
```

**Expected behavior**

Web server starts successfully and is accessible.

**More details**

Contents of the bin directory (no libuv visible):

```
ConsoleApplication6.exe
ConsoleApplication6.pdb
ConsoleApplication6.exe.config
ConsoleApplication6.vshost.exe
ConsoleApplication6.vshost.exe.config
ConsoleApplication6.vshost.exe.manifest
Microsoft.AspNetCore.Hosting.dll
Microsoft.AspNetCore.Hosting.xml
Microsoft.AspNetCore.Hosting.Abstractions.dll
Microsoft.AspNetCore.Hosting.Abstractions.xml
Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
Microsoft.AspNetCore.Hosting.Server.Abstractions.xml
Microsoft.AspNetCore.Http.dll
Microsoft.AspNetCore.Http.xml
Microsoft.AspNetCore.Http.Abstractions.dll
Microsoft.AspNetCore.Http.Abstractions.xml
Microsoft.AspNetCore.Http.Extensions.dll
Microsoft.AspNetCore.Http.Extensions.xml
Microsoft.AspNetCore.Http.Features.dll
Microsoft.AspNetCore.Http.Features.xml
Microsoft.AspNetCore.Server.Kestrel.dll
Microsoft.AspNetCore.Server.Kestrel.xml
Microsoft.AspNetCore.WebUtilities.dll
Microsoft.AspNetCore.WebUtilities.xml
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.Configuration.xml
Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.Abstractions.xml
Microsoft.Extensions.Configuration.EnvironmentVariables.dll
Microsoft.Extensions.Configuration.EnvironmentVariables.xml
Microsoft.Extensions.DependencyInjection.dll
Microsoft.Extensions.DependencyInjection.xml
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.DependencyInjection.Abstractions.xml
Microsoft.Extensions.FileProviders.Abstractions.dll
Microsoft.Extensions.FileProviders.Abstractions.xml
Microsoft.Extensions.FileProviders.Physical.dll
Microsoft.Extensions.FileProviders.Physical.xml
Microsoft.Extensions.FileSystemGlobbing.dll
Microsoft.Extensions.FileSystemGlobbing.xml
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Logging.xml
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.Abstractions.xml
Microsoft.Extensions.ObjectPool.dll
Microsoft.Extensions.ObjectPool.xml
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Options.xml
Microsoft.Extensions.PlatformAbstractions.dll
Microsoft.Extensions.PlatformAbstractions.xml
Microsoft.Extensions.Primitives.dll
Microsoft.Extensions.Primitives.xml
Microsoft.Net.Http.Headers.dll
Microsoft.Net.Http.Headers.xml
Microsoft.Win32.Primitives.dll
System.AppContext.dll
System.Buffers.dll
System.Collections.Immutable.dll
System.Collections.Immutable.xml
System.Console.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.DiagnosticSource.xml
System.Diagnostics.Tracing.dll
System.Globalization.Calendars.dll
System.IO.dll
System.IO.Compression.dll
System.IO.Compression.ZipFile.dll
System.IO.FileSystem.dll
System.IO.FileSystem.Primitives.dll
System.Net.Http.dll
System.Net.Sockets.dll
System.Numerics.Vectors.dll
System.Numerics.Vectors.xml
System.Reflection.dll
System.Reflection.Metadata.dll
System.Reflection.Metadata.xml
System.Runtime.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.Unsafe.xml
System.Runtime.Extensions.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Text.Encodings.Web.dll
System.Text.Encodings.Web.xml
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Extensions.xml
System.Xml.ReaderWriter.dll
```

**Comment by cesarbs** [comment] 2017-02-09 19:43
Dupe of https://github.com/aspnet/KestrelHttpServer/issues/1292

**Closed by cesarbs** 2017-02-09 19:43 UTC
