### ISSUE TITLE
ASP.NET Core Kestrel on Linux never prompts for client certificate

### ISSUE THREAD

**Issue by jceddy** [aspnet/KestrelHttpServer#1802] opened 2017-05-01 21:31 UTC
I have an ASP.NET Core 1.1 application set up to use Https and require client certificates:

![](https://i.stack.imgur.com/Jd048.png)

I'm running the application on Linux.

If I change ClientCertificateMode to "AllowCertificates", then everything works fine, but the browser never prompts for a client cert.

With "RequireCertificate" set, I still don't get prompted by the browser for a certificate, and I get the two exceptions below (both repeated four times) on the server side and no response returned the the browser:

Microsoft.AspNetCore.Server.Kestrel:Error: ConnectionFilter.OnConnection

System.AggregateException: One or more errors occurred. (Authentication failed because the remote party has closed the transport stream.) ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream. at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.d__3.MoveNext() --- End of inner exception stack trace --- ---> (Inner Exception #0) System.IO.IOException: Authentication failed because the remote party has closed the transport stream. at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.d__3.MoveNext()<---

Microsoft.AspNetCore.Server.Kestrel:Error: ConnectionFilter.OnConnection

System.AggregateException: One or more errors occurred. (The remote certificate is invalid according to the validation procedure.) ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.d__3.MoveNext() --- End of inner exception stack trace --- ---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.d__3.MoveNext()<---

![](https://i.stack.imgur.com/vGQJr.png)

I've spent about days trying different things and Googling around, but I can't seem to figure out what the core cause of the issue is, so thought I'd check if anyone over here has an idea.

**Comment by khellang** [comment] 2017-05-01 21:50
I see you're calling `UseIISIntegration`. Does that mean you're running this behind IIS?

**Comment by jceddy** [comment] 2017-05-01 22:02
On Windows we are running behind IIS Express. On Linux, no.

**Comment by jceddy** [comment] 2017-05-02 13:01
I tried removing that line to see if it was affecting something, and now I get this error:

[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HL4HBCV1BOC0" bad request data: "Invalid request line: <0x16><0x03><0x01><0x00><0xD0><0x01><0x00><0x00><0xCC><0x03><0x03>0<0xBA><0x0B><0xCB><0x1A>1<0xFE><0x1F><0x0A>"
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Invalid request line: <0x16><0x03><0x01><0x00><0xD0><0x01><0x00><0x00><0xCC><0x03><0x03>0<0xBA><0x0B><0xCB><0x1A>1<0xFE><0x1F><0x0A>
Microsoft.AspNetCore.Server.Kestrel:Information: Connection id "0HL4HBCV1BOC0" bad request data: "Invalid request line: <0x16><0x03><0x01><0x00><0xD0><0x01><0x00><0x00><0xCC><0x03><0x03>0<0xBA><0x0B><0xCB><0x1A>1<0xFE><0x1F><0x0A>"

Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Invalid request line: <0x16><0x03><0x01><0x00><0xD0><0x01><0x00><0x00><0xCC><0x03><0x03>0<0xBA><0x0B><0xCB><0x1A>1<0xFE><0x1F><0x0A>

**Comment by muratg** [comment] 2017-06-23 19:43
@jceddy Did you figure out what the issue is? Any more details?

**Comment by jceddy** [comment] 2017-06-23 19:47
No...there doesn't seem to be a way to tell Kestrel which certificate authorities to accept (i.e. to prompt for in the browser). I'm completely running behind NGINX/IIS proxies now, which are handling the SSL interaction with the client for me and forwarding all traffic to Kestrel over HTTP.

**Comment by muratg** [comment] 2017-06-23 19:50
Assigning to @halter73 to investigate (and add a test covering this scenario.)

**Comment by Eilon** [comment] 2017-07-06 22:26
@halter73 / @muratg - what action is required here for 2.0.0?

**Comment by muratg** [comment] 2017-07-06 22:28
I think we can move this out. @halter73 thoughts?

**Comment by day01** [comment] 2017-07-07 02:01
In my opinion, this is not resolved. Kestrel in client certificate validation is not worked properly. Of course, you can move this functionality to nginx/IIS but is it the best way?

**Comment by muratg** [comment] 2017-07-07 17:09
Moving to 2.1 due to time constraints. @halter73 if you could get it in very quickly, we can bring this back.

**Comment by muratg** [comment] 2017-08-18 19:49
@stephentoub Any thoughts if this is an issue with SslStream?

**Comment by stephentoub** [comment] 2017-08-19 13:38
> Any thoughts if this is an issue with SslStream?

cc: @bartonjs, @Priya91

**Comment by Drawaes** [comment] 2017-08-19 14:44
Are we sure it is just a linux issue? The problem is most likely that there is no way currently to tell SSLStream what cert authorities to accept. It needs to know so it can send the extension to the client this prompting the cert send if there is one matching. It might just be a matter of èxposing this option on the SSLStream wrapper for Kestrel?

**Comment by Priya91** [comment] 2017-08-22 19:10
On SslStream server side, if we expect remote cert, then we use the CA lists provided by the function ```X509_get_default_cert_dir()``` for system store and local user store under ```~/dotnet/cryptography/```, and sets the list of CAs sent to the client when requesting a client certificate with ```SSL_CTX_set_client_CA_list```. If the CA you want is not getting sent, please ensure to install it in one of the mentioned locations.

**Comment by ayende** [comment] 2017-09-11 06:23
I investigate this a bit more, and I think that the main issue is here:
https://github.com/dotnet/corefx/blob/0fd3d2c5bcb1a83e7ebd8025e4810e11e231ce03/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L323

The problem is that it adds all the local and user certs by default, and on the Windows side, it doesn't add anything.

Sending an empty list on SSL client cert basically means: "gimme what you got", while a list limits that.

It seems to be that sending the list (which in our tests http://issues.hibernatingrhinos.com/issue/RavenDB-8524) includes hundreds of entries is not what you want to do.

This is called here:
https://github.com/dotnet/corefx/blob/0fd3d2c5bcb1a83e7ebd8025e4810e11e231ce03/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L97

This is a reals tumbling block for us. Our situation calls for the user to use any client cert and the server side will handle the validation. However, with this logic on Linux, the admin is now forced into a lot of running around and managing certs that we would really wish to avoid.

Allow us to specify it would be much better, yes. Even if we need to write special code for Linux / Windows for this case, but right now this seems to be handled way too deep in the stack for us to have any sort of access to it.

**Comment by Priya91** [comment] 2017-09-12 21:43
cc @bartonjs

**Comment by bartonjs** [comment] 2017-09-13 13:25
If we're not behaving the same on all platforms then that'd (probably) be a bug.  If SslStream on Windows stopped sending the CA list intentionally then Linux should be changed (and macOS evaluated).  If it's that Windows made a change in newer versions of Windows then we need to decide what we want.  (The "probably" is because if it's nuanced in Windows we may have a hard time forming an opinion on the other platforms, and macOS may or may not expose any part of this as an option)

If all the platforms support an explicit list of string/X500DistinguishedName/etc, I could certainly get behind user control.

**Comment by muratg** [comment] 2017-11-10 20:44
External: https://github.com/dotnet/corefx/issues/23938

**Comment by aspnet-hello** [comment] 2018-09-24 18:20
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2018-09-24 18:20 UTC
Labels: external
