### ISSUE TITLE
Kestrel: Deadlocked in SocketOutput?

### ISSUE THREAD

**Issue by physhi** [aspnet/KestrelHttpServer#1278] opened 2016-12-31 07:34 UTC
There seems to be a dead lock in SocketOutput (and kestrel stops accepting new connections). My server does lock up randomly. See below the two sets of threads that may be causing deadlock. I looked at the code and these two sets of stack does seem to have possibility of deadlocking.

I'd taken 2 other dumps and I saw same pair of stacks getting stuck.

Since I can't repro the deadlock, I can't really tell what's causing these threads to get in deadlock. This issue could be related to #1267, but big difference is that in my case CPU goes down to zero.

![image](https://cloud.githubusercontent.com/assets/7017345/21576504/7f77fc86-cee7-11e6-8020-6548f784bd26.png)

**Comment by davidfowl** [comment] 2016-12-31 10:26
@physhi do you pass a cancellation token to any WriteAsync calls? What does your application look like?

**Comment by davidfowl** [comment] 2016-12-31 11:01
Yep there's a deadlock...

**Comment by physhi** [comment] 2016-12-31 17:04
I'm using 1.1.0 version of dotnet core running on windows. My application is really a file store with a lot of big files, and I have bandwidth throttling and content range and bunch of content transformations implemented in code. What I do is I try to pass cancellation token as far as possible so that I can terminate request if user has disconnected from the server.

Currently, because of this deadlock issue, I've to implement a watchdog process with very aggressive ping times and recycling kestrel as soon as the server stops processing a request.

**Comment by davidfowl** [comment] 2016-12-31 18:28
The only way to avoid it would be to stop passing a cancellation token. It's something we need to fix for 1.1.1.

The problem is that we're disposing the cancellation registration in the write callback under the context lock https://github.com/aspnet/KestrelHttpServer/blob/b46e48fe0188273f462809da8db96748efedfa81/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/SocketOutput.cs#L429 on the IO thread and this waits on any pending cancellation callbacks to execute. Turns out we have a cancellation callback waiting on the same lock https://github.com/aspnet/KestrelHttpServer/blob/b46e48fe0188273f462809da8db96748efedfa81/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/SocketOutput.cs#L299.

/cc @muratg @halter73 @cesarbs

**Comment by davidfowl** [comment] 2016-12-31 18:47
@physhi Are you manually calling `context.Abort()` anywhere?

**Comment by muratg** [comment] 2017-01-03 18:14
Putting this in 1.1.1 so that it's triaged with the rest of 1.1.1 items.

**Comment by davidfowl** [comment] 2017-01-04 05:59
@physhi have you tried not passing in the token?

**Comment by physhi** [comment] 2017-01-05 04:56
@davidfowl I'd tried not passing the token but still the problem persists.

**Comment by physhi** [comment] 2017-01-05 14:55
It's difficult to take snapshot, as I see hangs in production service and it get's recycled as soon as hang is detected. I just know that the service was restarted and that's it.

**Comment by davidfowl** [comment] 2017-01-05 19:04
The problem is that we're fixing the issue but if no cancellation token is passed into WriteAsync, this won't happen. It's possible there's another hang and what you're experiencing won't be fixed by this fix https://github.com/aspnet/KestrelHttpServer/pull/1281

**Comment by physhi** [comment] 2017-01-06 03:33
@davidfowl, Let me deploy the proposed fix and see if it fixes the issue. I'll know if there are not hangs in next 24 hours.

**Closed** 2017-01-07 04:47 UTC
Labels: 2 - Working, bug

**Comment by runxc1** [comment] 2017-01-13 00:15
So I am trying to see if this is related to what I have seen a couple times over the last couple weeks.   I have a fairly simple app that is running as an Azure App Service on a single Large Instance.   It has sometimes gone more than a week without any Issues serving about 1.5 million pages a day and then will stop processing requests.  If I restart the App it will start without any Issues and usually hums along after that.  Looking in the log I see the following error just before it stops processing anything.

2017-01-12 21:47:28.036 +00:00 [Warning] Unable to bind to http://localhost:17739 on the IPv6 loopback interface.
System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()<---

**Comment by davidfowl** [comment] 2017-01-13 00:16
That error is harmless, hard to know if it's the same issue without any more information. A process dump when the application hangs would confirm.
