### ISSUE TITLE
Access-Control-Allow headers not set when exception is thrown.

### ISSUE THREAD

**Issue by Zexuz** [aspnet/KestrelHttpServer#2172] opened 2017-11-17 22:16 UTC
**Problem**: I have enabled Cors and the developExceptionPage like this in the Startup.cs, but when I encounter a unhandeled exception I don't get a DeveloperExceptionPage beacuse the Cors header is not set.

**Expected behavior** : Cors headers to bet set on Unhandled exception.
**Actual behavior**: No cors header is set when request is aborted due to a Unhandled exception.

I don't know if this is a bug or not but I don't find this behavior to be logic.

```csharp
 app.UseDeveloperExceptionPage();
 app.UseCors(builder =>
                {
                    builder.AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowAnyOrigin()
                        .AllowCredentials()
                        .Build();
                });
```
And when a unhandled exception happened.  The Cors headers is not set.
Example 
```csharp
[Route("crash")]
        [HttpGet]
        public async Task Crash()
        {
            throw new Exception("Try and catch me!");
        }
```

For those who have the same problem here is my solution
I solved this by built my own Cors middleware.
```csharp
 app.Use((context, func) =>
                {
                    context.Response.OnStarting(state => {
                        var httpContext = (HttpContext) state;
                        httpContext.Response.Headers.Add("Access-Control-Allow-Origin", new [] {"*" });
                        httpContext.Response.Headers.Add("Access-Control-Allow-Methods", new [] {"*" });
                        httpContext.Response.Headers.Add("Access-Control-Allow-Headers", new [] {"*"});
                        return Task.FromResult(0);
                    }, context);
                    return func();
                });
```

**Comment by Tratcher** [comment] 2017-11-17 22:18
Duplicate of https://github.com/aspnet/Diagnostics/issues/247

**Closed by Tratcher** 2017-11-17 22:18 UTC
