### ISSUE TITLE
Connection disconnected shouldn't be `Fail`

### ISSUE THREAD

**Issue by lodejard** [aspnet/KestrelHttpServer#400] opened 2015-11-18 02:06 UTC
It appears that's a normal way some browsers remove http connections from their connection pool.

Note `fail:` below
```
dbug: Microsoft.AspNet.Server.Kestrel[6]
      Connection id "1" received FIN.
dbug: Microsoft.AspNet.Server.Kestrel[7]
      Connection id "1" sending FIN.
fail: Microsoft.AspNet.Server.Kestrel[10]
      Connection id "1" disconnected.
dbug: Microsoft.AspNet.Server.Kestrel[8]
      Connection id "1" sent FIN with status "0".
dbug: Microsoft.AspNet.Server.Kestrel[2]
      Connection id "1" stopped.
```

**Comment by Tratcher** [comment] 2015-11-18 17:46
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/392

**Closed by Tratcher** 2015-11-18 17:46 UTC
Labels: duplicate
