### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by patriksvensson** [aspnet/KestrelHttpServer#1737] opened 2017-04-21 20:34 UTC
I've started to see `ObjectDisposedException` in my logs lately for an application running on Azure.
I'm referencing version `1.1.1` of the `Microsoft.AspNetCore.Server.Kestrel` package.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FrameResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.ValidateState(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Microsoft.Extensions.RazorViews.BaseView.WriteLiteral(String value)
   at Microsoft.AspNetCore.Hosting.Views.ErrorPage.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.RazorViews.BaseView.<ExecuteAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

The controller giving this exception is an empty method returning OK (200).

```csharp
public sealed class PingApiController : Controller
{
    [HttpGet]
    [Route("ping")]
    public IActionResult Ping()
    {
        return Ok();
    }
}
```

**Comment by benaadams** [comment] 2017-04-21 20:47
Looks like the error page `Microsoft.AspNetCore.Hosting.Views.ErrorPage` is doing the write

**Comment by patriksvensson** [comment] 2017-04-21 20:52
@benaadams Ah, did I post this issue in the wrong place?

**Comment by benaadams** [comment] 2017-04-21 20:53
Don't know; was just observing 😄

**Comment by halter73** [comment] 2017-04-21 23:50
It will probably be helpful to figure out what's triggering the error page to begin with. This ObjectDisposedException usually means that something was attempting to write the response stream after the response was completed. This would mean controller action and all other middleware already finished executing.

**Comment by Tratcher** [comment] 2017-04-22 01:57
The hosting error page only captures and shows startup errors.

**Comment by muratg** [comment] 2017-04-24 19:36
@Tratcher could you investigate (preview2)

**Comment by patriksvensson** [comment] 2017-04-25 00:39
Some more information: This seem to occur only when the site is starting up. I'm calling the ping endpoint from a webjob to see when I can start using the API, and this only happen just after deployment of the site.

**Comment by davidfowl** [comment] 2017-04-25 02:14
@muratg this might be something we should fix in a patch

**Comment by sirajmansour** [comment] 2017-05-10 08:09
```
 app.Run(async (context) =>
            {
                if (context.Request.Method == HttpMethod.Post.Method)
                {
                    try
                    {
                        using (var reader = new StreamReader(context.Request.Body))
                        {
                            string request = (await reader.ReadToEndAsync()).Trim();
                            if (request.StartsWith("ping ", StringComparison.OrdinalIgnoreCase))
                            {

                                var targetServices = request.Substring(5).Trim().Split(new char[] { ',', ';' });
                                if (targetServices.Length > 0)
                                {
                                    using (var client = new HttpClient())
                                    {
                                        Func<string, Task<string>> pingSend = async (service) =>
                                        {
                                            try
                                            {
                                                string pong = await client.GetStringAsync(service);
                                                return $"Service [{service}] : \"{pong}\"";
                                            }
                                            catch (Exception ex)
                                            {

                                                logger.LogError(007, ex, $"Ping service [{service}] failed.");
                                                return $"Ping service [{service}] failed.";
                                            }
                                        };

                                        TransformBlock<string, Task<string>> tBlock = new TransformBlock<string, Task<string>>(pingSend, new ExecutionDataflowBlockOptions { BoundedCapacity = targetServices.Length, MaxDegreeOfParallelism = Environment.ProcessorCount });

                                        ActionBlock<Task<string>> aBlock = new ActionBlock<Task<string>>(async pingTask =>
                                        {
                                            var result = await pingTask;
                                            try
                                            {
                                                await context.Response.WriteAsync(result); // THIS WILL THROW ObjectDisposedException
                                            }
                                            catch (Exception ex)
                                            {
                                                ex.ToString();  //breakpoint 
                                            }
                                        });

                                        tBlock.LinkTo(aBlock, new DataflowLinkOptions { PropagateCompletion = true });

                                        foreach (var service in targetServices)
                                        {
                                            tBlock.Post(service);
                                        }

                                        tBlock.Complete();
                                        await tBlock.Completion;
                                        return;
                                    }
                                }                                    
                            }

                            throw new ArgumentException("Expected -> ping service1,service2");
                        }
                    }
                    catch (Exception ex)
                    {
                        context.Response.StatusCode = StatusCodes.Status400BadRequest;
                        await context.Response.WriteAsync(Newtonsoft.Json.JsonConvert.SerializeObject(ex));
                        return;
                    }
                }

                await context.Response.WriteAsync("Pong");
            });
```

**Comment by davidfowl** [comment] 2017-05-10 08:23
@patriksvensson This code reproduces the exception 100% of the time? Can you provide a minimal project with it working?

**Comment by patriksvensson** [comment] 2017-05-10 08:29
@davidfowl The code I posted with the issue or the code posted above your comment?

**Comment by davidfowl** [comment] 2017-05-10 08:31
My bad I mean to mention @sirajmansour. @patriksvensson  your issue I assume it doesn't repro 100% of the time right?

**Comment by patriksvensson** [comment] 2017-05-10 10:37
@davidfowl Not 100% of the time according to my logs and I haven't seen it for a while now.

**Comment by Tratcher** [comment] 2017-05-10 20:42
That exception is not coming from PingApiController. It's coming from Microsoft.AspNetCore.Hosting.Views.ErrorPage here: 
https://github.com/aspnet/Hosting/blob/rel/1.1.2/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L157
https://github.com/aspnet/Hosting/blob/rel/1.1.2/src/Microsoft.AspNetCore.Hosting/Startup/ExceptionPage/Views/ErrorPage.cshtml

This is only invoked if your app threw an exception on startup before the first request was processed. The ObjectDisposedException is reasonable if the app was trying to shut down while this error page was being written.

What you need to investigate is why did the app crash on startup. This exception is written to the console so you should be able to capture it by enabling the stdout logs for AspNetCoreModule in web.config. Pending that, there's nothing else here to investigate and we should close this issue.

**Closed** 2017-05-10 20:43 UTC
Labels: 1 - Ready, bug

**Comment by sirajmansour** [comment] 2017-05-10 23:53
@davidfowl yes this code reproduces the issue all the time.

**Comment by davidfowl** [comment] 2017-05-10 23:57
@sirajmansour it's possible you're writing to the response after the request is complete. Can you provide a running sample?

**Comment by sirajmansour** [comment] 2017-05-11 00:17
@davidfowl This is exactly what's happening, i should never trust my judgement after 5pm. I am calling `await` only on `tBlock.Completion` but i should also `await aBlock.Completion` otherwise the middleware delagate will return before the delegate of `aBlock` executed.

**Comment by davidfowl** [comment] 2017-05-11 00:31
@sirajmansour Great, put a minimal sample in a github repo so we can reproduce it
