### ISSUE TITLE
Go back to allowing a maximum of 3 concurrent uv_write operations per connection

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#691] opened 2016-03-11 06:19 UTC
In Kestrel 1.0.0-rc1 there was a [maximum of 3 ongoing uv_write operations](https://github.com/aspnet/KestrelHttpServer/blob/1.0.0-rc1/src/Microsoft.AspNet.Server.Kestrel/Http/SocketOutput.cs#L16). Now there are an unbounded number of concurrent write operations because the new `_writePending` bool is set to false before `uv_write` is even called instead of in the `OnWriteCompleted` callback [like we used to](https://github.com/aspnet/KestrelHttpServer/blob/1.0.0-rc1/src/Microsoft.AspNet.Server.Kestrel/Http/SocketOutput.cs#L186).

I'm worried that the unbounded concurrent calls to `uv_write` could create some pathological perf characteristics when the server application makes a bunch of small writes which don't exceed the write behind buffer while the client consumes the response slowly.

I think we can fix this issue by simply reverting https://github.com/aspnet/KestrelHttpServer/commit/480996433e5f21bd37d7c51ae2e68af52c44cc2e, but I would like a reminder as to why we made this change in the first place. @benaadams?

**Comment by benaadams** [comment] 2016-03-11 15:24
write's data gets appended to a memorypool block chain; thus an unlimited amount of writes coalesce to a single uv_write as it takes everything at the point its ready to write (Produce/Comsume); then the next uv_write takes everything available again.

Previously multiple outstanding writes were `ArrayBuffers` of `ArrayBuffers` and it had to maintain an record of what the data was in flight for that write as it had multiple stages to it and there could be multiple writes in progress at any time.

Currently it takes everything at the point of the write; then everything for the next write etc, and there is only one uv_write in progress at any time.

**Comment by benaadams** [comment] 2016-03-11 15:34
Hmm... a better summary might be previously it was a limit on how many _requests_ to write would be outstanding to libuv; whereas now its just a hasdata flag and there is only one outstanding request to write outstanding to libuv which takes all the data in the handover to libuv and marks it as no longer having data oustanding to write.

**Comment by halter73** [comment] 2016-03-11 17:19
@benaadams Exactly. The risk is that a lot of uv_write calls are made quickly with small buffers each time.

Theoretically, an app could make a bunch of calls to write with small buffers (so the total wouldn't exceed 64KB and causing weird to get throttled) slowly enough that the buffers don't get accumulated before the actual call to uv_write. Meanwhile the client could read the response even more slowly. This way you could theoretically get hundreds of ongoing uv_write calls.

**Comment by benaadams** [comment] 2016-03-11 17:21
You should only have one call to uv_write in the current set-up; it only makes a call if one isn't queued.

**Comment by benaadams** [comment] 2016-03-11 17:23
In the previous set up it would have multiple calls as it took the data snapshot at the time of the queue; now its the uv_write that takes the snapshot

**Comment by halter73** [comment] 2016-03-11 17:44
With the current setup, it no longer accounts for the time the async write actually takes to complete. Before when more write data was added via WriteAsync, ScheduleWrite wouldn't be called if there were already three outstanding write callbacks. Instead, the old code would wait for the next write callback to be triggered and only *then* call ScheduleWrite if there is more data available to be written.

This is the behavior we want, since this allows us to make fewer calls to uv_write with larger buffers given we can post operations to KestrelThread quicker than uv_write can complete asynchronously (which seems likely).

**Comment by halter73** [comment] 2016-03-11 17:49
We can probably combine the bool we have currently and the _writesPending count to avoid unnecessary calls to Post before a snapshot is even taken if that's a concern.

**Comment by benaadams** [comment] 2016-03-11 17:51
Hmm... let me get back to you; just checking code

**Comment by benaadams** [comment] 2016-03-11 18:02
To be specific, you mean this interaction is bad?

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Http/SocketOutput.cs#L188-L198
```csharp
	if (!_writePending)
	{
		_writePending = true;
		scheduleWrite = true;
	}
}

if (scheduleWrite)
{
	ScheduleWrite();
}
```
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Http/SocketOutput.cs#L321-L347
```csharp
// This is called on the libuv event loop
private void WriteAllPending()
{
	WriteContext writingContext = null;

	if (Monitor.TryEnter(_contextLock))
	{
		_writePending = false;

		if (_nextWriteContext != null)
		{
			writingContext = _nextWriteContext;
			_nextWriteContext = null;
		}

		Monitor.Exit(_contextLock);
	}
	else
	{
		ScheduleWrite();
	}

	if (writingContext != null)
	{
		writingContext.DoWriteIfNeeded();
	}
}
```

**Comment by benaadams** [comment] 2016-03-11 18:12
i.e. you are saying the next write should happen after the `OnWriteCompleted` rather than after `_uv.write` is called and the data ownership transferred to the kernel?

**Comment by halter73** [comment] 2016-03-11 18:18
Yep. We shouldn't allow too many concurrent write operations. I consider the write to be ongoing until the write callback is called. I don't think we need to limit it to one ongoing write at a time since that might hurt perf, but three sounds reasonable (though it's best to measure).

**Comment by benaadams** [comment] 2016-03-11 18:19
Sounds reasonable (with measure)

**Comment by benaadams** [comment] 2016-03-11 18:32
However, the completion routine is triggered after full round trip? (e.g. message delivery confirmed) So over slow links this would mean no extra data is put on the wire until delivery is confirmed?

So you may want to test with a slow round trip at TCP level (e.g. between East US and East Asia data centres)

**Comment by cesarbs** [comment] 2016-03-12 08:40
What if we did writes based on two factors: buffer size and time. Accumulate writes until a certain size is reached, then actually write; at the same time, set up a timer at a given interval that writes whatever is pending, which would prevent delaying responses if the app is not writing fast enough.

**Comment by benaadams** [comment] 2016-03-12 14:59
@cesarbs sounds like Nagle and Delayed Acks :bowtie: Also my websockets would hate you :worried:

I think I was wrong and the completion routine gets called after the data has been copied into the O/S buffer - so its more "this data is now unlocked", rather than delivery. 

Thinking aloud... assuming every callback was instant and there were no delays in the system.

A slow client would cause the O/S buffer not to get drained; so that would  eventually block and stop calling the callbacks; at which point the write behind buffer would start to fill when it became full the call to write would block. Say the O/S buffer is 64k and the write behind buffer is 64k at 128k "true" outstanding it would block.

In the previous scenario the queuing of writes was done prior to the call to `socket.send`; i.e. the queue lived in `KestrelThread` so could build up regardless of the state of the socket and its buffers and where the number of writes yet to be called on `libuv` - though it still had the outstanding data constraint - so `_writesPending` represented the number of writes `libuv` and the socket were yet to know about and so a degree the number of writes waiting on `KestrelThread`; though it was a bit of both (since it was decremented by `libuv` they could also be actual outstanding socket writes also).

In the current scenario, to add another write to `KestrelThread`, `libuv` has to have actioned the previous write - so sent it to the socket. There were extra issues previously; but is simpler now.

I don't think a fast or slow client has any overall effect on this; as its purely about O/S buffer filling (which obv client speed does effect fill level; but not write granularity). However... the gothca is `libuv`.

So libuv is a single threaded multi-phase eventing system, something like: 
1. runs requests in it queue (e.g. `KestrelThread.OnPost`)
2. calculate delay
3. check completion (timeout on delay `2`)
4. call callbacks
5. goto 1

So the worry is if someone wrote a terribad server that wrote and awaited a byte at a time?

**(A).**  Currently, if `libuv` was at step 1; and they wrote their bytes fast enough, `libuv` would stay at `step 1` until they had written 64k bytes? (with potentially 64k `uv_sends`)

**(B).** Putting the counter in would mean it would be limited to 3 bytes written per loop at step 1; with a max of 3 sends; until the loop completed and got back to step 1.

I don't think client speed particularly matters; as its a buffer unlock callback rather than a TCP ack callback.

(A) would mean a potentially huge number of outstanding callbacks; but the O/S would coalesce the data to reduce the packets sent. _However_, the highly granular writes would effect all other requests performance.

(B) would still have the same number of callbacks, but spread over a much longer time and less outstanding at any point - which would definitely be pathological to performance and the O/S wouldn't be able to coalesce the data.  _However_, the poor performance would be limited to that particular request's implementation and not effect all other requests.

Hmm... 

K, my take is (B) is better; even though its worse; because it focuses it being really bad on the code that is bad; but I do still have concerns as I can see situations where you might do small writes `IObservable` on a websocket or something.

How about adding the counter back; but increasing it to the const `_maxPooledWriteContexts`; then everything is in sync? e.g. the max pool is that same as the max outstanding which is works nicely. Then some bursty small writes are ok; but large numbers are bad. 

*Also* it shouldn't be write that increments the count; it should be `DoWriteIfNeeded` that increments it as that is the actual outstanding writes.

Sorry for the ramble... probably arguing more with myself than you :smile:

**Comment by muratg** [comment] 2016-04-05 19:43
Putting this in 1.0.0 to continue discussion post RC1.

**Comment by muratg** [comment] 2016-05-18 19:01
@halter73 claims that this is "super easy".

**Closed** 2016-06-03 00:09 UTC
Labels: 3 - Done, task
