### ISSUE TITLE
AddressRegistrationTests failures on OSX

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1734] opened 2017-04-21 08:06 UTC
[RegisterAddresses_IPv6ScopeId_Success(addressInput: "http://[fe80::1%1]:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null })] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException : Error -49 EADDRNOTAVAIL address not available
 
[RegisterAddresses_IPv6ScopeId_Success(addressInput: "http://[fe80::14b8:20f9:2ac2:d22b%4]:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null })] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException : Error -49 EADDRNOTAVAIL address not available
 
[RegisterAddresses_IPv4_Success(addressInput: "http://aspnetci-mac.guest.corp.microsoft.com:0/", testUrls: Func`2 { Method = System.String[] GetTestUrls(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = null })] System.Net.Sockets.SocketException : Network is unreachable

**Comment by natemcmaster** [comment] 2017-04-21 16:32
Dupe of #1729 ?

**Comment by davidfowl** [comment] 2017-04-21 16:57
The last error is.

**Comment by muratg** [comment] 2017-04-24 19:31
Dup of https://github.com/aspnet/KestrelHttpServer/issues/1733

**Comment by halter73** [comment] 2017-04-27 23:35
@davidfowl Have you seen this kind of failure since #1754 was merged?

I created that PR to fix the EINVALs and EADDRNOTAVAILs, but it is really odd to me that binding to "http://<some local address>:0/" would fail with EADDRNOTAVAIL considering there must be *some* port available.

**Comment by davidfowl** [comment] 2017-04-28 04:17
Seems to work now, you can close.

**Comment by davidfowl** [comment] 2017-04-28 04:17
Seems to pass now, you can close.

**Closed** 2017-04-28 04:18 UTC
Labels: 1 - Ready, task
