### ISSUE TITLE
E2ETests.SmokeTests_X64.SmokeTests_X64_Kestrel_CoreClr_Standalone fails in MusicStore

### ISSUE THREAD

**Issue by jkotalik** [aspnet/KestrelHttpServer#2116] opened 2017-10-13 22:22 UTC
Possibly related to the socket changes. @halter73 
See: https://ci.appveyor.com/project/aspnetci/musicstore/build/1.0.1182
Exception:
```
dotnet.exe : [xUnit.net 00:08:53.6420886]     E2ETests.SmokeTests_X64.SmokeTests_X64_Kestrel_CoreClr_Standalone [FAIL]
At C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15527\scripts\common.psm1:7 char:5
+     & $cmd @args
+     ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([xUnit.net 00:0...andalone [FAIL]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[xUnit.net 00:08:53.6424855]       System.Net.Http.HttpRequestException : An error occurred while sending the request.
[xUnit.net 00:08:53.6425527]       ---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
[xUnit.net 00:08:53.6434887]       Stack Trace:
[xUnit.net 00:08:53.6450987]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6451831]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6452483]            at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.<SendAsync>d__2.MoveNext()
[xUnit.net 00:08:53.6452998]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6453551]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6454098]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6454661]            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
[xUnit.net 00:08:53.6455184]            at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
[xUnit.net 00:08:53.6455689]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6456221]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6456926]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6457604]         C:\projects\musicstore\test\MusicStore.E2ETests\Implementation\Validator.cs(58,0): at E2ETests.Validator.<DoPostAsync>d__15.MoveNext()
[xUnit.net 00:08:53.6458643]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6459181]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6459793]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6460399]         C:\projects\musicstore\test\MusicStore.E2ETests\Implementation\Validator.cs(350,0): at E2ETests.Validator.<SignInWithUser>d__29.MoveNext()
[xUnit.net 00:08:53.6461375]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6461943]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6462483]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6463075]         C:\projects\musicstore\test\MusicStore.E2ETests\SmokeTestRunner.cs(106,0): at E2ETests.SmokeTestRunner.<RunTestsAsync>d__2.MoveNext()
[xUnit.net 00:08:53.6464495]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6465231]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6465830]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6466481]         C:\projects\musicstore\test\MusicStore.E2ETests\SmokeTestRunner.cs(59,0): at E2ETests.SmokeTestRunner.<SmokeTestSuite>d__1.MoveNext()
[xUnit.net 00:08:53.6467475]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6468059]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6468557]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6469078]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6469703]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6470249]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6470729]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:53.6471247]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6471798]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:53.6472202]         ----- Inner Stack Trace -----
[xUnit.net 00:08:53.6472725]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:53.6473222]            at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
[xUnit.net 00:08:53.6473769]            at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by halter73** [comment] 2017-10-17 22:08
I believe this is caused by https://github.com/dotnet/corefxlab/issues/1855

More output from https://ci.appveyor.com/project/aspnetci/musicstore/build/1.0.1182 (notice the InvalidOperationException):

```
[xUnit.net 00:08:54.6561946]         | SmokeTestSuite Information: Signing in with user '83236c1a3cf14ade97638065083c69ea@test.com'
[xUnit.net 00:08:54.6562313]         | SmokeTestSuite Information: POST Account/Login
[xUnit.net 00:08:54.6562705]         | System.Net.Http.HttpClient Debug: Sending POST http://localhost:2122/Account/Login
[xUnit.net 00:08:54.6563098]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout: warn: Microsoft.AspNetCore.Server.Kestrel[0]
[xUnit.net 00:08:54.6564017]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:       Connection processing ended abnormally.
[xUnit.net 00:08:54.6564858]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout: System.InvalidOperationException: Cursor is out of bounds
[xUnit.net 00:08:54.6565688]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at System.IO.Pipelines.ReadCursor.ThrowOutOfBoundsException()
[xUnit.net 00:08:54.6566515]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at System.IO.Pipelines.ReadableBuffer.Slice(ReadCursor start, ReadCursor end)
[xUnit.net 00:08:54.6567405]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
[xUnit.net 00:08:54.6568499]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.<ParseRequestAsync>d__37.MoveNext()
[xUnit.net 00:08:54.6569492]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout: --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:08:54.6570388]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:54.6571215]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:54.6572120]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__186.MoveNext()
[xUnit.net 00:08:54.6573065]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
[xUnit.net 00:08:54.6573928]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout:       Connection id "0HL8IG5T1DO3B" communication error.
[xUnit.net 00:08:54.6574763]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\Users\appveyor\AppData\Local\Temp\1\677ae741-e833-478c-a7c0-c5b49cb34648\MusicStore stdout: Microsoft.AspNetCore.Protocols.ConnectionAbortedException: The connection was aborted
[xUnit.net 00:08:54.6575642]         | System.Net.Http.HttpClient Error: Exception while sending 'POST http://localhost:2122/Account/Login'
[xUnit.net 00:08:54.6576018]         |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:54.6576414]         |    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
[xUnit.net 00:08:54.6576762]         |    at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
[xUnit.net 00:08:54.6577146]         |    --- End of inner exception stack trace ---
[xUnit.net 00:08:54.6577488]         |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:08:54.6577849]         |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:08:54.6578197]         |    at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.<SendAsync>d__2.MoveNext()
[xUnit.net 00:08:54.6578556]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Attempting to cancel process 4156
[xUnit.net 00:08:54.6578942]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: host process ID 4156 shut down
[xUnit.net 00:08:54.6579343]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Host process shutting down.
[xUnit.net 00:08:54.6579803]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Successfully terminated host process with process Id '4156'
[xUnit.net 00:08:54.6580490]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Failed to delete directory : Access to the path 'clrjit.dll' is denied.
[xUnit.net 00:08:54.6581201]         | SmokeTestSuite Information: Trying to drop database 'MusicStore_Test_72427a6f0f2143c1bd2754cef97e180a'
[xUnit.net 00:08:54.6581610]         | SmokeTestSuite Information: Successfully dropped database MusicStore_Test_72427a6f0f2143c1bd2754cef97e180a
[xUnit.net 00:08:54.6581957]         | Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '23.5694858' seconds
[xUnit.net 00:08:54.6582682]         | TestLifetime Information: Finished test SmokeTestSuite_Kestrel_Standalone in 23.570014s
Failed   E2ETests.SmokeTests_X64.SmokeTests_X64_Kestrel_CoreClr_Standalone
Error Message:
 System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The server returned an invalid or unrecognized response
Stack Trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.Validator.<DoPostAsync>d__15.MoveNext() in C:\projects\musicstore\test\MusicStore.E2ETests\Implementation\Validator.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.Validator.<SignInWithUser>d__29.MoveNext() in C:\projects\musicstore\test\MusicStore.E2ETests\Implementation\Validator.cs:line 350
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestRunner.<RunTestsAsync>d__2.MoveNext() in C:\projects\musicstore\test\MusicStore.E2ETests\SmokeTestRunner.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestRunner.<SmokeTestSuite>d__1.MoveNext() in C:\projects\musicstore\test\MusicStore.E2ETests\SmokeTestRunner.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

**Comment by ryanbrandenburg** [comment] 2017-10-23 23:33
We get similar failures on Win2012-E2ETests fairly frequently.

**Comment by ryanbrandenburg** [comment] 2017-10-24 18:27
To expound upon "fairly frequently", at least one of these tests fails a build of Win7-Universe and Win2012-E2ETests > 50% of the time. Can we raise the importance of this with the CoreFX team accordingly?

**Comment by muratg** [comment] 2017-10-24 23:55
@pakrym could you take a look at the CoreFX issue that Stephen filed?

**Comment by halter73** [comment] 2017-10-25 18:21
@muratg The PR to fix the issue was merged last week. We're waiting to consume the fix now.

**Comment by bradmarder** [comment] 2017-11-17 14:09
Is there any ETA when this will be fixed?

**Comment by halter73** [comment] 2017-11-17 22:57
This was fixed in [our dev myget feed](https://dotnet.myget.org/gallery/aspnetcore-ci-dev/) starting with Kestrel version 2.1.0-preview1-27589.

**Closed** 2017-11-17 22:58 UTC
Labels: 3 - Done
