### ISSUE TITLE
.net core 2.0 project 107 ENOTCONN socket is not connected at 

### ISSUE THREAD

**Issue by shaddockblack** [aspnet/KestrelHttpServer#2045] opened 2017-09-04 03:33 UTC
I am deployoing .net core 2.0 project on Linux UbuntuI have used Supervisor And Nginx, however I get the following output 

exception.Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode) at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_getpeername(UvTcpHandle handle, SockAddr& addr, Int32& namelen) at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.GetPeerIPEndPoint() at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection..ctor(ListenerContext context, UvStreamHandle socket) at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.DispatchConnection(UvStreamHandle socket) at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)

**Comment by muratg** [comment] 2017-11-10 21:13
@shaddockblack Could you share more details, or ideally an app that reproduces your issue?

**Comment by muratg** [comment] 2017-11-27 22:37
Not enough details, so closing this one.

**Closed by muratg** 2017-11-27 22:37 UTC

**Comment by kexxxfeng** [comment] 2017-12-07 09:07
I have got a lot of same exception, but I didn't knew where the exception happened.
```C#
2017-12-07 16:34:42.758 +08:00 [Error] Listener.OnConnection
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.GetPeerIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection..ctor(ListenerContext context, UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.DispatchConnection(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)
```

**Comment by muratg** [comment] 2017-12-07 18:07
@kexxxfeng Are you able to share a small repro app on GitHub?

**Comment by halter73** [comment] 2017-12-07 19:55
@kexxxfeng What OS is the app running on? Did you notice any failed requests or any other issue other than the error log?

My theory is that this is caused by a client disconnecting almost immediately after connecting.

**Comment by kexxxfeng** [comment] 2017-12-08 02:24
Recently, I upgraded `Microsoft.AspNetCore.All` to 2.0.3，then the exception was logged on running.
```
 Error:
   An assembly specified in the application dependencies manifest (Cnblogs.UCenter.WebAPI.deps.json) was not found:
     package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.1'
     path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'
   This assembly was expected to be in the local runtime store as the application was published usingthe following target manifest files:
     aspnetcore-store-2.0.3.xml
 Error:
   An assembly specified in the application dependencies manifest (Cnblogs.UCenter.WebAPI.deps.json) was not found:
     package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.1'
     path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'
   This assembly was expected to be in the local runtime store as the application was published usingthe following target manifest files:
     aspnetcore-store-2.0.3.xml
```
Then, I found an issue about that on [github](https://github.com/dotnet/cli/issues/6516#issuecomment-303181477).

According the comment, I disable `PublishWithAspNetCoreTargetManifest`.
```
<PropertyGroup>
  <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest> 
</PropertyGroup>
```

The app ran successfully. But after a few days, I found the error reported before in the log.txt. 
Now, I have already downgrade `Microsoft.AspNetCore.All` to 2.0.0. the error was not appeared any more.

The error was threw occasionally, in my opinion,  it must be about `Microsoft.AspNetCore.All 2.0.3`.

I've tried to new a demo to reproduce the exception, however, it didn't appear again.
