### ISSUE TITLE
 non-ASCII request header cause BadHttpRequestException

### ISSUE THREAD

**Issue by charliefr** [aspnet/KestrelHttpServer#2803] opened 2018-08-10 09:43 UTC
Kestrel server when request header include non-ASCII code will cause BadHttpRequestException,
(400 bad request)
for example
`curl -I 'https://localhost:5001/'  -H 'User-Agent: ）' `
or
`curl -I 'https://localhost:5001/'  -H 'X-Test: ）' `
or
`curl -I 'https://localhost:5001/'  -H 'x-test:にっぽんご' `
or
`curl -I 'http://localhost:33902/'  -H 'x-test: β'`

Exception output:

>  Microsoft.AspNetCore.Server.Kestrel:Information: Connection id "0HLFUJPBHUNP7" bad request data: "Malformed request: invalid headers."
> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

 AIT

`{"name":"Microsoft.ApplicationInsights.Dev.Exception","time":"2018-08-10T08:51:47.3906167Z","tags":{"ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.application.ver":"1.0.0.0"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"properties":{"{OriginalFormat}":"Connection id \"{ConnectionId}\" bad request data: \"{message}\"","ConnectionId":"0HLFUJPBHUNP7","Exception":"Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()","DeveloperMode":"true","CategoryName":"Microsoft.AspNetCore.Server.Kestrel","AspNetCoreEnvironment":"Development","message":"Malformed request: invalid headers."},"exceptions":[{"id":44264457,"typeName":"Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException","message":"Connection id \"0HLFUJPBHUNP7\" bad request data: \"Malformed request: invalid headers.\"","hasFullStack":true,"parsedStack":[{"level":0,"method":"Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1+<ProcessRequestsAsync>d__2.MoveNext","assembly":"Microsoft.AspNetCore.Server.Kestrel.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"}]}],"severityLevel":"Information"}}}`

Environment
- OS Windows 10.0.17134 x64
- dotnet host 2.1.2 ,commit 811c3ce6c0 , version 2.1.300
- Visual Studio 15.7.6
- Microsoft.AspNetCore.Server.Kestrel.Core, Version=2.0.2.0
- Microsoft.AspNetCore.Razor.Runtime Version=2.0.2
- Microsoft.VisualStudio.Web.CodeGeneration.Design Version=2.0.3
- System.Text.Encoding.CodePages Version=4.4.0

but makes me feel strange is emoji dose't,
`curl -I 'http://localhost:33902/'  -H 'x-test:☺'`
response status 200

1. How can I using any like middle ware encode the chars before request pass to Kestrel?
2. I can n't find those request record in IIS logs, is this exception capable ?

Thank for your help,
Best Regards,

**Comment by Tratcher** [comment] 2018-08-10 11:42
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/1144, @JunTaoLuo

**Closed by Tratcher** 2018-08-10 11:42 UTC
