### ISSUE TITLE
Flaky Test: Functional tests on Linux "disposing listeners failed"

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#1621] opened 2017-04-07 03:03 UTC
Seeing this as part of our partner acquisition linux builds but I suspect they are flaky on all platforms:

Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.EmptyRequestLoggedAsInformation
```
Disposing listeners failed
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<EmptyRequestLoggedAsInformation>d__0.MoveNext() in /datadrive/169923259d6dcfec/Universe/.r/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/HttpsTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.EmptyRequestLoggedAsInformation
```
Disposing listeners failed
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsTests.<EmptyRequestLoggedAsInformation>d__0.MoveNext() in /datadrive/169923259d6dcfec/Universe/.r/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/HttpsTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

More info: http://aspnetci/viewLog.html?buildId=197969&tab=buildResultsDiv&buildTypeId=CoreCLR_Linux

**Comment by JunTaoLuo** [comment] 2017-04-07 03:03
cc @cesarbs

**Comment by mikeharder** [comment] 2017-04-11 06:19
Another failure, also on Partner Acquisition \ Build: Linux

http://aspnetci/viewLog.html?buildId=199630&tab=buildResultsDiv&buildTypeId=CoreCLR_Linux

**Comment by davidfowl** [comment] 2017-04-11 06:54
I know why this fails now. I debugged the test and have a root cause. The fix unfortunately is part of the work that @halter73 is doing right now to move connection management into kestrel core.

**Comment by davidfowl** [comment] 2017-04-11 07:23
As described today by @halter73 this is happening because of a race between when the connection closes and when the libuv connections are walked during shutdown. Normally, the shutting down the server waits a for a certain amount of time before ending all connections, but since we made the change to immediately abort the connection on on a FIN, we lose track of that connection even though we may still be in the process of setting up the `FrameConnection`. This seems to be  causing a bunch of random test failures.

- Since the server doesn't wait on connections we can run the connection adapters after the uv_loop shuts down causing the debug assert here https://github.com/aspnet/KestrelHttpServer/issues/1616.
- Disposing listeners seems like a slowness issue. I'm still looking into it.

**Comment by davidfowl** [comment] 2017-04-11 07:41
This was from a run on my machine. Seems like the 2.5 second timeout might be too short. Something got slower.

```
Hosting starting
Hosting started
Connection id "0HL40LNU9EH94" started.
Connection id "0HL40LNU9EH94" received FIN.
Connection id "0HL40LNU9EH94" disconnecting.
Connection id "0HL40LNU9EH94" stopped.
Hosting shutdown
Disposing listener
Disposing 1 listeners
Disposing listener callback in 2223.7629ms
Walked 0 connections
```

**Comment by mikeharder** [comment] 2017-04-21 19:29
Another failure: http://aspnetci/viewLog.html?buildTypeId=CoreCLR_Linux&buildId=206363

**Comment by davidfowl** [comment] 2017-04-22 06:29
@halter73 What if we removed the Log "Dispose listeners failed"?

**Comment by davidfowl** [comment] 2017-04-22 06:43
I increased the timeout but if it keeps happening we're going to have to tweak this test to avoid looking for this error.

**Comment by Eilon** [comment] 2017-05-01 17:44
@davidfowl - anything left for preview1? Or would we juts fix things in `dev` at this point?

**Comment by davidfowl** [comment] 2017-05-01 23:45
Going to close this until it repros again.

/cc @mikeharder if it repros open this back up.

**Closed by davidfowl** 2017-05-01 23:45 UTC
Labels: 2 - Working, bug

**Comment by davidfowl** [comment] 2017-05-04 08:55
Saw this again on my linux box while running it in a loop over 2 days..
