### ISSUE TITLE
UvException: Error -4095 EOF end of file

### ISSUE THREAD

**Issue by oofpez** [aspnet/KestrelHttpServer#1965] opened 2017-07-21 09:30 UTC
I started getting this error regularly:

> ListenerPrimary.ReadCallback
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4095 EOF end of file
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.PipeReadContext.ReadCallback(UvStreamHandle dispatchPipe, Int32 status)</

I don't have any more information on the error, what are possible causes?

**Comment by halter73** [comment] 2017-07-21 21:52
This is usually the result of an external process trying to connect to a named pipe belonging to Kestrel. This used to cause real problems accepting new HTTP connections/requests since Kestrel didn't properly ignore these name pipe connections. You can read a little more background on the issue at #1182.

In Kestrel versions 1.0.2 and later, attempts by an external process to connect to the named pipe are now properly ignored. When that happens, you will see the exception above in your logs. Basically, Kestrel is expecting a handshake after an in-process named pipe connection is established, but the out-of-process connection immediately closes connection leading to an unexpected EOF error.

Are you running Kestrel in an Azure App Service by chance? In that environment there is a virus scanner that is known to try to connect to Kestrel's pipes about once every 24 hours.

You can actually force the error using powershell pretty easily to see what I'm talking about. Just run the following commands on machine with Kestrel running.

```
> ls \\.\pipe\ | grep kestrel
------       13/31/1600   4:00 PM              5 kestrel_70ae96135c554e5f90be1f417563a9a3
------       13/31/1600   4:00 PM              5 kestrel_6601589da5ed4d5fb7f47615a3119aaf

> # Pick any of the kestrel_* named pipes and "cat" it

> cat \\.\pipe\kestrel_72ae96135c554e5f90be1f417563a9a3
cat : FileStream was asked to open a device that was not a file. For support for devices like 'com2:' or 'lpt1:', call CreateFile, then use the
FileStream constructors that take an OS handle as an IntPtr.
At line:2 char:1
+ cat \\.\pipe\kestrel_71ae96135c554e5f90be1f417563a9a3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Content], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.GetContentCommand
```

If you take a look at the ASP.NET Core logs, you'll see the exact same EOF error you posed in this issue for each invocation of `cat \\.\pipe\kestrel_{random string}`.

**Comment by oofpez** [comment] 2017-07-24 12:16
It's much more frequent.  Also, it seems to be occuring only in one environment, so It must be related to some changes I made to the API.

I recently configured some middleware to read the request and response streams and log them.
I used some technique similar to here: https://stackoverflow.com/questions/43403941/how-to-read-asp-net-core-response-body

Do you think this could in any way be causing this issue?  All the Api calls are passing, but it randomly logs this error regularly.

**Comment by halter73** [comment] 2017-07-25 01:10
I don't see anyway this could be caused by wrapping and/or logging the request and response stream. This error can only be caused by something other than Kestrel opening one of Kestrel's named pipes.

**Comment by cesarbs** [comment] 2017-07-26 20:10
@oofpez What version of Kestrel are you using? What is your environment?

**Comment by skorunka** [comment] 2017-07-31 08:58
@halter73 Is there any chance to prevent this exception in Azure App Service?

**Comment by oofpez** [comment] 2017-07-31 10:05
Azure App Service (S2 instances) with the Microsoft.AspNetCore.AzureAppServicesIntegration 1.0.2 package
from what i can see, we are using 63.60712.2926 of Kudu.

**Comment by funkycoding** [comment] 2017-09-25 10:43
Hi,

Getting the same exception every day, at 4 PM and 7 PM. See screenshot below from app insights. Using Microsoft.AspNetCore.Server.Kestrel 1.1.2. Fun fact: Not seeing this on another web app, using the same package version.

![app-insights-kestrel-uv](https://user-images.githubusercontent.com/307410/30804737-d2089822-a1ee-11e7-9c36-b5706a348755.PNG)

**Comment by cesarbs** [comment] 2017-09-27 01:35
@funkycoding How long have you been observing this? Is it consistently around those times every day?

**Comment by funkycoding** [comment] 2017-09-27 07:03
@cesarbs If i look in app insights, it's been happening since 28-08 (this is the date when we put the web app there). I noticed the exception before, but due to @halter73 comment about virus scanner i wasn't (and still am) not really worried about it...

Anyway, short summary after scanning app insights:
 - between 28-08 and 19-09 this exception happened around 1 PM and 11 PM
 - between 20-09 and 26-09 this exception happened around 5 PM and 7 PM

Happy to share more intel if you need any.

**Comment by cesarbs** [comment] 2017-09-27 17:13
@funkycoding I think you're running into what's decribed by @halter73 near the top of this issue: https://github.com/aspnet/KestrelHttpServer/issues/1965#issuecomment-317120993

App Services has virus/security scanners that run there periodically, and it looks like they try to open Kestrel's pipes. The log message you're seeing is the scanner closing the pipe connection.

**Comment by yosigolan** [comment] 2017-10-08 06:09
Hey.
i have also received this error 2 days ago. i am using .net core 2 on azure app services. in my case, after this error my service stopped responding to any request.

**Comment by muratg** [comment] 2017-11-10 21:05
@yosigolan Could you share the exact logs?

**Comment by yosigolan** [comment] 2017-11-12 08:04
Hey @muratg . sorry, it was long ago i dont have the logs.

**Comment by centerboy88** [comment] 2017-12-06 14:17
i have the same issue... does anyone know if it's depending on the version of Kestrel ?

**Comment by muratg** [comment] 2017-12-06 18:27
@centerboy88 what version are you using? Also, what are the exact logs? Thanks.

**Comment by spelltwister** [comment] 2018-01-18 04:33
got this in app insights @ 7:14PM, 4:52PM, 1:11PM, 1:02PM, 7:04AM today.  Does this cause any problems or just noise in the logs?

```Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException:
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError (Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary+PipeReadContext.ReadCallback (Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

**Comment by muratg** [comment] 2018-01-18 17:54
@spelltwister What's the full stack trace there?

**Comment by spelltwister** [comment] 2018-01-19 23:16
that's all that was in the app insights record

**Comment by muratg** [comment] 2018-01-20 00:23
@spelltwister Got it. Was it a one-time thing only, or do you see these occasionally?

**Comment by spelltwister** [comment] 2018-01-24 16:54
I get a handful of these everyday.

**Comment by cgenin7** [comment] 2018-01-26 15:43
Allo,

I am also seeing these errors every 2 days or so. After this error, the app service stops responding to any request and I need to restart it.

**Comment by muratg** [comment] 2018-01-26 19:13
@cgenin7 are you able to take a process dump when this happens?

**Comment by cgenin7** [comment] 2018-01-30 15:46
I will provide one as soon as the problem is reproduced.

**Comment by erick-thompson** [comment] 2018-04-05 22:28
I've been seeing this same issue running on an Azure Web App (ASP.NET Core 2). Like @cgenin7, it causes the website to recycle, returning a 500 to caller. I have an hourly integration test that hits the Web App (fairly lightly), and it seems happen about once a day, regardless of deployment. That is, deploying the Web App doesn't seem to cause the error, and the error occurs when there hasn't been a deployment in days.

The Web App is fairly plain, mostly default values. It does have a Web Job running, and App Insights have been enabled. I have the same code running on 2 other Web Apps (CI, prestaging, prod). They all seem to have this problem, but not at the same frequency.

Any help would be great, as this is impacting customers.

Message:
`ListenerPrimary.ReadCallback`

Exception type:
`Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException`

Call stack:
```
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4095 EOF end of file
 at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
 at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.ListenerPrimary.PipeReadContext.ReadCallback(UvStreamHandle dispatchPipe, Int32 status)
```

**Comment by halter73** [comment] 2018-04-05 22:41
@erick-thompson Did you see my comment [here](https://github.com/aspnet/KestrelHttpServer/issues/1965#issuecomment-317120993)? Do you still see 500 responses when you force the ListenerPrimary.ReadCallback UvException in the way I suggest using the SCM powershell console? If you'r running 1.0.2 or later, the log is expected but the server should still remain healthy.

**Comment by erick-thompson** [comment] 2018-04-05 23:12
I'm on a shared app service plan, so I don't want to mess with other running apps. How can I determine the version of kestrel running?

In terms of expected but remaining healthly, the integration test fails with 500, and the only exceptions seen in App Insights are the one I referenced. Additionally, I do sometimes see failures (500) without anything appearing in App Insights. In theory, these could be a different issue, except that the behavior is the same in both cases (Kestrel exception and no exception), so I assume the process recycles before App Insights can send off the exception.

**Comment by erick-thompson** [comment] 2018-04-05 23:30
We're running 3 VMs in our app service plan, with about 50 web app instances. 

What is the best way to get an admin console? The console accessible from the Web App portal doesn't have permission to interact with named pipes.

**Comment by halter73** [comment] 2018-04-06 01:38
Just go to `https://<your app name>.scm.azurewebsites.net`. So basically just add ".scm" between your site name and "azurewebsites.net". This brings you to the Kudu portal which gives you a powershell console, let's you drag and drop files into your app, edit files, see environment variables, etc...

![image](https://user-images.githubusercontent.com/54385/38399593-1aa59de8-3900-11e8-9010-295477e2b9ab.png)

**Comment by Spaceman1861** [comment] 2018-05-01 03:33
I would like rid my logs of this error. 

Im getting it once per day per app slot.

@halter73 i have tried your script to replicate but im getting a Permission Denied response.

Is there a way i can disable the virus scanner?

**Comment by aspnet-hello** [comment] 2018-09-24 18:19
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Closed by aspnet-hello** 2018-09-24 18:19 UTC
