### ISSUE TITLE
Having RequestSizeLimit smaller than MaxRequestBufferSize causes a 502.3 for IIS hosted instead of the original response.

### ISSUE THREAD

**Issue by AndreyPereira** [aspnet/KestrelHttpServer#2602] opened 2018-05-22 02:15 UTC
Just created a new project on Visual Studio and did the following:
- set the RequestSizeLimit to 10 (yes, 10 bytes) via attribute ,globally or through a middleware, does not matter
- Try to read and catch the Request too large exception and try to return a 413 (code is below)
- End up with a 502.3 from IIS if the request has more than 1.1~ MB. If it is smaller, then i get my 413 as expected.

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [Route("api/values")]
    public class ValuesController : Controller
    {
        // GET api/values
        

		// POST api/values
		[HttpPost]
		[RequestSizeLimit(10)]
		public async Task<IActionResult> Post()
		{
			string Ret = "";
			try
			{
				using (StreamReader SR = new StreamReader(Request.Body))
				{
					Ret = SR.ReadToEnd();
				}
			}
			catch (Exception ex)
			{
				return await new ValueTask<ObjectResult>(StatusCode(413, ex.Message));
			}
			return await new ValueTask<ObjectResult>(StatusCode(200, Ret));

		}

		[HttpGet]
		public IEnumerable<string> Get()
		{
			return new string[] { "value1", "value2" };
		}

		// GET api/values/5
		[HttpGet("{id}")]
		public string Get(int id)
		{
			return "value";
		}
	}
}
```

**Comment by muratg** [comment] 2018-09-19 22:08
We'll attempt a repro.

**Comment by Tratcher** [comment] 2018-09-20 16:29
@AndreyPereira were your request sent using Content-Length or chunked?

I was able to reproduce this on 2.1 with a content-length request. A request body of length 147,247b works most of the time, but by the time you get up to 181,532b it fails most of the time. I don't see any indication the issue is related to MaxRequestBufferSize.

The ASP.NET Logs look identical for the success and failure scenarios:
```
WebApplication5> dbug: Microsoft.AspNetCore.Server.Kestrel[1]
WebApplication5>       Connection id "0HLGV20T9SCH3" started.
WebApplication5> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
WebApplication5>       Request starting HTTP/1.1 POST http://localhost:53607/api/values  181532
WebApplication5> dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
WebApplication5>       Request successfully matched the route with name '(null)' and template 'api/Values'.
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
WebApplication5>       Action 'WebApplication5.Controllers.ValuesController.Get (WebApplication5)' with id '62d0288c-c18a-431c-b61a-6ee5c08042c7' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'
WebApplication5> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Route matched with {action = "Post", controller = "Values"}. Executing action WebApplication5.Controllers.ValuesController.Post (WebApplication5)
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.RequestSizeLimitFilter
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Execution plan of exception filters (in the following order): None
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Internal.RequestSizeLimitFilter[3]
WebApplication5>       The maximum request body size has been set to 10.
WebApplication5> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
WebApplication5>       Executing action method WebApplication5.Controllers.ValuesController.Post (WebApplication5) - Validation state: Valid
WebApplication5> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
WebApplication5>       Executed action method WebApplication5.Controllers.ValuesController.Post (WebApplication5), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 0.538ms.
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11]
WebApplication5>       List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[4]
WebApplication5>       No information found on request to perform content negotiation.
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[8]
WebApplication5>       Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[10]
WebApplication5>       Attempting to select the first formatter in the output formatters list which can write the result.
WebApplication5> dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[2]
WebApplication5>       Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter' and content type 'text/plain' to write the response.
WebApplication5> info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
WebApplication5>       Executing ObjectResult, writing value of type 'System.String'.
WebApplication5> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
WebApplication5>       Executed action WebApplication5.Controllers.ValuesController.Post (WebApplication5) in 0.8051ms
WebApplication5> dbug: Microsoft.AspNetCore.Server.Kestrel[9]
WebApplication5>       Connection id "0HLGV20T9SCH3" completed keep alive response.
WebApplication5> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
WebApplication5>       Request finished in 1.4013ms 413 text/plain; charset=utf-8
WebApplication5> info: Microsoft.AspNetCore.Server.Kestrel[17]
WebApplication5>       Connection id "0HLGV20T9SCH3" bad request data: "Request body too large."
WebApplication5> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large.
WebApplication5>    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
WebApplication5>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.ForContentLength.OnReadStarting()
WebApplication5>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.TryInit()
WebApplication5>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ConsumeAsync()
WebApplication5>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
WebApplication5>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
WebApplication5> dbug: Microsoft.AspNetCore.Server.Kestrel[10]
WebApplication5>       Connection id "0HLGV20T9SCH3" disconnecting.
WebApplication5> dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
WebApplication5>       Connection id "0HLGV20T9SCH3" sending FIN.
WebApplication5> dbug: Microsoft.AspNetCore.Server.Kestrel[2]
WebApplication5>       Connection id "0HLGV20T9SCH3" stopped.
```

The response gets sent and then kestrel tries to drain the remaining data off the socket. This triggers the same length exception again and kestrel closes the connection.

This implies a race condition between kestrel sending the response and it closing the connection. Either the response does not get fully flushed before the close, or WinHttp/ANCM is not able to read the data off the socket before it sees it close. If I remove IIS from the picture and test Fiddler directly against Kestrel then I get the 413 every time. This implies a race in WinHttp/ANCM. It's possible WinHttp errors out if the connection closes before all of the request data is sent, and the variability is related to how much of the body fits into the outgoing TCP buffers. @pakrym to confirm from the ANCM end.

**Comment by Tratcher** [comment] 2018-09-20 16:37
Possible courses of action:
A) The server is being appropriately defensive when a basic protocol limit is exceeded, closing the connection is more important than giving the client a diagnostic error. No change required.
B) This is overly defensive and redundant with the RequestBodyDrainTimeout. We would like that error to reach the client. Consider disabling size limits while draining and rely solely on the timeout.

**Comment by Tratcher** [comment] 2018-09-25 22:21
I checked with Pavel and he agreed this is a side effect of using the ANCM out-of-proc reverse proxy. WinHttp reports the first error it sees which is the request body upload failure, it never notices the 413 response.

Using Kestrel directly does not have this issue. ANCM in-proc should also not be affected.

Closing this as all components are working as expected.

**Closed by Tratcher** 2018-09-25 22:21 UTC
