### ISSUE TITLE
Connection processing ends abnormally if referer header contains unencoded characters

### ISSUE THREAD

**Issue by Crimscent** [aspnet/KestrelHttpServer#1125] opened 2016-09-27 13:29 UTC
The issue is as follows:

IE11 and maybe some other browsers send unencoded characters in referer header, for example in russian: http://localhost/_api/users/search/тест .
Chrome and other browsers encode it and all is well, but IE11 sends it as it is, resulting in following log entries:

```
Connection id "" bad request data: "The input string contains non-ASCII or null characters." The input string contains non-ASCII or null characters.
Connection processing ended abnormally The input string contains non-ASCII or null characters.
```

**Comment by Tratcher** [comment] 2016-09-27 15:11
IE is probobly just parroting what it was sent by the prior server / response. It looks like this is coming from a different server on your own machine? What server software is it? Can you fix that site?

Can you use Microsoft Message Analyser to capture the raw bytes of the prior response and then this request? It would be good to know if the header is sent using UTF-8 or something else.

Also, nice error message... @cesarbs

**Comment by Crimscent** [comment] 2016-09-27 15:52
It's a simple ajax request from javascript using axios:

Raw request using Chrome:
```
GET http://localhost/_api/um/users?skip=0&take=25&q=%D0%B6%D0%BC%D0%B0 HTTP/1.1
Host: localhost
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Referer: http://localhost/users/search/%D0%B6%D0%BC%D0%B0
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```
Raw request using IE11:
```
GET http://localhost/_api/um/users?skip=0&take=25&q=%D0%B6%D0%BC%D0%B0 HTTP/1.1
Referer: http://localhost/users/search/жма
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.7,ru;q=0.3
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: localhost
Connection: Keep-Alive
```

The only real difference I see is in Referer header.
And yes, when the request is made that's what is in address bar.

**Comment by Tratcher** [comment] 2016-09-27 16:03
Can you show the trace for the prior request to http://localhost/users/search/жма?

We'll also still want to see the raw bytes for the prior request and this one to confirm the wire encoding.

**Comment by Crimscent** [comment] 2016-09-27 16:50
Sorry if I misunderstand you somehow, but here is initial request. It returns simple index.html.
```
GET http://localhost/users/search/%D0%B6%D0%BC%D0%B0 HTTP/1.1
Host: localhost
Proxy-Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```
http://localhost/ is an asp.net core 1.0.1 web application hosted in IIS, here is the [code](https://github.com/Crimscent/simple-web-server)
http://localhost/_api/ is similar asp.net core 1.0.1 web application hosted in IIS as well.

I doubt that I will be able to send you raw bytes.

**Comment by Crimscent** [comment] 2016-09-27 17:06
http://localhost/ is an asp.net core 1.0.1 web application hosted in IIS, here is the [code](https://github.com/Crimscent/simple-web-server)
http://localhost/_api/ is similar asp.net core 1.0.1 mvc web application hosted in IIS as well.

Initial request to index.html:
```
GET http://localhost/users/search/%D0%B6%D0%BC%D0%B0 HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Accept-Language: en-US,en;q=0.7,ru;q=0.3
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
Pragma: no-cache
Host: localhost
```
What's more, any request to static file fails as well:
```
GET http://localhost/styles/select2.min.css HTTP/1.1
Accept: text/css, */*
Referer: http://localhost/users/search/жма
Accept-Language: en-US,en;q=0.7,ru;q=0.3
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Accept-Encoding: gzip, deflate
Host: localhost
Connection: Keep-Alive
Pragma: no-cache
```
I won't be able to provide you raw bytes today and sorry if I misunderstood you somehow.

**Comment by Tratcher** [comment] 2016-09-27 18:33
This may be related: https://blogs.msdn.microsoft.com/ieinternals/2014/04/22/unicode-in-url-changes-for-ie11/
It may be trying to use your system encoding by default.

**Comment by halter73** [comment] 2016-09-27 19:27
@Tratcher I saw that too. It seems that this is a new issue in IE 11: http://answers.microsoft.com/en-us/ie/forum/ie11-windows_other/ie11-sends-unencoded-url-referer-header/7420a770-56eb-4317-b00f-3322637dc62b

Apparently the change was made in part to "match the behavior of other browsers." It would be interesting to find out if any other browsers actually exhibit this behavior. This is somewhat related to https://github.com/aspnet/KestrelHttpServer/issues/564

If I were to change Kestrel to support non-ASCII characters, I would treat *everything* as UTF-8. At least that wouldn't break anything that is ASCII.

**Comment by Tratcher** [comment] 2016-09-27 19:33
We haven't confirmed the browser's sending utf-8 bytes in this case. It may be using local code pages.

**Comment by halter73** [comment] 2016-09-27 21:34
@Tratcher Your msdn blog link indicates it's utf-8.

**Comment by cesarbs** [comment] 2016-09-27 21:40
@Tratcher About the error message, not sure why it showed up like that in @Crimscent's post. I see this:

```
Connection id "0HKV73R9T60C2" bad request data: "The input string contains non-ASCII or null characters."
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end) in D:\src\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Infrastructure\MemoryPoolIteratorExtensions.cs:line 122
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeMessageHeaders(SocketInput input, FrameRequestHeaders requestHeaders) in D:\src\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Http\Frame.cs:line 1225
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext() in D:\src\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel\Internal\Http\FrameOfT.cs:line 65
```

**Comment by Tratcher** [comment] 2016-09-27 21:55
@halter73 we haven't confirmed the encoding from @Crimscent's repro.

**Comment by Crimscent** [comment] 2016-09-28 09:03
[matp.zip](https://github.com/aspnet/KestrelHttpServer/files/497554/matp.zip)
1.matp - initial request
2.matp - request for css with unencoded referer.
I changed my system locale, language, etc. to "English (United States)" prior to data capture.

**Comment by Tratcher** [comment] 2016-09-28 20:54
Ok, the raw bytes are `0xD0, 0xB6, 0xD0, 0xBC, 0xD0, 0xB0`, which is utf-8 for `жма`. That's bizarre that they would start doing this.

**Comment by benaadams** [comment] 2016-09-29 01:34
Bit strange to do it for the referrer only (i.e. encode the regular url as normal)

**Comment by muratg** [comment] 2016-10-31 21:32
Subsumed by #1144, closing.

**Closed by muratg** 2016-10-31 21:32 UTC
Labels: duplicate
