### ISSUE TITLE
What if a corresponding KestrelHttpClient

### ISSUE THREAD

**Issue by hismichael** [aspnet/KestrelHttpServer#1560] opened 2017-03-26 01:21 UTC
We know that many server projects have implemented their client libraries as well, such as Netty, Undertow, so forth. Those are very comfortable to use on server side.

I had rolled out a couple of web servers in the past, all with client connectivity.

What if there is a corresponding KestrelHttpClient? as a (better) alternative to HttpClient in clustered environments.

**Comment by khellang** [comment] 2017-03-26 02:49
What's wrong with the existing HttpClient?

**Comment by davidfowl** [comment] 2017-03-26 02:52
It hasn't gotten the same perf treatment that kestrel has. @stephentoub @geoffkizer are working on improving that. We've toyed around with the idea though (I call it reverse kestrel).

**Comment by geoffkizer** [comment] 2017-03-26 02:56
We are definitely looking at HttpClient performance.

Though, if "better alternative to HttpClient" is about more than just performance, it would be good to hear those issues too...

**Comment by hismichael** [comment] 2017-03-26 04:43
> It hasn't gotten the same perf treatment that kestrel has. @stephentoub @geoffkizer are working on improving that. We've toyed around with the idea though (I call it reverse kestrel).

Nice to hear those, too.

> Though, if "better alternative to HttpClient" is about more than just performance, it would be good to hear those issues too...

Despite of the perf issue, I prefer a reverse kestrel working together with the kestrel server on SERVER environments. IMHO its API is well-thought-out and less focusing on application-level tasks such as object serialization. I assume that HttpClient wasn't initially created for running on the server side.

**Comment by geoffkizer** [comment] 2017-03-26 15:25
> I assume that HttpClient wasn't initially created for running on the server side.

HttpClient is intended to run well on the server side.  How well it does this is a separate question.

Re API, it would be great to look at some examples of what you mean.  Are there common tasks that are painful with HttpClient, but would be easier with a Kestrel-like API?  What would the code for these look like in both cases?

In some cases, I'm sure we could improve usability of HttpClient.  In other cases, this may be difficult, if the problem is rooted in the basic design of HttpClient.  I'd like to understand the specific scenarios better and evaluate what we could potentially do.

Alternatively, perhaps what you really want is an API/object model that is common across server and client -- thus KestrelHttpServer and KestrelHttpClient.  If so, that would be interesting to know too.

**Comment by Drawaes** [comment] 2017-03-26 15:29
I would say wait for pipelines then there are more possibilities for server side pooling, keep alive and passing through headers.

**Comment by hismichael** [comment] 2017-03-27 02:25
concerning the HttpContent class:

1) The ReadAsByteArrayAsync() method now conveniently returns an internally prepared byte[]. While in many cases I would prefer another ReadAsync(byte[] buffer, int offset, int count) method which let the caller to manage the byte[]. 

2) HttpContent includes Headers, this design could reduce the flexibility of its custom subclassing, especially when out of the content of HTTP. 

3) In fact, I don't like a strong content model at all. I prefer it simply be byte[] or Stream. Or at most, a IHttpContent interface.

**Comment by Drawaes** [comment] 2017-03-27 03:07
The HttpContent class for sending also, can't be reused, they are one shot, therefore allocations every time.

**Comment by hismichael** [comment] 2017-03-27 03:52
> The HttpContent class for sending also, can't be reused, they are one shot, therefore allocations every time.

Yeah. My questions is: Why we need such a class?

**Comment by stephentoub** [comment] 2017-03-27 04:03
> The HttpContent class for sending also, can't be reused, they are one shot

That could be fixed. There's nothing inherent to the model that prevents it from being reused.

**Comment by Tratcher** [comment] 2017-03-27 04:05
Except that it's disposable and HttpClient always disposes it.

**Comment by stephentoub** [comment] 2017-03-27 04:09
Like I said, that could be fixed. If we're considering new APIs, it'd be trivial to add something that tells HttpClient not to dispose it and to leave it up to the caller to do so.

**Comment by davidfowl** [comment] 2017-03-27 04:33
@hismichael There are design choices in http client that I don't think any of us (except maybe @Tratcher) were privy to during the original design. I'm personally not married to them but it would be good to understand which specific things you have an issue with so we can see what can be patched and which ones would require a different API surface.

**Comment by hismichael** [comment] 2017-03-27 15:42
@davidfowl No specific issue for me. And as far as this post titled about (KestrelHttpClient), I've got answers. Thank you all!

**Comment by hismichael** [comment] 2017-03-27 15:43
@davidfowl No specific issue for me. And as far as this post titled about (KestrelHttpClient), I've got answers. Thank you all!

**Comment by benaadams** [comment] 2017-03-27 15:48
Can see something for `Kestrel<->Kestrel`, `HttpSysServer<->Kestrel`, `AspNetCoreModule<->Kestrel` fast path for localhost? e.g. pipe or memory mapped file... maybe...

**Comment by benaadams** [comment] 2017-03-27 15:50
Can see something for `Kestrel<->Kestrel`, `HttpSysServer<->Kestrel`, `AspNetCoreModule<->Kestrel` fast path for localhost? e.g. pipe or memory mapped file... maybe...

localhost does have a port exhaustion issue like any single external ip ->server pair would; but is more exassibated on localhost as its all the same ip

**Comment by muratg** [comment] 2017-05-12 22:11
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 22:11 UTC
