### ISSUE TITLE
Broken test: ConnectionResetLoggedWithActiveStreams

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2362] opened 2018-03-05 23:29 UTC
A lot of tests seem to have been broken by our move to Http2. I'm Skipping them for now, but we need to triage and fix them.

Non-exhaustive list of failures [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:CollectionDiff,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

```
The collection contained 0 matching element(s) instead of 1.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.<ConnectionResetLoggedWithActiveStreams>d__127.MoveNext() in /_/test/Kestrel.Core.Tests/Http2ConnectionTests.cs:line 1974
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Affected tests:
- ConnectionResetLoggedWithActiveStreams

**Comment by Tratcher** [comment] 2018-03-05 23:52
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/2359?

**Closed** 2018-03-06 00:04 UTC
