### ISSUE TITLE
DebugAssertException: Block being garbage collected instead of returned to pool

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#667] opened 2016-03-02 18:30 UTC
This DebugAssertException has been showing up in some of our CI runs since I enabled it [a little over a week ago](https://github.com/aspnet/KestrelHttpServer/pull/623). The issue doesn't affect most test runs, but I think this exception has mostly shown up in Microsoft.AspNetCore.Server.KestrelTests.

Here is a run on AppVeyor that failed due to this assertion: https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.2396

It's possible that Kestrel is still not properly returning blocks in some circumstances, but this could also be a test issue (particularly if it is unit tests that are causing the issue).

I know @cesarbs has already started investigating this and has set up a small VM that repros the issue more reliably than most of our workstations, so I'm assigning it to him for now.

**Comment by cesarbs** [comment] 2016-03-02 19:10
Yep, and I've already found out that the culprits are `Http10KeepAliveContentLength` in `EngineTests` and `Http10TransferEncoding` in `ChunkedRequestTests` (which was previously in `EngineTests`. I haven't found any other leaky tests (yet :grin:). The problem is that the memory blocks allocated by `SocketOutput` instances are never returned when the `KestrelEngine` instance is disposed in those tests. I haven't yet found a way to make that happen.

**Comment by halter73** [comment] 2016-03-02 19:15
@cesarbs Can you add a [trace here](https://github.com/aspnet/KestrelHttpServer/blob/9c64a492615e2fa9153021438fd053301e9a3d4a/src/Microsoft.AspNetCore.Server.Kestrel/Infrastructure/KestrelThread.cs#L135) to see if any sockets are being disposed "rudely" when this happens? That might explain the issue.

**Comment by cesarbs** [comment] 2016-03-02 19:17
To double check: do you mean a trace inside the walk, or in `OnStopRude`? I do know that `OnStopRude` is being called.

**Comment by halter73** [comment] 2016-03-02 19:44
`OnStopRude` is always called as the code is written today. That might change once #641 is fixed. What matters is if any sockets are being disposed there.

**Comment by benaadams** [comment] 2016-03-02 19:58
If that is the issue, dispose the Slabs in `OnStopXXX` so `IsActive == false` which should resolve the issue?

**Comment by halter73** [comment] 2016-03-02 20:24
@benaadams Good point. When I first made the change to uncomment the `Debug.Assert`, I didn't have the `|| IsActive == false` so a rude shutdown could cause issues. Now it shouldn't...

**Comment by cesarbs** [comment] 2016-03-03 04:37
I found the problem.

The way things are right now, the slabs should be properly disposed i.e. `IsActive` is set to `false`:

1) The tests call `TestServer.Dispose`.
2) `TestServer.Dispose` calls `_server.Dispose`. `_server` is a `Disposable`.
3) `Disposable` will call its action, which is `KestrelEngine.DisposeListeners`.
4) As each `Listener` is disposed, its `MemoryPool2` is disposed.
5) As each `MemoryPool2` is disposed, its `MemoryPoolSlab2`s are disposed.
6) `MemoryPoolSlab2` sets `IsActive` to `false`.

The problem is in `KestrelEngine.DisposeListeners`. It creates tasks to dispose the listeners, but never runs them. I'll send a PR shortly. The call to `Log.NotAllConnectionsClosedGracefully()` is always made.

**Comment by cesarbs** [comment] 2016-03-03 04:52
I mean, the dispose tasks are called but it seems their `Post`s end up never running.

**Comment by cesarbs** [comment] 2016-03-03 05:00
In `KestrelEngine.DisposeListeners`, if I change

    disposeTasks.Add(listener.DisposeAsync());

to:

    var task = new Task(async () => await listener.DisposeAsync());
    disposeTasks.Add(task);
    task.Start();

The listeners are disposed and the debug assertion is gone.

This makes no sense to me. Ideas?

**Comment by cesarbs** [comment] 2016-03-03 05:06
More specifically, the lambda passed to the second `PostAsync` in `Listener.Dispose` doesn't run.

**Comment by cesarbs** [comment] 2016-03-03 05:11
I removed my comment on changing how the listener dispose task is run. That doesn't really solve the issue.

Ok, so you guys suggested I dispose the slabs in `OnStop`*. The threads don't have direct access to the memory pool right now. I see two ways to expose them:

1) Add a `ListenerContext` property to `KestrelThread` and set it when creating each listener.
2) Expose the listeners from `KestrelEngine`.

What do you think?

**Comment by benaadams** [comment] 2016-03-03 14:28
Does disposing the MemoryPool early cause any issues?

e.g. could `Memory.Dispose()` be moved to the top of `DisposeAsync`?

**Comment by cesarbs** [comment] 2016-03-03 16:54
@benaadams That seems to work. I was a bit uneasy about moving it earlier, but there doesn't seem to be anything that could try to allocate new memory while the server is being shutdown.

**Comment by halter73** [comment] 2016-03-03 18:30
@benaadams @cesarbs Obstensibly the 5s timeout on listener shutdown is to give the application time to finish processing the current request. So blocks can still be leased for writing, further input on existing sockets, etc...

**Comment by halter73** [comment] 2016-03-03 18:34
Oh, and this shows that my suggestion about checking whether `OnStopRude` was disposing sockets was actually sensible even if I forgot why :grin: It shows there wasn't a graceful shutdown and all the pools weren't likely disposed. It certainly would have been better to suggest looking at whether `Log.NotAllConnectionsClosedGracefully()` was logged though.

**Comment by halter73** [comment] 2016-03-04 00:58
:shipit:

**Comment by cesarbs** [comment] 2016-03-04 04:57
@halter73 I think you meant to comment that on #669 :grin:

**Closed** 2016-03-04 07:58 UTC
Labels: 3 - Done
