### ISSUE TITLE
Cannot deploy my app on azure due to Error -4089 EAFNOSUPPORT address family not supported

### ISSUE THREAD

**Issue by nukec** [aspnet/KestrelHttpServer#1730] opened 2017-04-20 19:15 UTC
I published net core application on my azure server.

I am getting this displayed on my azure server:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/UNIem.png

Error on application insight is:

> Application version: 1.0.0.0 AspNetCoreEnvironment: Production
> Assembly: Unknown City: Dublin Client IP address: 191.235.220.0
> Country or region: Ireland Device type: PC Event count: 1.00 Event
> time: 20/04/2017 17:27:35 EventId: 3312925812 Exception type:
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException
> Failed method: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
> includeTaskCanceledExceptions) handledAt: UserCode Innermost exception
> message: Error -4089 EAFNOSUPPORT address family not supported
> Innermost exception type:
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException
> LogLevel: Warning MessageTemplate: Unable to bind to
> http://localhost:14710 on the IPv6 loopback interface. Outer exception
> message: One or more errors occurred. (Error -4089 EAFNOSUPPORT
> address family not supported) Outer exception method:
> System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
> includeTaskCanceledExceptions) Outer exception type:
> System.AggregateException Problem ID:
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException at
> System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
> includeTaskCanceledExceptions) RenderedMessage: Unable to bind to
> http://localhost:14710 on the IPv6 loopback interface. SDK version:
> dotnet:2.2.0-54036 Severity level: Warning SourceContext:
> Microsoft.AspNetCore.Server.Kestrel State or province: Leinster
> 
> Stack Trace
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException:
> Error -4089 EAFNOSUPPORT address family not supported
>     at  Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle
> handle, SockAddr& addr, Int32 flags)
>     at  Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress
> address)
>     at  Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
>     at  Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object
> state)
> 
> System.AggregateException: One or more errors occurred. (Error -4089
> EAFNOSUPPORT address family not supported)
>     at  System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>     at  System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>     at  Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress
> address)
>     at  Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1
> application)

I read on other websites it's not a big deal and it should be ignored, but i can't start app at all.

**Comment by natemcmaster** [comment] 2017-04-20 19:20
Likely duplicate of https://github.com/aspnet/KestrelHttpServer/issues/1239, assuming the message is a warning and not a fatal error. @nukec is your app running despite the message about EAFNOSUPPORT?

**Comment by nukec** [comment] 2017-04-20 19:23
I put image showing  An error occured while starting the application.

**Comment by natemcmaster** [comment] 2017-04-20 19:27
We've made some improvements recently to fix ipv6 errors (see #1717), but this won't be in until 2.0.0. Can you share your configuration details? e.g. what are your environment variables, have you called `.UseUrls()` on WebHostBuilder, etc. We may be able to provide a workaround.

**Comment by nukec** [comment] 2017-04-20 22:28
is fine i put some wrong settings

**Comment by natemcmaster** [comment] 2017-04-20 23:55
Ok, feel to re-open if needed.

**Closed by natemcmaster** 2017-04-20 23:55 UTC
