### ISSUE TITLE
GET Timeout when Kestrel is behind a reverse proxy on Linux

### ISSUE THREAD

**Issue by kpocza** [aspnet/KestrelHttpServer#468] opened 2015-12-11 19:29 UTC
OS: Ubuntu 14.4
ASP.NET5 version: RC1
Mono: 4.2.1

I'm exposing 4 kestrel web services on port no. 8000, 8001, 8002 and 8003. When I reach the services from the outside world everything is fine, I get response very fast for every requests (using .NET WebClient).

However my goal is to expose all services on port no. 80 under some designated locations (/api, /papi, etc.) which can be achieved by putting the services behind a reverse proxy. Previously (beta7 era) I was using tinyproxy, however in case of rc1 I experience timeouts for tinyproxy and for nginx, as well.

It's makes things even interesting that POST request are fine but GET requests are failing.

I was doing an strace on the nginx processes.

This is a successful request-response for a POST: reading from the network, writing to Kestrel, reading from Kestrel, writing to network.
```
2763  recvfrom(7, "POST /api/v1/users/register HTTP/1.1\r\nContent-Type: application/json\r\nHost: ubuntuthriottesthost\r\nContent-Length: 97\r\nExpect: 100-continue\r\nConnection: Keep-Alive\r\n\r\n", 1024, 0, NULL, NULL) = 166
2763  sendto(7, "HTTP/1.1 100 Continue\r\n\r\n", 25, 0, NULL, 0) = 25
2763  recvfrom(7, 0x1890990, 97, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
2763  epoll_wait(14, {{EPOLLIN, {u32=2255806864, u64=139777671487888}}}, 512, 60000) = 1
2763  gettimeofday({1449858779, 255726}, NULL) = 0
2763  recvfrom(7, "{\"Email\":\"e349c441-6ad1-44e2-802c-9a929b68d3aa@test.hu\",\"Password\":\"p@ssw0rd\",\"Name\":\"test user\"}", 97, 0, NULL, NULL) = 97
2763  epoll_ctl(14, EPOLL_CTL_MOD, 7, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=2255806864, u64=139777671487888}}) = 0
2763  socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 9
2763  ioctl(9, FIONBIO, [1])            = 0
2763  epoll_ctl(14, EPOLL_CTL_ADD, 9, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=2255807056, u64=139777671488080}}) = 0
2763  connect(9, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
2763  epoll_wait(14, {{EPOLLOUT, {u32=2255806864, u64=139777671487888}}, {EPOLLOUT, {u32=2255807056, u64=139777671488080}}}, 512, 60000) = 2
2763  gettimeofday({1449858779, 255959}, NULL) = 0
2763  getsockopt(9, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
2763  writev(9, [{"POST /v1/users/register HTTP/1.0\r\nHost: ubuntuthriottesthost\r\nX-Real-IP: 192.168.0.2\r\nX-Forwarded-For: 192.168.0.2\r\nConnection: close\r\nContent-Length: 97\r\nContent-Type: application/json\r\n\r\n", 189}, {"{\"Email\":\"e349c441-6ad1-44e2-802c-9a929b68d3aa@test.hu\",\"Password\":\"p@ssw0rd\",\"Name\":\"test user\"}", 97}], 2) = 286
2763  recvfrom(7, 0x7fff0fa9ab2f, 1, 2, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
2763  epoll_wait(14, {{EPOLLIN|EPOLLOUT, {u32=2255807056, u64=139777671488080}}}, 512, 60000) = 1
2763  gettimeofday({1449858779, 276793}, NULL) = 0
2763  recvfrom(9, "HTTP/1.0 200 OK\r\nCache-Control: no-cache\r\nDate: Fri, 11 Dec 2015 18:32:59 GMT\r\nPragma: no-cache\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\nServer: Kestrel\r\nSet-Cookie: ThriotMgmtAuth=CfDJ8A-YPKeA7-lLphX92nmImKg4D7ruQ3WPm4X-9m9wtErvPgerZxjx_KULjxRP54p0aOpdIofeONj-AyuNlKe3kQi1K0mw-IXsBG2mBrXMpGTbcH8l9v1MIhHIbHvHqEzyk7cgp6lzwcvdQ4AcoTzbOu1Sr5VXKJv-Shg35MAJmy988PrtuAPhUVxBHOlDQxz9Wd4Wm_p9Gm2DMVXs7SF4HB3cQUsMVQQqWoW8UT9Q9qfV9gOMKKr8y8kws0bcjFcEsFEczKqfMmzjKKK-vy1moRrDK8Re-THb7Fcg2cADB7v4kytG238WuqqS6SKkIkdRLCyVFr3lZUtiO88lPW00JUs; path=/\r\n\r\n{\"NeedsActivation\":false}", 4096, 0, NULL, NULL) = 585
2763  readv(9, 0x7fff0fa9a920, 1)       = -1 EAGAIN (Resource temporarily unavailable)
2763  epoll_wait(14, {{EPOLLIN|EPOLLOUT, {u32=2255807056, u64=139777671488080}}}, 512, 59979) = 1
2763  gettimeofday({1449858779, 276997}, NULL) = 0
2763  readv(9, [{"f\276I\250\36\v\0p\212l\0\0\0\0\0\23\0\0\0\0\0\0\0\334\23J\0\0\0\0\0c\10w\264\322\25\334\262\250\212l\0\0\0\0\0\r\0\0\0\0\0\0\0\215\375I\0\0\0\0\0\22V\216\363W&\212]\340\212l\0\0\0\0\0\7\0\0\0\0\0\0\0\27\23J\0\0\0\0\0004\247\366\261\25\0\0\0\30\213l\0\0\0\0\0\r\0\0\0\0\0\0\0\177\375I\0\0\0\0\0;kGS\366\303aHP\213l\0\0\0\0\0\n\0\0\0\0\0\0\0%\341I\0\0\0\0\0\336~\304\321\221\245\t\0\210\213l\0\0\0\0\0\n\0\0\0\0\0\0\0\333\341I\0\0\0\0\0\205`\226\f\366]\n\0\300\213l\0\0\0\0\0\f\0\0\0\0\0\0\0\360\23J\0\0\0\0\0\325\262\r\342\2140\336*\370\213l\0\0\0\0\0\17\0\0\0\0\0\0\0\17\23J\0\0\0\0\0\272\312\3\243FB\7\3560\214l\0\0\0\0\0\20\0\0\0\0\0\0\0\376\22J\0\0\0\0\0\26ET\2\335\6\341\322h\214l\0\0\0\0\0\22\0\0\0\0\0\0\0\37\23J\0\0\0\0\0l&\366\374\2616\272\236\240\214l\0\0\0\0\0\21\0\0\0\0\0\0\0002\23J\0\0\0\0\0\250\365\374\345\300\310?\211\330\214l\0\0\0\0\0\17\0\0\0\0\0\0\0D\23J\0\0\0\0\0\322\204\32\35FB\7\356\20\215l\0\0\0\0\0\21\0\0\0\0\0\0\0\230\341I\0\0\0\0\0\365\260\366K\325v\362\311H\215l\0\0\0\0\0\20\0\0\0\0\0\0\0`\375I\0\0\0\0\0't\340|\225\351\357\334\200\215l\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\4\0\0\0\0\0\0\0\34\342I\0\0\0\0\0\256\357.\0\0\0\0\0\1\0\0\0\0\0\0\0\6\0\0\0\0\0\0\0\244\230J\0\0\0\0\0C/\2\312\0\0\0\0\1\0\0\0\0\0\0\0\5\0\0\0\0\0\0\0\\bJ\0\0\0\0\0\276)\261\6\0\0\0\0\1\0\0\0\0\0\0\0\17\0\0\0\0\0\0\0\17\23J\0\0\0\0\0\272\312\3\243FB\7\356\1\0\0\0\0\0\0\0\20\0\0\0\0\0\0\0\376\22J\0\0\0\0\0\26ET\2\335\6\341\322\1\0\0\0\0\0\0\0\22\0\0\0\0\0\0\0\37\23J\0\0\0\0\0l&\366\374\2616\272\236\1\0\0\0\0\0\0\0\21\0\0\0\0\0\0\0002\23J\0\0\0\0\0\250\365\374\345\300\310?\211\1\0\0\0\0\0\0\0\17\0\0\0\0\0\0\0D\23J\0\0\0\0\0\322\204\32\35FB\7\356\1\0\0\0\0\0\0\0\4\0\0\0\0\0\0\0 \341I\0\0\0\0\0\250\3650\0\0\0\0\0\1\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0%\341I\0\0\0\0\0\336~\304\321\221\245\t\0\1\0\0\0\0\0\0\0\16\0\0\0\0\0\0\0\200\341I\0\0\0\0\0\272"..., 3511}], 1) = 0
2763  close(9)                          = 0
2763  writev(7, [{"HTTP/1.1 200 OK\r\nServer: nginx/1.4.6 (Ubuntu)\r\nDate: Fri, 11 Dec 2015 18:32:59 GMT\r\nContent-Type: application/json; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nExpires: -1\r\nSet-Cookie: ThriotMgmtAuth=CfDJ8A-YPKeA7-lLphX92nmImKg4D7ruQ3WPm4X-9m9wtErvPgerZxjx_KULjxRP54p0aOpdIofeONj-AyuNlKe3kQi1K0mw-IXsBG2mBrXMpGTbcH8l9v1MIhHIbHvHqEzyk7cgp6lzwcvdQ4AcoTzbOu1Sr5VXKJv-Shg35MAJmy988PrtuAPhUVxBHOlDQxz9Wd4Wm_p9Gm2DMVXs7SF4HB3cQUsMVQQqWoW8UT9Q9qfV9gOMKKr8y8kws0bcjFcEsFEczKqfMmzjKKK-vy1moRrDK8Re-THb7Fcg2cADB7v4kytG238WuqqS6SKkIkdRLCyVFr3lZUtiO88lPW00JUs; path=/\r\n\r\n", 625}, {"19\r\n", 4}, {"{\"NeedsActivation\":false}", 25}, {"\r\n", 2}, {"0\r\n\r\n", 5}], 5) = 661
2763  write(4, "192.168.0.2 - - [11/Dec/2015:19:32:59 +0100] \"POST /api/v1/users/register HTTP/1.1\" 200 61 \"-\" \"-\"\n", 99) = 99
2763  setsockopt(7, SOL_TCP, TCP_NODELAY, [1], 4) = 0
2763  recvfrom(7, 0x18997c0, 1024, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
```

This is a failing GET: reading from network, writing to Kestrel, reading from Kestrel and nothing more.
```
2763  recvfrom(7, "GET /api/v1/users/me HTTP/1.1\r\nContent-Type: application/json\r\nHost: ubuntuthriottesthost\r\nCookie: ThriotMgmtAuth=CfDJ8A-YPKeA7-lLphX92nmImKiCbkrbk0IPExBQa4T7QVcSEF5YQ0TiSB4Xl5kdLMDnH3wBUma5Y-32yIx2yqmf-sZSgiKKXwEw81oBZv10Hbr7LGtcWx5O2xMeC5VxhisZHXTGgmEWl3usSJlXMn0CscvW7EFMSp_RjohDX93SmRkq9rV74RfOKCTeJikbO7MT0vlF-eOp4hBrXpLOtOjsA_bs9EBo-WJWtRMxOAKZWhsDqtz1I2mjQi0xem5mNMkUOpbeoa8XC7d4olcgu83F2CKM9TULbZcDx3gbEwJSwMFHzm0OQ4OjpY_8ZadKSZ52uNzxsOlk2ic1_bzNIspuqZE\r\n\r\n", 1024, 0, NULL, NULL) = 465
2763  socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 9
2763  ioctl(9, FIONBIO, [1])            = 0
2763  epoll_ctl(14, EPOLL_CTL_ADD, 9, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=2255807057, u64=139777671488081}}) = 0
2763  connect(9, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
2763  epoll_wait(14, {{EPOLLOUT, {u32=2255807057, u64=139777671488081}}}, 512, 60000) = 1
2763  gettimeofday({1449858779, 395954}, NULL) = 0
2763  getsockopt(9, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
2763  writev(9, [{"GET /v1/users/me HTTP/1.0\r\nHost: ubuntuthriottesthost\r\nX-Real-IP: 192.168.0.2\r\nX-Forwarded-For: 192.168.0.2\r\nConnection: close\r\nContent-Type: application/json\r\nCookie: ThriotMgmtAuth=CfDJ8A-YPKeA7-lLphX92nmImKiCbkrbk0IPExBQa4T7QVcSEF5YQ0TiSB4Xl5kdLMDnH3wBUma5Y-32yIx2yqmf-sZSgiKKXwEw81oBZv10Hbr7LGtcWx5O2xMeC5VxhisZHXTGgmEWl3usSJlXMn0CscvW7EFMSp_RjohDX93SmRkq9rV74RfOKCTeJikbO7MT0vlF-eOp4hBrXpLOtOjsA_bs9EBo-WJWtRMxOAKZWhsDqtz1I2mjQi0xem5mNMkUOpbeoa8XC7d4olcgu83F2CKM9TULbZcDx3gbEwJSwMFHzm0OQ4OjpY_8ZadKSZ52uNzxsOlk2ic1_bzNIspuqZE\r\n\r\n", 534}], 1) = 534
2763  epoll_wait(14, {{EPOLLIN|EPOLLOUT, {u32=2255807057, u64=139777671488081}}}, 512, 60000) = 1
2763  gettimeofday({1449858779, 399835}, NULL) = 0
2763  recvfrom(9, "HTTP/1.0 200 OK\r\nDate: Fri, 11 Dec 2015 18:32:59 GMT\r\nContent-Type: application/json; charset=utf-8\r\nServer: Kestrel\r\n\r\n{\"Id\":\"00613243798e104a45a2b14e6a8645e8\",\"Name\":\"test user\",\"Email\":\"e349c441-6ad1-44e2-802c-9a929b68d3aa@test.hu\"}", 4096, 0, NULL, NULL) = 235
2763  readv(9, 0x7fff0fa9a920, 1)       = -1 EAGAIN (Resource temporarily unavailable)
2763  epoll_wait(14,  <unfinished ...>
2762  <... epoll_wait resumed> {}, 512, 500) = 0
```
I don't know whether the missing Content-Length header causes this error or there is some networking issue but it's quite strange. And even I don't know whether this is an error really only for GET or it has nothing to do with the HTTP verb.

The source code for the whole application is here:
https://github.com/kpocza/thriot

**Comment by benaadams** [comment] 2015-12-11 20:34
What happens on the unstable/RC2 branch? Does this behave better?

**Comment by kpocza** [comment] 2015-12-12 13:08
Much better.
It would have been to much effort to upgrade the whole solution to the unstable dnx so instead of that I've created the default ASP.NET5 WebAPI sample solution of VS 2015 and tried it on rc1 and unstable/rc2. The exact version for Microsoft.AspNet.Server.Kestrel was 1.0.0-rc2-16127, dnx was 1.0.0-rc2-16258 for Mono.
Just tried the GET request from a webbrowser. When I've addressed the service directly, rc1 and unstable/rc2 was also fine, however through nginx in case of rc1 it was waiting for something to happen desperately without success as expected, fortunately on unstable/rc2 it worked flawlessly.

Publishing on Windows for Linux however was not successful for rc2 since when trying to run the package on Linux, dnx was looking for System.Runtime.InteropServices.RuntimeInformation but couldn't end up with the right dll.
So I've restored and published the whole stuff on Linux. 

According to this quick smoke test the problem seems to be cured in rc2, but for the sake of safety other verbs even under heavier load might be also tested through nginx, preferably.

**Comment by benaadams** [comment] 2015-12-12 13:36
@kpocza I think it might have been this issue: https://github.com/aspnet/KestrelHttpServer/issues/406

Caused by the `HTTP/1.0`

Try setting [`proxy_http_version 1.1;`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version) ?

**Comment by kpocza** [comment] 2015-12-13 19:56
According to one of the linked issued I've added ```proxy_set_header Connection keep-alive``` as workaround to nginx config and it did the trick for rc1.

**Comment by yaapelsinko** [comment] 2015-12-19 06:00
Hi. I have the same problem. The workaround with `Connection keep-alive` seems to work,

Also I've found something that could be relevant: http://serverfault.com/questions/524878/nginx-as-reverse-proxy-causes-failure-to-respond-to-certain-post-requests

*The problem: ASP.NET development server sends a 100 Continue response even when there was no Expect: 100-continue in the request. Nginx will issue a request with no Expect header; ASP.NET will respond with one, then receive the rest of the request, and then send the actual response. Nginx, however, will only forward the 100 Continue part. It will not forward the actual response; that gets swallowed, at least on nginx 1.4.2.*

With beta8 it all worked well. Also, nginx update 1.4.6 to 1.8.0 didn't help. So it is Kestrel to blame!!! O_O

**Comment by yaapelsinko** [comment] 2015-12-19 06:16
An article: http://www.fallingcanbedeadly.com/posts/http-100-continue-latency-and-you/

I'm too lame in such matters to understand if is it relevant or not.

**Comment by khellang** [comment] 2015-12-19 11:35
> Also I've found something that could be relevant [...] So it is Kestrel to blame!!! O_O

I don't think it's relevant, and definitely not evidence that this is Kestrel's fault. The question was asked in 2013, when there was no Kestrel.

**Comment by muratg** [comment] 2015-12-21 23:07
Please reopen if this is still an issue.

**Comment by ahmad-moussawi** [comment] 2016-02-05 15:12
👍same issue, on ubuntu 14.04 with nginx as proxy
also if am using another proxy like http-proxy-middleware

**Comment by RTodorov** [comment] 2016-02-09 16:50
this is definitely still an issue, I'm facing this using microsoft/aspnet dockerimage behind DEIS, which uses nginx as a proxy/load-balancer

**Comment by muratg** [comment] 2016-02-09 17:05
@cesarbs Could you investigate?

**Comment by cesarbs** [comment] 2016-02-09 18:24
@muratg On it.

@ahmad-moussawi @RTodorov Need some info from you guys:

1) Kestrel/DNX/dotnet version.
2) Reverse proxy settings from your nginx.conf.

**Comment by RTodorov** [comment] 2016-02-09 18:28
Kestrel: 1.0.0-rc1-final
Dnx: 1.0.0-rc1-16231
Dotnet: 1.0.0-rc1-update1

            proxy_buffering             off;
            proxy_set_header            Host my-server;
            proxy_set_header            X-Forwarded-For $remote_addr;
            proxy_redirect              off;
            proxy_connect_timeout       "10s";
            proxy_send_timeout          "20m";
            proxy_read_timeout          "20m";

            proxy_pass                  http://my-kestrel;

my-kestrel being an upstream server

**Comment by cesarbs** [comment] 2016-02-09 18:30
@RTodorov Could you try with the latest packages? Kestrel had known issues in RC1 when being put behind nginx, those have been fixed already.

**Comment by tucaz** [comment] 2016-02-21 02:32
@cesarbs I'm having the same problem as @RTodorov with same versions of everything. What version of Kestrel do you suggest we use? I only could find rc1-final in https://www.nuget.org/packages/Microsoft.AspNet.Server.Kestrel/

Thanks

**Comment by cesarbs** [comment] 2016-02-21 05:39
@tucaz You'd have to use the vnext or cidev feeds to get more recent stuff:

    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />

    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v2" />

Keep in mind though that there have been a number of changes since then and you'll likely have to make a number of adjustments to your code.

A workaround that has worked for some people is to configure your reverse proxy to send a `Connection: keep-alive` header. You might also have to configure it to use HTTP 1.1 if it uses 1.0 by default.

Previous similar issue:

https://github.com/aspnet/KestrelHttpServer/issues/341

**Comment by cesarbs** [comment] 2016-02-24 19:00
Has anyone tried it with the latest packages, or tried the `Connection: keep-alive` to check if that solves the problem?

**Comment by RTodorov** [comment] 2016-02-24 19:15
Connection: keep-alive works fine, didn't test with latest packages though.


Em quarta-feira, 24 de fevereiro de 2016, Cesar Blum Silveira <
notifications@github.com> escreveu:

**Comment by cesarbs** [comment] 2016-02-24 19:44
@RTodorov Alright, will close this then. Completely off-topic: hello fellow Brazilian :smile:

**Closed by cesarbs** 2016-02-24 19:44 UTC

**Comment by tucaz** [comment] 2016-02-25 00:09
I guess we are all Brazilians here :)

@cesarbs keep alive works, however I think I found something else related to this issue. Whenever the first request that goes to Kestrel comes from nginx (even with the keep alive header) Kestrel hangs and don't serve any subsequent requests.

In my case it only works if the first request is performed via curl.

The steps to reproduce are:

1. Put Kestrel behind nginx proxy with connection: keep-alive
2. Start kestrel
3. Issue a request that goes through nginx into Kestrel

I don't know if this makes any difference, but I'm running my asp.net kestrel app also on linux, so both nginx and kestrel are running in the same machine.

**Comment by cesarbs** [comment] 2016-02-25 01:21
Try adding

    proxy_http_version 1.1;

to your nginx config file.

**Comment by tucaz** [comment] 2016-02-25 03:03
It was already there. 

However, I tried to reproduce the error and when starting kestrel I got an `EADDRINUSE` error. When I ran `netstat -an` I saw that for some reason my port (5000) was in a CLOSE_WAIT state.

After killing the process and running kestrel again it worked.

I'm not sure why it didn't work before, but it's working now. I will do some more testing later to see if I can reproduce. If I can, I will come back here or open a new issue so you guys know.

Thanks!

**Comment by muratg** [comment] 2016-02-25 05:00
Thanks @tucaz!

**Comment by grennis** [comment] 2016-03-14 18:19
+1 hit this issue and fixed by proxy_set_header Connection keep-alive

**Comment by rshramko** [comment] 2016-09-09 10:17
+ we also ran into the same issue and fixed by adding actually two headers:

> proxy_http_version 1.1;
> proxy_set_header Connection keep-alive

Thank you guys!
