### ISSUE TITLE
Throughput Regression in Plaintext Libuv

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2338] opened 2018-02-21 01:59 UTC
There is a 10-15% throughput regression in Plaintext Libuv between 2.0.0 and 2.1.0-preview2-30159:

Hardware|KestrelThreadCount|2.0.1|2.1.0-preview2-30159|Delta
-----|-----|-----|-----|-----
Physical|2|1,842,532|1,659,272|-10%
Cloud|Default|517,623|440,627|-15%

We have identified the source commits for two recent regressions:

# Jan 4, 2018
* React to pipeline changes (https://github.com/aspnet/KestrelHttpServer/commit/1fa001e7db3d7eb93d42f7e0ef4c6c114a831d64)

# Jan 29-31, 2018
One or more of the following:
* React to pipelines changes (https://github.com/aspnet/KestrelHttpServer/commit/a84095e5c3a61a329bca5819183de608067d0394)
* Update dependencies (https://github.com/aspnet/KestrelHttpServer/commit/5e6b901a12697945974001c3f1bc69af3ed60273)
* Merge release/2.1 (https://github.com/aspnet/KestrelHttpServer/commit/261b5836c1a876e8fd4ea866e7433d9b5ab106b4)

CC: @sebastienros, @pakrym, @davidfowl

**Comment by davidfowl** [comment] 2018-02-21 07:34
Here are the relevant PRs in pipelines that caused the performance regressions:

https://github.com/dotnet/corefxlab/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Apakrym+merged%3A%3E2017-10-17

**Comment by pakrym** [comment] 2018-02-21 17:11
@davidfowl nice one!
![http://www.reactiongifs.com/r/Tom-Cruise-crazy-laugh.gif](http://www.reactiongifs.com/r/Tom-Cruise-crazy-laugh.gif)

**Comment by davidfowl** [comment] 2018-02-21 17:30
😂

**Comment by mikeharder** [comment] 2018-02-21 18:57
@pakrym: On a serious note, do you have any more information about which changes (or parts of changes) caused the throughput regressions?

**Comment by davidfowl** [comment] 2018-02-21 19:14
The first 2 were the big ones.

- https://github.com/dotnet/corefxlab/pull/1967
- https://github.com/dotnet/corefxlab/pull/1974

**Comment by benaadams** [comment] 2018-02-21 20:09
At a guess 2 issues would be: 

Advance going from inlinable method, to virtual method; which should hopefully be fixed by the introduction of `Commit` to `BufferWriter` née `OutputWriter` https://github.com/dotnet/corefxlab/pull/2113

Other is `ReadOnlySequence` being able to represent multiple objects, and pattern matching on the type; which should hopefully be somewhat addressed by using the flag on the `SequencePosition` to indicate type (not sure which PR that was)

**Comment by tmds** [comment] 2018-03-06 08:19
Maybe part of the regression is due to Meltdown/Spectre fixes?

**Comment by davidfowl** [comment] 2018-03-06 09:25
@tmds nope, it's mostly the pipeline API changes. @benaadams and @pakrym have done some good work to get that back. We're now within 3% without the big changes from CoreFx yet. My assumption is that the next time we grab bits from corefx this will be resolved.

**Comment by muratg** [comment] 2018-03-13 22:09
Closing, as we are satisfied with the current results.

**Closed by muratg** 2018-03-13 22:09 UTC
Labels: perf
