### ISSUE TITLE
System.IO.IOException: Error -104 ECONNRESET connection reset by peer

### ISSUE THREAD

**Issue by radheshchamarti** [aspnet/KestrelHttpServer#2540] opened 2018-05-03 19:04 UTC
I am getting this excpetion in my code

System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -104 ECONNRESET connection reset by peer
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvOutputConsumer.<WriteOutputAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.<Start>d__26.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

**Comment by halter73** [comment] 2018-05-03 23:28
@radheshchamarti Do you see this on every request? This exception should only occur when the client closes the underlying connection mid-request which is generally pretty rare.

**Comment by daveclarke** [comment] 2018-05-07 23:32
Same here, ref: https://github.com/aspnet/KestrelHttpServer/issues/2536. I spent over an hour skyping a MS Network Engineer going over a network trace to try and figure out why we are getting ECONNRESET exceptions in our logs. We are running a number of Docker containers on an Azure VM which together comprise a small microservice system. The Docker base image is `microsoft/aspnetcore:2.0.6`.

The Azure application gateway sends a default health probe request to the web server every 30 seconds. Mostly this works but maybe 20 times a day it fails. Stack trace logged:

	22:33:19 [Information] () "Request starting HTTP/1.1 GET http://127.0.0.1/  "

	22:33:19 [Information] () {"Connection":["Keep-Alive"],"Host":["127.0.0.1"],"Max-Forwards":["10"]}

	22:33:19 [Information] () Executing action method "HonestyBoxWeb.Controllers.HomeController.Index (HonestyBoxWeb)" with arguments (null) - ModelState is Valid

	22:33:19 [Information] () Executing ViewResult, running view at path "/Views/Home/Index.cshtml".

	22:33:19 [Information] () Executed action "HonestyBoxWeb.Controllers.HomeController.Index (HonestyBoxWeb)" in 6.6907ms

	22:33:19 [Information] () "Request finished in 13.7646ms 200 text/html; charset=utf-8"

	22:33:19 [Information] () Connection id ""0HLD3PUA8AP49"" request processing ended abnormally.
	System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -104 ECONNRESET connection reset by peer
	   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvOutputConsumer.<WriteOutputAsync>d__6.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection.<Start>d__26.MoveNext()
	   --- End of inner exception stack trace ---
	   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
	   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
	   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

The network trace does show the health probe sending RST, but it does that each time. The website is not being hit by any other requests when this occurs. It would be helpful to have this resolved - at the moment we're getting these reported effectively as false positives that make it less likely we will identify actual issues when they occur. I have an open ticket with Azure Infrastructure Support REG:118032617886670 but their feedback is basically that it isn't their issue:

> I have had an internal discussion with my Technical advisory of the health probe behavior of Application gateway and we confirmed that it will not use graceful TCP closure to close the session with backend server. It will only use the ACK Reset to close the existing health probe session in a much efficiency way.
>  
> To conclude, the Application gateway will use ACK Reset to close the health probe session and no graceful TCP session close phase will be used by Application gateway. In the latest network trace file you provide on 05/02, we can see totally of 12 Reset packets have been sent to backend server to finish the TCP connection between health probe and server.
> 
> For the ECONNRESET log in your webserver, we do consider it was generated by Kestrel itself instead of Azure Application gateway. Because according to the packet analysis, it should record more logs of ECONNRESET instead of only 1 time in the log file around issue time.
>

**Comment by davidfowl** [comment] 2018-05-14 07:15
@daveclarke are you saying that you get an RST in Kestrel without the client disconnecting? Do you have a repro for that? Sounds like maybe it could be a deeper issue as we're not doing anything special here. If you have something reproducible then we can take a look.

**Comment by daveclarke** [comment] 2018-05-14 07:47
@davidfowl no, the Azure application gateway is sending a health probe request every 30 seconds but is just doing a Reset to close the connection. This happens for every request but Kestrel doesn't log an exception every time, only a couple of dozen are logged per day. Obviously we're not the only ones using Kestrel in Azure but we are generating an email notification when an exception is logged so we're effectively getting false positives. Our clients don't appear to be impacted by this as far as I'm aware. Certainly the 30 second health probes are currently the most active client we have but we hope that will change as our client base grows :-)

**Comment by davidfowl** [comment] 2018-05-14 07:53
Yes, @halter73 and I had a discussion about making it so that all errors due to the connection going away are logged as trace/debug.

**Comment by daveclarke** [comment] 2018-05-14 07:56
Sounds good to me. When might we see it resolved? @halter73 indicated it "didn't hit the escrow bar for 2.1.0".

**Comment by davidfowl** [comment] 2018-05-14 08:50
2.1.0 is pretty much done.

**Comment by halter73** [comment] 2018-05-14 18:09
#2547 should address the noisy logs. I tried to get the change approved for 2.1 a few days before opening that PR, but it didn't meet the bar.

**Comment by halter73** [comment] 2018-05-22 23:40
Fixed by #2547

**Closed by halter73** 2018-05-22 23:40 UTC
Labels: 3 - Done, bug, cost: XS
