### ISSUE TITLE
 Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected

### ISSUE THREAD

**Issue by zuosc** [aspnet/KestrelHttpServer#2658] opened 2018-06-11 03:37 UTC
Error stack：

```
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_getpeername(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.GetPeerIPEndPoint()
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnection..ctor(ListenerContext context, UvStreamHandle socket)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.DispatchConnection(UvStreamHandle socket)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Listener.OnConnection(UvStreamHandle listenSocket, Int32 status)

```

dotnet --info:
```
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

How it works:

It's run with nginx.the nginx conf is:

```
server {
        listen 80;
        server_name tmp.12**56.c**ud;

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://1**.1**.2**.3*:12758/;
    }
}


server {
        # SSL configuration

        listen 443 ssl;
        listen [::]:443 ssl;
        ssl on;

        server_name t*p.12***6.c****d;


        ssl_certificate   /etc/nginx/***/fullchain.pem;
        ssl_certificate_key  /etc/nginx/***/wildcard_123456cloud.pem;
        ssl_session_timeout 5m;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;

        location / {
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   Host      $http_host;
                proxy_pass         http://1**.1**.2**.3*:12758/;
    }

}

```
#Important#

if I deploy the web  on local,then  the nginx conf:[proxy_pass] use  http://127.0.0.1:12758/: ,  everything is ok!

but if i deploy the web on remote server,and  the nginx conf:[proxy_pass] use http://1**.1**.2**.3*:12758/;  it's wrong with 'Error -107 ENOTCONN socket is not connected'

**Comment by Tratcher** [comment] 2018-06-11 15:14
Likely duplicates:
https://github.com/aspnet/KestrelHttpServer/issues/2583
https://github.com/aspnet/KestrelHttpServer/issues/941

**Comment by halter73** [comment] 2018-06-11 19:02
@zuosc If you can, I recommend upgrading the .net runtime and kestrel dependencies to 2.1.0. This issue should be fixed in that release.

**Comment by zuosc** [comment] 2018-06-12 03:04
@halter73    I upgrading the .net runtime and kestrel dependencies to 2.1.0.

```
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.5" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" />
    <PackageReference Include="MySqlConnector" Version="0.42.0" />
    <PackageReference Include="UAParser" Version="3.0.0" />
  </ItemGroup>
```

yes, now it's no UvException log.   

But!，my website is also 502 Bad Gateway error.  so sad。

And 

>if I deploy the web on local, then the Nginx conf:[proxy_pass] use ’http://127.0.0.1:12758/:‘ , everything is ok!

>but if I deploy the web on a remote server, and the Nginx conf:[proxy_pass] use ’http://1**.1**.2**.3*:12758/‘; it's wrong with 'Error -107 ENOTCONN socket is not connected'




Maybe is my Nginx setting or conf have some error？

**Comment by zuosc** [comment] 2018-06-12 03:12
I find some Nginx error log

```
 *27742 upstream prematurely closed connection while reading response header from upstream, client: 1xx.**.1*6.2, server: tmp.1****6.cloud, request: "GET / HTTP/2.0", upstream: "http://1**.1**.2**.36:12758/", host: "tmp.1****6.cl**d"
2018/06/12 10:44:38 [error] 17726#17726: *27742 upstream prematurely closed connection while reading response header from upstream, client: 153.37.196.2, server: tmp.1****6.cl**d, request: "GET /favicon.ico HTTP/2.0", upstream: "http://1**.1**.2**.36:12758/favicon.ico", host: "tmp.1****6.cl**d", referrer: "https://tmp.1****6.cl**d/"
2018/06/12 10:44:39 [error] 17726#17726: *27742 upstream prematurely closed connection while reading response header from upstream, client: 153.37.196.2, server: tmp.1****6.cl**d, request: "GET / HTTP/2.0", upstream: "http://1**.1**.2**.36:12758/", host: "tmp.1****6.cl**d"
2018/06/12 10:44:40 [error] 17726#17726: *27742 upstream prematurely closed connection while reading response header from upstream, client: 153.37.196.2, server: tmp.1****6.cl**d, request: "GET /favicon.ico HTTP/2.0", upstream: "http://1**.1**.2**.36:12758/favicon.ico", host: "tmp.1****6.cl**d", referrer: "https://tmp.1****6.cl**d/"
2018/06/12 10:48:06 [notice] 30013#30013: signal process started
2018/06/12 10:48:12 [error] 30018#30018: *27750 upstream prematurely closed connection while reading response header from upstream, client: 153.37.196.2, server: tmp.1****6.cl**d, request: "GET / HTTP/2.0", upstream: "http://1**.1**.2**.36:12758/", host: "tmp.1****6.cl**d"
2018/06/12 10:48:14 [error] 30018#30018: *27750 upstream prematurely closed connection while reading response header from upstream, client: 153.37.196.2, server: tmp.1****6.cl**d, request: "GET /favicon.ico HTTP/2.0", upstream: "http://1**.1**.2**.36:12758/favicon.ico", host: "tmp.1****6.cl**d", referrer: "https://tmp.1****6.cl**d/"
```



So this looks like a problem with my server network

**Comment by Tratcher** [comment] 2018-06-12 03:16
Do you have 2.1 installed on the remote server?

**Comment by zuosc** [comment] 2018-06-12 03:34
yes   this is dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.200 [/usr/share/dotnet/sdk]
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by muratg** [comment] 2018-07-06 19:47
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by muratg** 2018-07-06 19:47 UTC

**Comment by LightVolk** [comment] 2018-11-12 08:39
@muratg , i have the same issure on dotnet --version 2.1.403.
This problem manifests itself during prolonged operation of the service.
Moreover, the service does not receive requests. The service can work without receiving requests within 5-10 days and only then this error appears.
P.S. The service is used for laboratory work and therefore I use it only.
