### ISSUE TITLE
Default server addresses for kestrel

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1432] opened 2017-03-03 05:21 UTC
Appveyor failed and I see local failures locally as well.

```
[xUnit.net 00:00:05.2370067]     Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6_Success(addressInput: null, testUrls: Func`2 { Method = System.String[] <get_AddressRegistrationDataIPv6>b__25_0(Microsoft.AspNetCore.Hosting.Server.Features.IServerAddressesFeature), Target = <>c { } }) [FAIL]
[xUnit.net 00:00:05.2399215]       System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it
[xUnit.net 00:00:05.2410778]       Stack Trace:
[xUnit.net 00:00:05.2423124]         C:\Users\dfowler\Documents\GitHub\KestrelHttpServer\test\shared\HttpClientSlim.cs(124,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetSocket>d__7.MoveNext()
[xUnit.net 00:00:05.2424405]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:05.2424979]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:05.2425336]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:05.2425636]            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[xUnit.net 00:00:05.2425987]         C:\Users\dfowler\Documents\GitHub\KestrelHttpServer\test\shared\HttpClientSlim.cs(85,0): at Microsoft.AspNetCore.Testing.HttpClientSlim.<GetStream>d__6.MoveNext()
```

/cc @cesarbs

**Comment by JunTaoLuo** [comment] 2017-03-03 07:42
For completeness, these failures were due to https://github.com/aspnet/Hosting/issues/917. The default address of `http://localhost:5000` is no longer added by default by hosting and the default fallback for kestrel was set to only the ipv4 address. 

@davidfowl suggested that we discuss this tomorrow. So let's keep this open.

**Comment by JunTaoLuo** [comment] 2017-03-03 07:48
Nevermind this is a dupe of https://github.com/aspnet/KestrelHttpServer/issues/1434

**Closed by JunTaoLuo** 2017-03-03 07:48 UTC
