### ISSUE TITLE
Exception is missing details

### ISSUE THREAD

**Issue by arcaner** [aspnet/KestrelHttpServer#1082] opened 2016-09-04 02:43 UTC
Received a strange exception that is missing details. Caused the application to become unresponsive (bad gateway). The memory and Cpu usage on this app plan is very low. A simple restart of the web app made the problem go away but I would like to understand what is the cause of this problem.

The process was terminated due to an unhandled exception. Exception Info: Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32) at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint() at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket() at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener+<>c.<StartAsync>b__6_0(System.Object) Exception Info: System.AggregateException at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean) at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken) at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(Microsoft.AspNetCore.Server.Kestrel.ServerAddress) at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1<Context>) at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start() at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost, System.Threading.CancellationToken, System.String) at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost) at ***HIDDEN***.Program.Main(System.String[])

**Comment by GuardRex** [comment] 2016-09-04 14:18
See: https://github.com/aspnet/KestrelHttpServer/issues/1020

**Comment by halter73** [comment] 2016-09-06 23:10
@GuardRex  Yep. This is a dupe of #1020. We will log. The exception does have a message, but it's not shown by the event viewer.

**Closed by halter73** 2016-09-06 23:10 UTC
Labels: duplicate
