### ISSUE TITLE
reallocating new Headers and Streams on Frames is slow

### ISSUE THREAD

**Issue by nathana1** [aspnet/KestrelHttpServer#780] opened 2016-04-28 22:35 UTC
Additionally the existing pooling support doesn't scale well so it is actually slower than not pooling.  Proposal is to add an option to cache the Headers/Streams on the Frame object and remove current pooling scheme.

**Comment by benaadams** [comment] 2016-04-28 22:41
Related: https://github.com/aspnet/KestrelHttpServer/issues/754

**Comment by muratg** [comment] 2016-05-18 19:15
@cesarbs Could you dupe this?

**Comment by cesarbs** [comment] 2016-05-19 22:30
Dupe of #754.

**Closed by cesarbs** 2016-05-19 22:30 UTC
Labels: duplicate, perf
