### ISSUE TITLE
Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/KestrelHttpServer#388] opened 2015-11-15 12:07 UTC
Hello, 

Since the migration using HttpPlatformHandler with KestrelServer, we experience multiple Microsoft.AspNet.Server.Kestrel.Networking.UvException "ECONNRESET". 

I think this is not realy a Kestrel bug because the requests are indeed reset by the client but we wonder if this error could not be silently ignored by Kestrel and/or manualy in the exception handler.

**Comment by halter73** [comment] 2015-11-18 20:36
In RC2, we are changing the UvExceptions to IOExceptions: https://github.com/aspnet/KestrelHttpServer/issues/299

I don't think there are any plans to swallow these exception though.

**Comment by mrgleba** [comment] 2015-11-20 11:13
I'd like to give my +1 for a possibility of somhehow being able to swallow the exception.
We're running Kestrel inside docker and we're logging to console.

As of now most of the logs come from these exceptions and this cutters the log output.

Maybe some new service  that if defined by the user in ConfigureServices can decide whether to swallow or to log.

**Comment by mrgleba** [comment] 2015-11-25 11:19
I think we were able to pinpoint the cause of ECONNRESET.
We were trying to return data for a HEAD request.

We're running behind a nginx proxy. The returned data were never read by nginx,
so the handler got stuck trying to send the data. Finally nginx kiled the connection due to a timeout
which gave us the ECONNRESET.

Maybe Kestrel shoud prohibit or warn when trying sending data to a request that doesn't expect it?
Similarily mabye Kestrel should warn if there is a mismatch between Content-Length and the actual amount of data sent.

**Comment by muratg** [comment] 2015-12-03 18:40
@Tratcher @halter73 Putting this in backlog for now. If you think there's something we can do here please ping me or @glennc

**Comment by tugberkugurlu** [comment] 2016-05-16 13:37
I am also seeing this when I put Kestrel behind HAProxy. The apps run insider docker under rc1-update1 bits:

```
api0      | info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
api0      |       Request starting HTTP/1.1 GET http://localhost/  
api0      | info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
api0      |       Request finished in 0.0001ms 200 text/html
api0      | warn: Microsoft.AspNet.Server.Kestrel[0]
api0      |       Connection shutdown abnormally
api0      |       System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
api0      |         --- End of inner exception stack trace ---
api0      |         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult () [0x00000] in <filename unknown>:0 
api0      |         at Microsoft.AspNet.Server.Kestrel.Http.Frame+<RequestProcessingAsync>d__79.MoveNext () [0x00000] in <filename unknown>:0 
api2      | warn: Microsoft.AspNet.Server.Kestrel[0]
api2      |       Connection processing ended abnormally
api2      |       System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
api2      |         --- End of inner exception stack trace ---
api2      |         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult () [0x00000] in <filename unknown>:0 
api2      |         at Microsoft.AspNet.Server.Kestrel.Http.Frame+<RequestProcessingAsync>d__79.MoveNext () [0x00000] in <filename unknown>:0 
api2      | warn: Microsoft.AspNet.Server.Kestrel[0]
api2      |       Connection shutdown abnormally
api2      |       System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
api2      |         --- End of inner exception stack trace ---
api2      |         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult () [0x00000] in <filename unknown>:0 
api2      |         at Microsoft.AspNet.Server.Kestrel.Http.Frame+<RequestProcessingAsync>d__79.MoveNext () [0x00000] in <filename unknown>:0 
api1      | info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
api1      |       Request starting HTTP/1.1 GET http://localhost/  
api1      | info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
api1      |       Request finished in 0ms 200 text/html
api1      | warn: Microsoft.AspNet.Server.Kestrel[0]
api1      |       Connection processing ended abnormally
api1      |       System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
api1      |         --- End of inner exception stack trace ---
api1      |         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult () [0x00000] in <filename unknown>:0 
api1      |         at Microsoft.AspNet.Server.Kestrel.Http.Frame+<RequestProcessingAsync>d__79.MoveNext () [0x00000] in <filename unknown>:0 
api1      | warn: Microsoft.AspNet.Server.Kestrel[0]
api1      |       Connection shutdown abnormally
api1      |       System.IO.IOException: Error -104 ECONNRESET connection reset by peer ---> Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -104 ECONNRESET connection reset by peer
api1      |         --- End of inner exception stack trace ---
api1      |         at Microsoft.AspNet.Server.Kestrel.Http.SocketInput.GetResult () [0x00000] in <filename unknown>:0 
api1      |         at Microsoft.AspNet.Server.Kestrel.Http.Frame+<RequestProcessingAsync>d__79.MoveNext () [0x00000] in <filename unknown>:0 
```

[This is my HAProxy config](https://github.com/tugberkugurlu/AspNetCoreSamples/blob/62928971ec5b10f22f31f19589610cf266efc40a/haproxy-zero-downtime-sample/haproxy.cfg), [this is the sample](https://github.com/tugberkugurlu/AspNetCoreSamples/tree/62928971ec5b10f22f31f19589610cf266efc40a/haproxy-zero-downtime-sample). To repro, run `docker-compose up` under [this path](https://github.com/tugberkugurlu/AspNetCoreSamples/tree/62928971ec5b10f22f31f19589610cf266efc40a/haproxy-zero-downtime-sample).

Any idea why I am getting these errors?

**Comment by tugberkugurlu** [comment] 2016-05-16 13:38
^^ @Tratcher @halter73 @muratg

**Comment by halter73** [comment] 2016-05-16 18:11
@tugberkugurlu  Has this had any discernible impact on or application, or are you simply asking why these warnings are showing up in your logs.

On Linux, a -104 read status is an ECONNRESET instead of -4077 like on Windows (#649). Until a recent commit, we didn't properly identify the ECONNRESET on Linux and OS X. Since an ECONNRESET is not a truly exceptional case, it shouldn't lead to an IOException unless it results in a corrupted request. This already works appropriately on Windows, and this should be fixed for Linux and OS X for 1.0.0 RTM. Unfortunately it doesn't seem like the fix made it into RC2.

**Comment by tugberkugurlu** [comment] 2016-05-16 18:57
App seems to be working fine but it logs warning messages like those which clutters the log destinations, especially the console.

Any workarounds that I can apply and any other issue that this is being tracked so that I can follow?

**Comment by gdoron** [comment] 2016-07-13 11:33
@tugberkugurlu I guess you can filter by eventId and source, can't you?

**Comment by muratg** [comment] 2016-07-25 20:02
Loglevel is no longer warn, but info.

**Closed by muratg** 2016-07-25 20:02 UTC
