### ISSUE TITLE
unable to run kestrel on mono/linux

### ISSUE THREAD

**Issue by w41dev** [aspnet/KestrelHttpServer#86] opened 2015-03-26 13:00 UTC
I try to run kestrel with the aspnet/Home sample (kpm build runs without errors). When i try to run k kestrel i got the following error : 
```
dev@DebianDev:~/src/Home/samples/HelloMvc$ k kestrel
Mono: DllImport unable to load library 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport unable to load library 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Microsoft.AspNet.Server.Kestrel.Networking.PlatformApis/LinuxApis.dlopen (string,int) <0xffffffff>
  at Microsoft.AspNet.Server.Kestrel.Networking.PlatformApis/LinuxApis.LoadLibrary (string) <0x0001b>
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Load (string) <0x0002e>
  at Microsoft.AspNet.Server.Kestrel.KestrelEngine..ctor (Microsoft.Framework.Runtime.ILibraryManager) <0x0038f>
  at Kestrel.ServerFactory.Start (Microsoft.AspNet.Builder.IServerInformation,System.Func`2<object, System.Threading.Tasks.Task>) <0x0011f>
  at Microsoft.AspNet.Hosting.HostingEngine.Start (Microsoft.AspNet.Hosting.HostingContext) <0x001d4>
  at Microsoft.AspNet.Hosting.Program.Main (string[]) <0x00312>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x000af>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00046>
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly,string[],System.IServiceProvider) <0x000f7>
  at Microsoft.Framework.ApplicationHost.Program.ExecuteMain (Microsoft.Framework.Runtime.DefaultHost,string,string[]) <0x001eb>
  at Microsoft.Framework.ApplicationHost.Program.Main (string[]) <0x0035b>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x000af>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00046>
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly,string[],System.IServiceProvider) <0x000f7>
  at kre.host.Bootstrapper.Main (string[]) <0x002c3>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x000af>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00046>
  at kre.hosting.RuntimeBootstrapper.ExecuteAsync (string[]) <0x0139f>
  at kre.hosting.RuntimeBootstrapper.Execute (string[]) <0x0004b>
  at EntryPoint.Main (string[]) <0x00143>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

        mono(mono_handle_native_sigsegv+0xf3) [0x811b9b3]
        mono(mono_arch_handle_altstack_exception+0xb4) [0x8167054]
        mono(mono_sigsegv_signal_handler+0x107) [0x8096627]
        [0xb779940c]
        /lib/ld-linux.so.2(+0xe9f6) [0xb77a89f6]
        /lib/ld-linux.so.2(+0x11ba8) [0xb77abba8]
        /usr/lib/i386-linux-gnu/libdl.so(+0xc2b) [0xb4ab4c2b]
        /lib/ld-linux.so.2(+0xdde6) [0xb77a7de6]
        /usr/lib/i386-linux-gnu/libdl.so(+0x10bc) [0xb4ab50bc]
        /usr/lib/i386-linux-gnu/libdl.so(dlopen+0x41) [0xb4ab4b61]
        [0xb4996a74]
        [0xb49969fc]
        [0xb499666f]
        [0xb4995d78]
        [0xb4995740]
        [0xb5272275]
        [0xb562bc5b]
        [0xb562b8ed]
        mono() [0x8096101]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Abgebrochen
```
Mono Verison is 4.1.0, libuv Version is v1.0.0-rc2

**Comment by davidfowl** [comment] 2015-03-26 15:53
What version of kestrel?

**Comment by w41dev** [comment] 2015-03-27 08:50
Version of kestrel is 1.0.0-beta3
I am using the "stable" (KVM) version of the k tooling. The project.json is unchanged as i using the Home sample : https://raw.githubusercontent.com/aspnet/Home/master/samples/HelloMvc/project.json

**Comment by w41dev** [comment] 2015-03-31 09:44
Here is the whole mono output with MONO_LOG_LEVEL="debug" / MONO_LOG_MASK="dll"

```
Mono: DllImport attempting to load: 'api-ms-win-core-file-l1-2-0.dll'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll': 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll.so': 'libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'api-ms-win-core-file-l1-2-0.dll': 'api-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.so': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0': 'libapi-ms-win-core-file-l1-2-0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.so': 'libapi-ms-win-core-file-l1-2-0.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'api-ms-win-core-file-l1-2-0': 'api-ms-win-core-file-l1-2-0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll': 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll.so': 'libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll': 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport unable to load library 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport attempting to load: '__Internal'.
Mono: DllImport loaded library '(null)'.
Mono: DllImport searching in: '__Internal' ('(null)').
Mono: Searching for 'ReadFile'.
Mono: DllImport attempting to load: 'api-ms-win-core-file-l1-2-0.dll'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll': 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll.so': 'libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'api-ms-win-core-file-l1-2-0.dll': 'api-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.so': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0': 'libapi-ms-win-core-file-l1-2-0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.so': 'libapi-ms-win-core-file-l1-2-0.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'api-ms-win-core-file-l1-2-0': 'api-ms-win-core-file-l1-2-0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so': '/home/dev/.k/runtimes/kre-mono.1.0.0-beta3/bin/libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll': 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll.so': 'libapi-ms-win-core-file-l1-2-0.dll.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libapi-ms-win-core-file-l1-2-0.dll': 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport unable to load library 'libapi-ms-win-core-file-l1-2-0.dll: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport searching in: '__Internal' ('(null)').
Mono: Searching for 'ReadFile'.
Mono: DllImport attempting to load: '__Internal'.
Mono: DllImport loaded library '(null)'.
Mono: DllImport searching in: '__Internal' ('(null)').
Mono: Searching for 'GetProcAddress'.
Mono: Probing 'GetProcAddress'.
Mono: Could not find 'GetProcAddress' due to 'mono: undefined symbol: GetProcAddress'.
Mono: Probing 'GetProcAddress'.
Mono: Could not find 'GetProcAddress' due to 'mono: undefined symbol: GetProcAddress'.
Mono: Probing 'GetProcAddressA'.
Mono: Could not find 'GetProcAddressA' due to 'mono: undefined symbol: GetProcAddressA'.
Mono: Probing 'GetProcAddressA'.
Mono: Could not find 'GetProcAddressA' due to 'mono: undefined symbol: GetProcAddressA'.
Mono: DllImport searching in: '__Internal' ('(null)').
Mono: Searching for 'LoadLibraryExW'.
Mono: Probing 'LoadLibraryExW'.
Mono: Could not find 'LoadLibraryExW' due to 'mono: undefined symbol: LoadLibraryExW'.
Mono: Probing 'LoadLibraryExW'.
Mono: Could not find 'LoadLibraryExW' due to 'mono: undefined symbol: LoadLibraryExW'.
Mono: Probing 'LoadLibraryExWA'.
Mono: Could not find 'LoadLibraryExWA' due to 'mono: undefined symbol: LoadLibraryExWA'.
Mono: Probing 'LoadLibraryExWA'.
Mono: Could not find 'LoadLibraryExWA' due to 'mono: undefined symbol: LoadLibraryExWA'.
Mono: DllImport searching in: '__Internal' ('(null)').
Mono: Searching for 'LoadLibraryExW'.
Mono: Probing 'LoadLibraryExW'.
Mono: Could not find 'LoadLibraryExW' due to 'mono: undefined symbol: LoadLibraryExW'.
Mono: Probing 'LoadLibraryExW'.
Mono: Could not find 'LoadLibraryExW' due to 'mono: undefined symbol: LoadLibraryExW'.
Mono: Probing 'LoadLibraryExWA'.
Mono: Could not find 'LoadLibraryExWA' due to 'mono: undefined symbol: LoadLibraryExWA'.
Mono: Probing 'LoadLibraryExWA'.
Mono: Could not find 'LoadLibraryExWA' due to 'mono: undefined symbol: LoadLibraryExWA'.
Mono: DllImport attempting to load: 'libc.so.6'.
Mono: DllImport error loading library '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libc.so.6': '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libc.so.6: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libc.so.6.so': '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libc.so.6.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport loaded library 'libc.so.6'.
Mono: DllImport searching in: 'libc.so.6' ('libc.so.6').
Mono: Searching for 'uname'.
Mono: Probing 'uname'.
Mono: Found as 'uname'.
Mono: DllImport attempting to load: 'libdl'.
Mono: DllImport error loading library '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libdl': '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libdl: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libdl.so': '/home/dev/.k/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta3/lib/aspnet50/libdl.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport error loading library 'libdl': 'libdl: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden'.
Mono: DllImport loaded library 'libdl.so'.
Mono: DllImport searching in: 'libdl' ('libdl.so').
Mono: Searching for 'dlopen'.
Mono: Probing 'dlopen'.
Mono: Found as 'dlopen'.
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Microsoft.AspNet.Server.Kestrel.Networking.PlatformApis/LinuxApis.dlopen (string,int) <0xffffffff>
  at Microsoft.AspNet.Server.Kestrel.Networking.PlatformApis/LinuxApis.LoadLibrary (string) <0x0001b>
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Load (string) <0x0002e>
  at Microsoft.AspNet.Server.Kestrel.KestrelEngine..ctor (Microsoft.Framework.Runtime.ILibraryManager) <0x0038f>
  at Kestrel.ServerFactory.Start (Microsoft.AspNet.Builder.IServerInformation,System.Func`2<object, System.Threading.Tasks.Task>) <0x0011f>
  at Microsoft.AspNet.Hosting.HostingEngine.Start (Microsoft.AspNet.Hosting.HostingContext) <0x001d4>
  at Microsoft.AspNet.Hosting.Program.Main (string[]) <0x00312>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x000af>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00046>
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly,string[],System.IServiceProvider) <0x000f7>
  at Microsoft.Framework.ApplicationHost.Program.ExecuteMain (Microsoft.Framework.Runtime.DefaultHost,string,string[]) <0x001eb>
  at Microsoft.Framework.ApplicationHost.Program.Main (string[]) <0x0035b>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x000af>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00046>
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly,string[],System.IServiceProvider) <0x000f7>
  at kre.host.Bootstrapper.Main (string[]) <0x002c3>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x000af>
  at System.Reflection.MethodBase.Invoke (object,object[]) <0x00046>
  at kre.hosting.RuntimeBootstrapper.ExecuteAsync (string[]) <0x0139f>
  at kre.hosting.RuntimeBootstrapper.Execute (string[]) <0x0004b>
  at EntryPoint.Main (string[]) <0x00143>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

        mono(mono_handle_native_sigsegv+0xf3) [0x811b9b3]
        mono(mono_arch_handle_altstack_exception+0xb4) [0x8167054]
        mono(mono_sigsegv_signal_handler+0x107) [0x8096627]
        [0xb777b40c]
        /lib/ld-linux.so.2(+0xe9f6) [0xb778a9f6]
        /lib/ld-linux.so.2(+0x11ba8) [0xb778dba8]
        /usr/lib/i386-linux-gnu/libdl.so(+0xc2b) [0xb45f9c2b]
        /lib/ld-linux.so.2(+0xdde6) [0xb7789de6]
        /usr/lib/i386-linux-gnu/libdl.so(+0x10bc) [0xb45fa0bc]
        /usr/lib/i386-linux-gnu/libdl.so(dlopen+0x41) [0xb45f9b61]
        [0xb462caac]
        [0xb462ca34]
        [0xb462c6a7]
        [0xb462bfe0]
        [0xb462b9a8]
        [0xb4be0275]
        [0xb4e01c5b]
        [0xb4e018ed]
        mono() [0x8096101]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Abgebrochen
```

**Comment by davidfowl** [comment] 2015-03-31 10:07
Seems like OS detection is broken on debian.

**Comment by Tratcher** [comment] 2015-04-06 22:59
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/78

**Closed** 2015-04-13 05:08 UTC
