### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException and  Error -4047 EPIPE broken pipe

### ISSUE THREAD

**Issue by Damon227** [aspnet/KestrelHttpServer#1407] opened 2017-02-28 06:16 UTC
Exception message:

fail: Microsoft.AspNetCore.Server.Kestrel [0]
      TcpListenerPrimary.OnConnection
        Inner Exception(s) Found:
        Type: Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException
        Message: Error -4047 EPIPE broken pipe
        Source: Microsoft.AspNetCore.Server.Kestrel
        DataJson: {"$id":"1"}
        Stacktrace:
         at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
         at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvWriteReq.Write2(UvStreamHandle handle, ArraySegment`1 bufs, UvStreamHandle sendHandle, Action`4 callback, Object state)
         at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.DispatchConnection(UvStreamHandle socket)
         at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.OnConnection(UvStreamHandle listenSocket, Int32 status)

**Comment by Damon227** [comment] 2017-02-28 06:24
I have a asp.net core web app in azure, but sometimes the httprequest will be locked and return 502, and the exception is Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException. My app's dll is 1.1.0.
 "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
so who can give me some advicees?

**Comment by halter73** [comment] 2017-02-28 06:27
This looks like a dupe of https://github.com/aspnet/KestrelHttpServer/issues/1182 which should be fixed in 1.1.0. Can you post your project.lock.json in a gist?

**Comment by Damon227** [comment] 2017-02-28 07:04
@halter73 <script src="https://gist.github.com/Damon227/91c0cd5ba2af2fc72d475e7e83a4f7cb.js"></script>

**Comment by Damon227** [comment] 2017-02-28 07:05
@halter73 Hi ! There is the project.lock.json. https://gist.github.com/Damon227/91c0cd5ba2af2fc72d475e7e83a4f7cb

**Comment by halter73** [comment] 2017-02-28 08:04
Looking at your project.lock.json, it looks like you you upgraded an app that started using AspNetCore 1.0.0 packages to use 1.1.0 packages. Since this looks so similar to a bug that was fixed in 1.0.0, could you triple check that Web App you have published in Azure is really using the 1.1.0 Kestrel dll?

One easy way to do this is to go to "https://{yoursite}*.scm*.azurewebsites.net" and navigating to D:\home\site\wwwroot in the "Debug console > PowerShell" tab. In the powershell prompt, if you enter

```
(ls D:\home\site\wwwroot\Microsoft.AspNetCore.Server.Kestrel.dll).VersionInfo
```

What output do you get?

**Comment by Damon227** [comment] 2017-02-28 08:14
@halter73 Hi，I get this information fromn Kudu Debug console. 

PS D:\home\site\wwwroot> (ls D:\home\site\wwwroot\Microsoft.AspNetCore.Server.Kestrel.dll).VersionInfo

ProductVersion   FileVersion      FileName                                     
--------------   -----------      --------                                     
1.1.0-rtm-22752  1.1.0.21115      D:\home\site\wwwroot\Microsoft.AspNetCore....

So my app should be using the 1.1.0 Kestrel DLL.  And i alse set Kestrel thread count = 1 at Program.cs in app.

**Comment by halter73** [comment] 2017-02-28 18:10
Do you still see the error when you set the thread count to 1?

**Comment by muratg** [comment] 2017-03-20 19:31
*ping* @Damon227...

**Closed** 2017-04-07 19:39 UTC
