### ISSUE TITLE
Graceful shutdown regression

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1547] opened 2017-03-24 05:34 UTC
This issue is currently being obscured by https://github.com/aspnet/Logging/issues/563, but here are the logs from Kestrel's sample app after Chrome opens two requests to http://localhost:5000. This is reproducible with and without connection adapters:

```
KestrelHttpServer\samples\SampleApp [dev ≡ +0 ~2 -0 !]> dotnet bin\Release\netcoreapp1.1\SampleApp.dll
Hosting environment: Production
Content root path: C:\Users\shalter\dev\misc\KestrelHttpServer\samples\SampleApp
Now listening on: http://127.0.0.1:5000
Now listening on: http://127.0.0.1:5001
Application started. Press Ctrl+C to shut down.
Connection id "0HL3IEM4MV4OC" started.
Connection id "0HL3IEM4MV4OC" completed keep alive response.
Connection id "0HL3IEM4MV4OC" completed keep alive response.
Connection id "0HL3IEM4MV4OD" started.
Application is shutting down...
Connection id "0HL3IEM4MV4OD" disconnecting.
Connection id "0HL3IEM4MV4OC" disconnecting.
Some connections failed to close gracefully during server shutdown.
Some connections failed to close gracefully during server shutdown.
Some connections failed to abort during server shutdown.
Some connections failed to abort during server shutdown.
Disposing write requests failed
Disposing write requests failed
KestrelThread.StopAsync failed to terminate libuv thread.
KestrelThread.StopAsync failed to terminate libuv thread.
```

If I had to guess, I would say this was likely regressed by https://github.com/aspnet/KestrelHttpServer/pull/1497, but the parent commit no longer builds due to corefx(lab) changes.

You can see the logs during dispose using my [halter73/1547](https://github.com/aspnet/KestrelHttpServer/compare/halter73/1547) branch.

**Comment by davidfowl** [comment] 2017-03-24 05:38
@halter73 are you going to fix this as part of your changes or do you want me to look at it?

**Comment by halter73** [comment] 2017-03-24 05:45
I don't have the fix. I'm currently tying to stay focused on not regressing the current behavior.

I think this could fixed after my changes are merged, but by all means feel free to look at it.

**Comment by davidfowl** [comment] 2017-03-24 05:50
I'll take a look.

**Comment by davidfowl** [comment] 2017-03-24 07:15
Logging is the reason things are busted. Here's what happening:

- The browser connects
- User runs Ctrl + C
- We start the shutdown sequence by looping over all connections and calling `StopAsync()` https://github.com/aspnet/KestrelHttpServer/blob/3e6303b6c15c571a0eca618042add2f246fe1ead/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Connection.cs#L124
- That cancelling the frame's reading loop by calling `CancelPendingRead()`.
- Frame unwinds successfully and in the finally block tries to end the connection via `IConnectionControl.End(ProduceEndType.SocketShutdown)` https://github.com/aspnet/KestrelHttpServer/blob/3e6303b6c15c571a0eca618042add2f246fe1ead/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameOfT.cs#L215
- The catch block within the finally block in FrameOfT runs https://github.com/aspnet/KestrelHttpServer/blob/3e6303b6c15c571a0eca618042add2f246fe1ead/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameOfT.cs#L220
- The frame task is marked as completed successfully but the _socketClosedTcs is never completed. https://github.com/aspnet/KestrelHttpServer/blob/3e6303b6c15c571a0eca618042add2f246fe1ead/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Connection.cs#L124

**Comment by halter73** [comment] 2017-03-24 07:51
Logging is definitely messing things up, but why does the halter73/1547 branch still fail when it's using a "fake" logger?

**Comment by davidfowl** [comment] 2017-03-24 07:53
I didn't try your branch. Will take a look.

**Comment by davidfowl** [comment] 2017-03-24 08:05
Tried your branch, seems like an issue with pipes. `CancelPendingRead()` isn't yielding the read async in `SocketOutput`. I'm guessing https://github.com/dotnet/corefxlab/pull/1332/files likely fixes it, what's the status of this change @pakrym?

**Comment by davidfowl** [comment] 2017-03-24 08:21
@halter73 guess what the problem is 😄 . Like *all* problems of this class, *something* is blocking the libuv thread thus the socket output callback never gets scheduled. In particular https://github.com/aspnet/KestrelHttpServer/blob/3e6303b6c15c571a0eca618042add2f246fe1ead/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/ConnectionManager.cs#L67, since we're using the configured thread pool here we don't get the desired affect which is the get *off* the libuv thread. 

It's been a regression since we added thread pool dispatching. It happens in the sample because it turns it on.

**Comment by davidfowl** [comment] 2017-03-24 08:27
The right fix is to avoid using the `IThreadPool` in the `ConnectionManager` and directly use `Task.Run` or `TP.QUWI`

**Comment by halter73** [comment] 2017-03-24 08:41
Lol. I forgot that we had disabled thread pool dispatching in this sample. I already changed ConnectionManager to use Task.Run() for other reasons in my branch. Same for KestrelThread.DoPostWork().

**Comment by davidfowl** [comment] 2017-03-24 08:43
😄  I'll close this bug

**Closed by davidfowl** 2017-03-24 08:43 UTC
