### ISSUE TITLE
Validate certificate EKU

### ISSUE THREAD

**Issue by danroth27** [aspnet/KestrelHttpServer#1764] opened 2017-04-25 18:29 UTC
When setting up SSL with Kestrel if the cert has an EKU we should validate that the cert is for server usage.

**Comment by muratg** [comment] 2017-06-23 19:36
@blowdart your thoughts on this one?  (OK to do in 2.1?)

**Comment by blowdart** [comment] 2017-06-23 19:38
No, as we patched full framework to check for this last month. It needs to be right on the server too.

**Comment by natemcmaster** [comment] 2017-07-06 23:40
@muratg @halter73  I might be able to poach this one if we still want to get it in for 2.0.0

**Comment by muratg** [comment] 2017-07-07 00:41
Thanks @natemcmaster! If we can't get to it, it's probably OK.

**Comment by davidfowl** [comment] 2017-07-07 00:44
Is this really important for 2.0? Wasn't this for the identity service scenario?

**Comment by danroth27** [comment] 2017-07-07 04:46
@davidfowl This was requested by @blowdart and applies to HTTPS with Kestrel independent of the identity as a service work.

**Comment by blowdart** [comment] 2017-07-07 11:55
It's very separate. 

Both Core and Framework now check the EKUs of the servers they're attaching to. So if you bind an invalid certificate then HttpClient et al will refuse to connect. This check on startup ensures that you're not using a certificate that isn't meant to be for a server, and so warns you a lot earlier than waiting for an HttpClient to attach.

It's a nice to have, but it's very very very nice, because it'll make things easier to diagnose.

**Comment by davidfowl** [comment] 2017-07-07 13:05
I think it should be moved to 2.1 but if @natemcmaster can do it and it's low risk (has a low chance of regressions on all 3 OSes) then sure.

**Comment by natemcmaster** [comment] 2017-07-07 16:12
The check is actually fairly simple. The hardest part of doing this was figuring out how to make a test cert with an EKU extension. I have a PR open to implement EKU validation here: https://github.com/aspnet/KestrelHttpServer/pull/1940.

**Comment by muratg** [comment] 2017-07-07 17:10
@halter73 / @davidfowl could you review the PR?  

@natemcmaster if this is risky, let's move it out to 2.1.

**Comment by natemcmaster** [comment] 2017-07-07 19:36
In #1940, we added validation of the Extended Key Usage extension. In https://github.com/aspnet/KestrelHttpServer/pull/1944, I'm adding the validation for the normal Key Usage extension as well. According to the RFC, validation of these extensions is an orthogonal concern so we don't need both, however, it seems best to be consistent and check both types of key usage extensions.

**Comment by natemcmaster** [comment] 2017-07-07 21:22
Talked with @blowdart in person. We can address the Key Usage extension separately, and do that post 2.1. Closing this as resolved with changes in #1940. I've opened https://github.com/aspnet/KestrelHttpServer/issues/1946 to address this.

**Closed by natemcmaster** 2017-07-07 21:22 UTC
Labels: 2 - Working, enhancement
