### ISSUE TITLE
Test failure: UpgradedConnectionsCountsAgainstDifferentLimit

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2776] opened 2018-08-06 11:00 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=524221&buildTypeId=Releases_21Public_UbuntuUniverse) occasionally with the following error:
```
System.IO.IOException : Expected connection close, received data instead: "HTTP/1.1 200 OK
Date: Mon, 06 Aug 2018 10:40:42 GMT
Content-Length: 0
"
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ConnectionLimitTests.UpgradedConnectionsCountsAgainstDifferentLimit() in /_/test/Kestrel.FunctionalTests/ConnectionLimitTests.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-06 11:00
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-07 11:00
UpgradedConnectionsCountsAgainstDifferentLimit [failed with about the same error](http://aspnetci/viewLog.html?buildId=525020&buildTypeId=Releases_21Public_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-08-15 21:01
UpgradedConnectionsCountsAgainstDifferentLimit [failed with about the same error](http://aspnetci/viewLog.html?buildId=531843&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-28 18:01
UpgradedConnectionsCountsAgainstDifferentLimit [failed with about the same error](http://aspnetci/viewLog.html?buildId=540783&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment] 2018-08-28 18:11
@halter73 @Tratcher

**Comment by halter73** [comment] 2018-08-28 18:27
Here are the server logs for the most recent test failure:

```
2018-08-28 17:33:04.613 +00:00 [TestLifetime] [Information] Starting test "UpgradedConnectionsCountsAgainstDifferentLimit"
2018-08-28 17:33:04.669 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Hosting starting
2018-08-28 17:33:04.700 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Hosting started
2018-08-28 17:33:04.700 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Loaded hosting startup assembly "Libuv.FunctionalTests, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
2018-08-28 17:33:04.768 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLGD1H7PT043"" started.
2018-08-28 17:33:05.482 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
2018-08-28 17:33:05.757 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLGD1H7PT04O"" started.
2018-08-28 17:33:05.758 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLGD1H7PT04O"" received FIN.
2018-08-28 17:33:05.758 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
2018-08-28 17:33:05.758 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLGD1H7PT04O"" disconnecting.
2018-08-28 17:33:05.759 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLGD1H7PT04O"" sending FIN.
2018-08-28 17:33:05.759 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request finished in 0.5998ms 0 
2018-08-28 17:33:05.759 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLGD1H7PT04O"" stopped.
2018-08-28 17:34:05.761 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Hosting shutdown
2018-08-28 17:34:05.761 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLGD1H7PT043"" received FIN.
2018-08-28 17:34:05.761 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLGD1H7PT043"" disconnecting.
2018-08-28 17:34:05.762 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLGD1H7PT043"" sending FIN.
2018-08-28 17:34:05.777 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request finished in 60294.9489ms 101 
2018-08-28 17:34:05.777 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLGD1H7PT043"" stopped.
```

The two surprising things are:

1. A FIN was received 1 minute before the test completed, but the test is only supposed to close the the connection (and send a FIN) at the end of the test.
2. Libuv reported only two connections being started instead of the expected 3.

Here are the server logs for the previous failure:

```
2018-08-15 20:13:26.062 +00:00 [TestLifetime] [Information] Starting test "UpgradedConnectionsCountsAgainstDifferentLimit"
2018-08-15 20:13:26.238 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Hosting starting
2018-08-15 20:13:26.524 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Hosting started
2018-08-15 20:13:26.525 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Loaded hosting startup assembly "Libuv.FunctionalTests, Version=2.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
2018-08-15 20:13:26.683 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQFL"" started.
2018-08-15 20:13:27.649 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
2018-08-15 20:13:28.193 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGG"" started.
2018-08-15 20:13:28.194 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
2018-08-15 20:13:28.194 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGG"" completed keep alive response.
2018-08-15 20:13:28.194 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request finished in 0.7016ms 200 
2018-08-15 20:13:28.211 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLG2TE7MJQGG"" received FIN.
2018-08-15 20:13:28.212 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGG"" disconnecting.
2018-08-15 20:13:28.212 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLG2TE7MJQGG"" sending FIN.
2018-08-15 20:13:28.218 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGG"" stopped.
2018-08-15 20:13:28.249 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGH"" started.
2018-08-15 20:13:28.251 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request starting HTTP/1.1 GET http:///  
2018-08-15 20:13:28.251 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGH"" completed keep alive response.
2018-08-15 20:13:28.252 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request finished in 1.2372ms 200 
2018-08-15 20:13:28.258 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLG2TE7MJQGH"" received FIN.
2018-08-15 20:13:28.259 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGH"" disconnecting.
2018-08-15 20:13:28.259 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLG2TE7MJQGH"" sending FIN.
2018-08-15 20:13:28.260 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Debug] Hosting shutdown
2018-08-15 20:13:28.260 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLG2TE7MJQFL"" received FIN.
2018-08-15 20:13:28.260 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQFL"" disconnecting.
2018-08-15 20:13:28.260 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQGH"" stopped.
2018-08-15 20:13:28.261 +00:00 [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id ""0HLG2TE7MJQFL"" sending FIN.
2018-08-15 20:13:28.354 +00:00 [Microsoft.AspNetCore.Hosting.Internal.WebHost] [Information] Request finished in 702.7512ms 101 
2018-08-15 20:13:28.356 +00:00 [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id ""0HLG2TE7MJQFL"" stopped.
```

Here three connection are started as expected, but there's still a premature FIN that gets received which is enough to fail the test. Both of these failures occurred with the libuv transport on Ubuntu.

@muratg I could change this into an in-memory test. I'm confident this would eliminate the flakiness at the cost of some functional transport coverage. The thing is that this is a pretty infrequent repro to begin with and would likely require network tracing or extra tracing in the native libuv library layer to investigate further.

**Comment by muratg** [comment] 2018-08-28 21:13
@halter73 is that premature FIN a concern though? Is it somehow due to how the tests are structured/executed?

**Comment by halter73** [comment] 2018-08-28 22:44
I don't why there's a premature FIN. It's possible that it's a client bug, but it would be a concern if the transport was reporting this when it wasn't happened. I can't think of any reason why our test infrastructure would cause this.

**Comment by aspnet-hello** [comment] 2018-08-29 00:01
UpgradedConnectionsCountsAgainstDifferentLimit [failed with about the same error](http://aspnetci/viewLog.html?buildId=541223&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment] 2018-08-29 01:18
@halter73 I'm fine with moving this to an in-memory test. I'm assuming we're getting enough transport coverage elsewhere.

**Comment by halter73** [comment] 2018-08-29 19:38
Aside from the ConnectionLimitTests, we don't have much transport coverage for establishing multiple concurrent connections  (or even just multiple connections at all) to a single server instance.

There's nothing about this test that logically makes it more flaky than the other ConnectionLimitTests, so if we were to make this particular test in-memory only, we should probably make all the ConnectionLimitTests in-memory only at which point we'd be losing a lot of coverage. Pretty much all the ConnectionLimitTests have a [history of flakiness](https://github.com/aspnet/KestrelHttpServer/search?q=ConnectionLimitTests&type=Issues), so in a way it would be nice, but it also makes me a little nervous that we wouldn't notice a major regression.

**Comment by ryanbrandenburg** [comment] 2018-09-06 00:00
@muratg was there a decision on what to do here?

**Comment by halter73** [comment] 2018-09-06 19:38
The decision is to create/leave at least one test that ensures multiple concurrent connections work with each real transport, but move the ConnectionLimitTests to InMemory.

**Comment by muratg** [comment] 2018-09-06 19:59
IIRC, @halter73 thought moving this class of tests to be  in-memory to reduce flakiness considerably. And create a separate test to cover multiple concurrent connections for actual transport.

**Comment by halter73** [comment] 2018-09-06 22:26
One thing I notice now is that this is in the 2.1 branch meaning that we need to backport the entire creation of the InMemory functional test project first. This might help make even more tests more reliable, but it makes this overall a much larger work item.

**Comment by halter73** [comment] 2018-09-12 19:10
Trying to backport the introduction of the entire in-memory functional test project introduced too much flakiness. If we see UpgradedConnectionsCountsAgainstDifferentLimit/ConnectionLimitTests fail again, we can look at moving it into the unit test project and use the in-memory test server for specifically this test class.

**Comment by aspnet-hello** [comment] 2018-10-17 19:01
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=579562&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 10:45:48 AM:
- UpgradedConnectionsCountsAgainstDifferentLimit

**Closed** 2018-12-11 22:55 UTC
Labels: Branch:2.1, Flaky, test-failure
