### ISSUE TITLE
Broken tests: RegisterAddresses_HostName_Success et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2739] opened 2018-07-19 22:44 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=509500&buildTypeId=XPlat_HighSierraOsxUniverse) every time with on of the following errors:
```
System.Net.Sockets.SocketException : Device not configured
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 190
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RegisterAddresses_HostName_Success at 2018-07-19T04:58:28
| [0.010s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.018s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.018s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.054s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.059s] TestLifetime Information: Finished test RegisterAddresses_HostName_Success in 0.057792s
```
[or](http://aspnetci/viewLog.html?buildId=509842&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId-64104852415917104)
```
======= Failed test run #1 ==========
System.Net.Sockets.SocketException : Connection refused
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 190
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RegisterAddresses_HostName_Success at 2018-07-19T19:19:11
| [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.016s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.017s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.022s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.026s] TestLifetime Information: Finished test RegisterAddresses_HostName_Success in 0.024921s
======= Failed test run #2 ==========
System.Net.Sockets.SocketException : Connection refused
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 190
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RegisterAddresses_HostName_Success at 2018-07-19T19:23:23
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests
| [0.010s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.014s] TestLifetime Information: Finished test RegisterAddresses_HostName_Success in 0.012739s
```

CC @Eilon for triaging.

**Comment by Eilon** [comment] 2018-07-20 17:59
@Tratcher - can you please take a look? It is a high priority to resolve these flaky tests.

**Comment by Tratcher** [comment] 2018-07-20 19:56
5 failures starting 7/18 through today, all on OSX High Sierra.

AddressRegistrationTests.ListenAnyIP_HostName_Success is also failing with the same errors.

Possibilities:
- Agent instability, reboot?
- Framework High Sierra specific regression in Sockets/DNS? 
  - Have there been any OS updates on the High Sierra machine?
  - Have we taken any corefx updates in the last two days?

**Comment by Eilon** [comment] 2018-07-20 20:08
Thanks @Tratcher !

@ryanbrandenburg - do you know the answer to any of these questions?

**Comment by ryanbrandenburg** [comment] 2018-07-20 20:20
1. What kind of instability do you posit? Stale processes? Open ports?
2. 
- Not that I know of, although @natemcmaster was logged on to one of the mac machines yesterday.
- No CoreFx updates in the last 2 days.

**Comment by Tratcher** [comment] 2018-07-20 22:15
These are the only tests that depend on the HostNameIsReachable skip condition. It calls Dns.GetHostName() and then tries to open a connection to it.

https://github.com/aspnet/KestrelHttpServer/blob/612fcca7291e5fad753fccbd8b15279c21e2e288/test/Kestrel.FunctionalTests/TestHelpers/HostNameIsReachableAttribute.cs#L37-L39

It doesn't expect the connection to succeed, but it does check for specific known error codes. It's possible this list is incomplete and we're hitting a new error due to some change in DNS or similar.

It looks like that middle build without a failure was skipped by this conditional with the message "Test cannot run when network is unreachable. Socket exception: 'Attempt to establish a connection took over a second without success or failure.'" All of the cases where I can see that it was skipped were for the same timeout reason.

[Update] I just noticed that this test also failed in the 2.2 branch yesterday but has passed every build since then. This may have been a transient agent issue, let's check back next week to see if there are any more instances. John has scheduled a reboot of the agent anyways.

**Comment by Tratcher** [comment] 2018-07-27 23:19
No additional failures since the agent recovered on the 19th. Closing as resolved.

**Closed by Tratcher** 2018-07-27 23:19 UTC
Labels: flaky test
