### ISSUE TITLE
Test failure: LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1789] opened 2017-04-28 01:04 UTC
Fails rather consistently on my Ubuntu 14.04 VM. Doesn't repro on my 16.04 one though.

This was in the `rel/2.0.0-preview1` branch. cc @muratg

```
[xUnit.net 00:00:30.9479479]     LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter [FAIL]
[xUnit.net 00:00:30.9550052]       System.TimeoutException : The operation at /home/cesars/src/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/LoggingConnectionAdapterTests.cs:45 timed out after reaching the limit of 10000ms.
[xUnit.net 00:00:30.9560423]       Stack Trace:
[xUnit.net 00:00:31.0824414]            at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
[xUnit.net 00:00:31.0825578]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:31.0826009]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:31.0826432]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:31.0826724]            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[xUnit.net 00:00:31.0827006]            at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.LoggingConnectionAdapterTests.<LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter>d__0.MoveNext()
[xUnit.net 00:00:31.0827272]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:31.0827466]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:31.0827687]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:31.0827842]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:31.0828025]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:31.0828234]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:31.0828376]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:31.0828562]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:31.0828760]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter
Error Message:
 System.TimeoutException : The operation at /home/cesars/src/aspnet/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/LoggingConnectionAdapterTests.cs:45 timed out after reaching the limit of 10000ms.
Stack Trace:
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.LoggingConnectionAdapterTests.<LoggingConnectionAdapterCanBeAddedBeforeAndAfterHttpsAdapter>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by muratg** [comment] 2017-04-28 01:08
Does it look like a product bug on downlevel Ubuntu? Or more a test issue?

**Comment by cesarbs** [comment] 2017-04-28 01:13
Can't tell right now. I caught this while working on fixing the flakiness in `AddressRegistrationTests`. Will have to investigate more.

**Comment by davidfowl** [comment] 2017-04-28 05:52
Dupe of https://github.com/aspnet/KestrelHttpServer/issues/1697

**Closed by davidfowl** 2017-04-28 05:52 UTC
