### ISSUE TITLE
System.AccessViolationException in Kestrel in stress run

### ISSUE THREAD

**Issue by yuwaMSFT** [aspnet/KestrelHttpServer#657] opened 2016-02-25 23:03 UTC
(lldb) pe -nested
Exception object: 00007f5409851888
Exception type:   System.AccessViolationException
Message:          Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00007F542674B4D0 00007F5428AAB342 UNKNOWN!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib]].AwaitUnsafeOnCompleted[[System.__Canon, mscorlib],[Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__3[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel]](System.__Canon ByRef, <RequestProcessingAsync>d__3<Context> ByRef)+0x92
    00007F542674B530 00007F54282E0AE6 UNKNOWN!Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__3[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].MoveNext()+0xfb6
    00007F542674B640 00007F54282DEF91 UNKNOWN!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__3[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel]](<RequestProcessingAsync>d__3<Context> ByRef)+0x61
    00007F542674B670 00007F54282DEF04 UNKNOWN!Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].RequestProcessingAsync()+0x94
    00007F542674B740 00007F54279028F2 UNKNOWN!System.Threading.Tasks.Task`1[[System.__Canon, mscorlib]].InnerInvoke()+0xa2
    00007F542674B770 00007F54278F4469 UNKNOWN!System.Threading.Tasks.Task.Execute()+0x49
    00007F542674B7A0 00007F54278F424C UNKNOWN!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0xec
    00007F542674B7F0 00007F54278F3ED1 UNKNOWN!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+0x2b1
    00007F542674B8B0 00007F54278F3BA4 UNKNOWN!System.Threading.Tasks.Task.ExecuteEntry(Boolean)+0xc4
   00007F542674B8D0 00007F54278F5DB6 UNKNOWN!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x1c6

StackTraceString: <none>
HResult: 80004003

Nested exception -------------------------------------------------------------
Exception object: 00007f5409851888
Exception type:   System.AccessViolationException
Message:          Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00007F542674B4D0 00007F5428AAB342 UNKNOWN!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib]].AwaitUnsafeOnCompleted[[System.__Canon, mscorlib],[Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__3[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel]](System.__Canon ByRef, <RequestProcessingAsync>d__3<Context> ByRef)+0x92
    00007F542674B530 00007F54282E0AE6 UNKNOWN!Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__3[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].MoveNext()+0xfb6
    00007F542674B640 00007F54282DEF91 UNKNOWN!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1+<RequestProcessingAsync>d__3[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel]](<RequestProcessingAsync>d__3<Context> ByRef)+0x61
    00007F542674B670 00007F54282DEF04 UNKNOWN!Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].RequestProcessingAsync()+0x94
    00007F542674B740 00007F54279028F2 UNKNOWN!System.Threading.Tasks.Task`1[[System.__Canon, mscorlib]].InnerInvoke()+0xa2
    00007F542674B770 00007F54278F4469 UNKNOWN!System.Threading.Tasks.Task.Execute()+0x49
    00007F542674B7A0 00007F54278F424C UNKNOWN!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0xec
    00007F542674B7F0 00007F54278F3ED1 UNKNOWN!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+0x2b1
    00007F542674B8B0 00007F54278F3BA4 UNKNOWN!System.Threading.Tasks.Task.ExecuteEntry(Boolean)+0xc4
    00007F542674B8D0 00007F54278F5DB6 UNKNOWN!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x1c6

StackTraceString: <none>
HResult: 80004003

**Comment by yuwaMSFT** [comment] 2016-02-25 23:08
@halter73

**Comment by halter73** [comment] 2016-05-18 21:51
@yuwaMSFT Can you still reproduce this AV?

**Comment by halter73** [comment] 2016-05-27 23:24
@muratg @SajayAntony Has anyone seen any `System.AccessViolationException`'s recently? I need a repro or a memory dump to investigate this for 1.0.0.

**Comment by yuwaMSFT** [comment] 2016-05-28 00:16
There was a core file from Linux shared earlier \\funfile\Scratch\yuwa\Failures\022416\av
I couldn't remember details of this crash plz check the dump. 

We had certain fixes to move some callback to be executed within logcontext to avoid crash app. I don't know if this would also be suppressed.

**Comment by halter73** [comment] 2016-06-01 23:10
@muratg The `022416\av` was created February 24th when this issue was filed. We were still using dnx then. Obviously a lot has changed since then, should I investigate that dump? I'm not sure it's worth the effort if we can't reproduce with newer bits.

**Comment by muratg** [comment] 2016-06-02 16:00
@halter73 moved out to 1.0.1 for now. If @yuwaMSFT or someone from @SajayAntony's team still has a repro with the newer bits, we can investigate further... otherwise we can close this one post RTM.

**Comment by muratg** [comment] 2016-06-28 21:26
Closing. If it still repros, please file another one.

**Closed by muratg** 2016-06-28 21:26 UTC
Labels: stress
