### ISSUE TITLE
Microsoft.AspNet.Server.Kestrel.FunctionalTests failures on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#265] opened 2015-10-19 18:58 UTC
info: Exec
    info:   program: /usr/bin/env
    info:   commandline: bash -c ". \"/home/cesars/src/aspnet/universe/KestrelHttpServer/packages/KoreBuild/build/dnvm.sh\"; dnvm run default -runtime coreclr test"
    info:   workingdir: test/Microsoft.AspNet.Server.Kestrel.FunctionalTests
    xUnit.net DNX Runner (64-bit DNXCore 5.0)
      Discovering: Microsoft.AspNet.Server.Kestrel.FunctionalTests
      Discovered:  Microsoft.AspNet.Server.Kestrel.FunctionalTests
      Starting:    Microsoft.AspNet.Server.Kestrel.FunctionalTests
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.ResponseTests.<LargeDownload>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.AspNet.Server.Kestrel.FunctionalTests.ThreadCountTests.ZeroToTenThreads [SKIP]
          https://github.com/aspnet/KestrelHttpServer/issues/232
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          System.Threading.Tasks.TaskCanceledException : A task was canceled.
          Stack Trace:
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.AddressRegistrationTests.<RegisterAddresses_Success>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          Assert.Equal() Failure
                    ↓ (pos 0)
          Expected: 0
          Actual:   1048576
                    ↑ (pos 0)
          Stack Trace:
               at Microsoft.AspNet.Server.Kestrel.FunctionalTests.RequestTests.<LargeUpload>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Finished:    Microsoft.AspNet.Server.Kestrel.FunctionalTests
    === TEST EXECUTION SUMMARY ===
       Microsoft.AspNet.Server.Kestrel.FunctionalTests  Total: 11, Errors: 0, Failed: 10, Skipped: 1, Time: 901.973s

**Comment by cesarbs** [comment] 2015-10-19 19:38
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by halter73** [comment] 2015-10-28 23:57
@cesarbs I was actually abut to close this, since they're now passing on my machine. Are you seeing something different?

**Comment by cesarbs** [comment] 2015-10-29 21:58
Have a look at the latest CI build. There are some Kestrel test failures there.

**Comment by muratg** [comment] 2015-11-25 18:48
@halter73 this is one of the high pri fundamentals bugs that Eilon was talking about. Please look into this on Mac and Linux runs on the CI.

**Comment by halter73** [comment] 2015-11-30 19:15
Both the KestrelTests and the Kestrel.FunctionalTests projects have been running on Travis over a week with both coreclr and mono. The last 5 Travis builds of the dev branch have passed.

https://travis-ci.org/aspnet/KestrelHttpServer/builds/93789119#L2317

I'm about to manually run the build on OS X.

**Comment by halter73** [comment] 2015-11-30 23:25
CoreClr tests are looking good on Yosemite. I also ran the tests on a non-travis Trusty VM and things are good there.

**Comment by muratg** [comment] 2015-12-01 17:25
@halter73 All pass on aspnetci as well?

**Comment by halter73** [comment] 2015-12-01 18:24
Ubuntu-Universe and Mac-Universe haven't run since 11 days ago.

The last Mac run timed out before reaching the Kestrel tests. The last Ubuntu run timed out during the Kestrel tests.

We have skipped some hanging tests on **Mono** since the last runs, so I'm rerunning both configurations now. I'll report back once I get new results.

**Comment by halter73** [comment] 2015-12-09 20:46
I ran the full Kestrel build with both CoreCLR and Mono tests on our Mac agent twice, and it passed both tests.

I did the same on our Ubuntu agent, and the build hung both times after showing the (successful) result of the Mono test run. We saw this issue a while back, but I hadn't seen it recently on travis until @cesarbs showed me the exact same type of failure happened earlier today.

**Comment by halter73** [comment] 2015-12-10 01:22
Full Kestrel builds are once again passing on both the Mac and Ubuntu agents!

**Comment by muratg** [comment] 2015-12-10 04:54
Cool, thanks!

**Comment by halter73** [comment] 2015-12-11 20:49
At least the last two Ubuntu-Universe failures are due to it hanging in the middle of the Mono Kestrel tests.

After running Kestrel's build.sh in a loop until failure on the ubuntu agent, I am now once again seeing the Mono test hangs. Apparently I didn't catch everything. :(

**Comment by benaadams** [comment] 2015-12-13 18:29
https://github.com/aspnet/KestrelHttpServer/pull/473 may help with diagnosis; its helped me track down a few issues that didn't exhibit causes because some of the exceptions were getting masked in testing (though still exhibiting the symptoms of going wrong).

**Comment by muratg** [comment] 2015-12-14 12:35
@halter73 I believe @cesarbs enabled CoreCLR only agents... do we have 100% in those runs?

**Comment by halter73** [comment] 2015-12-14 23:05
The Kestrel repo successfully builds and all the tests pass for the CoreCLR only runs.

This test failed on the last Ubuntu CoreClr run:

> Test collection for E2ETests.PublishAndRunTests_OnX86 (1): E2ETests (1)
  PublishAndRunTests_OnX86.NonWindowsOS(serverType: Kestrel, runtimeFla…e: x86, applicationBaseUrl: "http://localhost:5035/", noSource: False) 	
  System.OperationCanceledException : Failed to connect, retry canceled.

I'm not sure if this is an issue with Kestrel or publish. I can look into it if it fails again on the next run.

**Comment by muratg** [comment] 2015-12-14 23:47
Sounds good, thanks.

**Comment by halter73** [comment] 2015-12-17 20:31
I seems the the `E2ETests.PublishAndRunTests_OnX86` failure is caused by a `TargetInvocationException` from `ConsoleLoggerProvider.CreateLoggerImplementation`. @cesarbs is tracking the fix.

**Closed** 2015-12-17 20:32 UTC
Labels: 2 - Working, Fundamentals
