### ISSUE TITLE
Can OnCompleted callbacks be called even though OnStarting was never called?

### ISSUE THREAD

**Issue by tenor** [aspnet/KestrelHttpServer#470] opened 2015-12-12 19:06 UTC
I'm looking at [FrameOfT#93](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/FrameOfT.cs#L93), and imagining the following scenario:

Application throws an exception, 
but hasn't called Response.Write() or Response.Flush(), which would have called FireOnStarting()

FireOnStarting() on line 93 is never called because _applicationException is set.
FireOnCompleted() (line 98) is called.

Is this an acceptable scenario?

**Comment by tenor** [comment] 2015-12-12 22:59
I can repro this scenario.
Create a new WebAPI application and change the api/values action to this:

```csharp
// GET: api/values
[HttpGet]
public IEnumerable<string> Get()
{
    bool onStartingCalled = false, onCompletedCalled = false;

    this.HttpContext.Response.OnStarting(() =>
    {
        return Task.Run(() =>
        {
            onStartingCalled = true;
        });
    });

    this.HttpContext.Response.OnCompleted(() =>
    {
        return Task.Run(() =>
        {
            System.Diagnostics.Debug.Assert(onStartingCalled);
            onCompletedCalled = true;
        });
    });

    //return new string[] { "value1", "value2" }; //Uncomment this to get the expected behavior

    throw new Exception();
}
```

**Comment by benaadams** [comment] 2015-12-15 00:29
Don't know, you might have stuff to clean up even if it threw exception and didn't start outputting?

**Comment by Tratcher** [comment] 2015-12-15 01:43
Yes, this is the behavior we want.

**Comment by halter73** [comment] 2015-12-18 00:38
@benaadams You are exactly right. We call the `OnCompleted` callback in spite of an `_applicationException`, because we want to allow users to treat it as a `finally` block of sorts. Firing `OnStarting` isn't necessary, because the application never attempted to even start writing a response.

I don't think we have any regression tests to verify we don't change this behavior, so I think we should keep this bug open until we add that.

**Comment by muratg** [comment] 2015-12-21 23:09
@JunTaoLuo

**Comment by cesarbs** [comment] 2016-01-08 20:06
Added regression test. Closing.

**Closed by cesarbs** 2016-01-08 20:06 UTC
Labels: 2 - Working, task
