### ISSUE TITLE
404 error on certain route templates

### ISSUE THREAD

**Issue by Hobart2967** [aspnet/KestrelHttpServer#587] opened 2016-01-17 14:34 UTC
I've got the problem with the routing. I am using attribute routing. 

Problem is, when naming defining a route like this:

        [HttpGet("get/{walkthroughid}")]
         public ResponseContainer<WalkthroughModel> GetWalkthrough(int walkthroughid)

        [HttpGet("get/{walkthroughId}")]
         public ResponseContainer<WalkthroughModel> GetWalkthrough(int walkthroughId)

Running the webapi on a kestrel server, it returns a 404 on calling /api/walkthroughs/get/123, while having 
        [Route("api/[controller]")]

defined on the controller. Renaming the route in the name or the parameter to for example [HttpGet("get/{walkthrougaId}")] (so change the "h" to an "a") or [HttpGet("getItem/{walkthroughId}")]
it works fine.

This is the failing case on **kestrel**

        01/17/2016 15:26:47 +01:00 [Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: **:5001  PathBase:   Path: /api/walkthroughs/get/123  QueryString:
        01/17/2016 15:26:47 +01:00 [Debug] The request path "/api/walkthroughs/get/123" does not match a supported file type
        01/17/2016 15:26:47 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{walkthroughid}"'.
        01/17/2016 15:26:47 +01:00 [Debug] No actions matched the current request
        01/17/2016 15:26:47 +01:00 [Debug] Request did not match any routes.
        01/17/2016 15:26:47 +01:00 [Information] Request finished in 0,0157ms 404

This is the working case on **weblistener**

    2016-01-17 19:00:46.839 +01:00 [Debug] Method: GET  PathBase:   Path: /api/walkthroughs/get/1313  Query:   Protocol: HTTP/1.1  Headers: Microsoft.Net.Http.Server.HeadersLogStructure
    dnx.exe Information: 0 : 2016-01-17 19:00:46.843 +01:00 [Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: marco-pc:5000  PathBase:   Path: /api/walkthroughs/get/1313  QueryString:
    2016-01-17 19:00:46.847 +01:00 [Debug] The request path "/api/walkthroughs/get/1313" does not match a supported file type
    2016-01-17 19:00:46.848 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{walkthroughid}"'.
    2016-01-17 19:00:46.849 +01:00 [Debug] Executing action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough"
    dnx.exe Information: 0 : 2016-01-17 19:00:46.885 +01:00 [Information] Executing action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" with arguments (["1313"]) - ModelState is Valid'
    2016-01-17 19:00:51.558 +01:00 [Debug] Executed action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough", returned result "Microsoft.AspNet.Mvc.ObjectResult".'
    2016-01-17 19:00:51.576 +01:00 [Debug] No information found on request to perform content negotiation.
    2016-01-17 19:00:51.580 +01:00 [Debug] Selected output formatter '"Microsoft.AspNet.Mvc.Formatters.JsonOutputFormatter"' and content type '"application/json"' to write the response.
    dnx.exe Information: 0 : 2016-01-17 19:00:51.582 +01:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNet.Mvc.ActionContext".
    dnx.exe Information: 0 : 2016-01-17 19:00:51.664 +01:00 [Information] Executed action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" in 0.4812ms
    dnx.exe Information: 0 : 2016-01-17 19:00:51.666 +01:00 [Information] Request finished in 0,4828ms 200 application/json; charset=utf-8

This is the working case on **kestrel**, replacing {walkthroughId} by just {id}

    01/17/2016 16:18:52 +01:00 [Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: localhost:5000  PathBase:   Path: /api/walkthroughs/get/1313  QueryString:
    01/17/2016 16:18:52 +01:00 [Debug] The request path "/api/walkthroughs/get/1313" does not match a supported file type
    01/17/2016 16:18:52 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{id}"'.
    01/17/2016 16:18:52 +01:00 [Debug] Executing action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough"
    01/17/2016 16:18:52 +01:00 [Information] Executing action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" with arguments (["1313"]) - ModelState is Valid'
    01/17/2016 16:18:52 +01:00 [Debug] Executed action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough", returned result "Microsoft.AspNet.Mvc.ObjectResult".'
    01/17/2016 16:18:52 +01:00 [Debug] No information found on request to perform content negotiation.
    01/17/2016 16:18:52 +01:00 [Debug] Selected output formatter '"Microsoft.AspNet.Mvc.Formatters.JsonOutputFormatter"' and content type '"application/json"' to write the response.
    01/17/2016 16:18:52 +01:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNet.Mvc.ActionContext".
    01/17/2016 16:18:52 +01:00 [Information] Executed action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" in 0.0017ms
    01/17/2016 16:18:52 +01:00 [Information] Request finished in 0,0018ms 200 application/json; charset=utf-8

This also happens for routes like this:

        [HttpGet("shop/{shopId}")]
        public FileStreamResult GetShopLogo(int shopId)

or

        [HttpGet("rating/{ratingId}")]
        public FileStreamResult GetRatingLogo(int ratingId)

or

        [HttpGet("screenshot/{screenshotId}")]
        public FileStreamResult GetScreenshot(int screenshotId)

But this route works by coincidence, and it`s just extended by "/thumb"

        [HttpGet("screenshot/{screenshotId}/thumb")]
        public FileStreamResult GetScreenshotThumb(int screenshotId)

I also tried using the "Route" attribute instead of "HttpGet". This does not bring any positive results either.

Any ideas? Running it on windows, with the WebListener "web" command it works fine.

// Update: Filed this problem in the Routing as well: https://github.com/aspnet/Routing/issues/279

**Comment by khellang** [comment] 2016-01-17 15:01
I think this is better suited for [MVC](https://github.com/aspnet/Mvc) or [Routing](https://github.com/aspnet/Routing), no?

**Comment by Hobart2967** [comment] 2016-01-17 15:02
I don't really know, I put it here, because it only happens on kestrel...

**Comment by khellang** [comment] 2016-01-17 15:06
> Checking the log, it shows this [...]

Is that for the scenario that works, or the one that doesn't work? Can you also post the other scenario so it's easier to compare the two?

**Comment by Hobart2967** [comment] 2016-01-17 15:20
Sure. The one I posted is the non-working one.
I'll update the first post too, but just for completeness: Here the working one (with {id} instead of {walkthroughId}:

    01/17/2016 16:18:52 +01:00 [Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: localhost:5000  PathBase:   Path: /api/walkthroughs/get/1313  QueryString:
    01/17/2016 16:18:52 +01:00 [Debug] The request path "/api/walkthroughs/get/1313" does not match a supported file type
    01/17/2016 16:18:52 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{id}"'.
    01/17/2016 16:18:52 +01:00 [Debug] Executing action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough"
    01/17/2016 16:18:52 +01:00 [Information] Executing action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" with arguments (["1313"]) - ModelState is Valid'
    01/17/2016 16:18:52 +01:00 [Debug] Executed action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough", returned result "Microsoft.AspNet.Mvc.ObjectResult".'
    01/17/2016 16:18:52 +01:00 [Debug] No information found on request to perform content negotiation.
    01/17/2016 16:18:52 +01:00 [Debug] Selected output formatter '"Microsoft.AspNet.Mvc.Formatters.JsonOutputFormatter"' and content type '"application/json"' to write the response.
    01/17/2016 16:18:52 +01:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNet.Mvc.ActionContext".
    01/17/2016 16:18:52 +01:00 [Information] Executed action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" in 0.0017ms
    01/17/2016 16:18:52 +01:00 [Information] Request finished in 0,0018ms 200 application/json; charset=utf-8

**Comment by Tratcher** [comment] 2016-01-17 15:24
> because it only happens on kestrel...

As opposed to? We don't have many other servers at this point.

**Comment by Hobart2967** [comment] 2016-01-17 15:25
Well, there's not "many other" servers, that's true, but it does not happen on a WebListener. So I put it here, because it could be related to just that one server.

**Comment by khellang** [comment] 2016-01-17 15:54
```diff
-01/17/2016 15:26:47 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{walkthroughid}"'.
+01/17/2016 16:18:52 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{id}"'.
```

OK, this is *really* weird. For some reason, it matches a different route for the same request (except the port). Something is :fish:-y here...

**Comment by Tratcher** [comment] 2016-01-17 16:00
What URLs is the server on?

**Comment by Hobart2967** [comment] 2016-01-17 18:03
Hereby the WebListener log:

    2016-01-17 19:00:46.839 +01:00 [Debug] Method: GET  PathBase:   Path: /api/walkthroughs/get/1313  Query:   Protocol: HTTP/1.1  Headers: Microsoft.Net.Http.Server.HeadersLogStructure
    dnx.exe Information: 0 : 2016-01-17 19:00:46.843 +01:00 [Information] Protocol: HTTP/1.1  Method: GET  ContentType:   ContentLength:   Scheme: http  Host: marco-pc:5000  PathBase:   Path: /api/walkthroughs/get/1313  QueryString:
    2016-01-17 19:00:46.847 +01:00 [Debug] The request path "/api/walkthroughs/get/1313" does not match a supported file type
    2016-01-17 19:00:46.848 +01:00 [Debug] Request successfully matched the route with name 'null' and template '"api/Walkthroughs/get/{walkthroughid}"'.
    2016-01-17 19:00:46.849 +01:00 [Debug] Executing action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough"
    dnx.exe Information: 0 : 2016-01-17 19:00:46.885 +01:00 [Information] Executing action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" with arguments (["1313"]) - ModelState is Valid'
    2016-01-17 19:00:51.558 +01:00 [Debug] Executed action method "avsn.api.Controllers.WalkthroughsController.GetWalkthrough", returned result "Microsoft.AspNet.Mvc.ObjectResult".'
    2016-01-17 19:00:51.576 +01:00 [Debug] No information found on request to perform content negotiation.
    2016-01-17 19:00:51.580 +01:00 [Debug] Selected output formatter '"Microsoft.AspNet.Mvc.Formatters.JsonOutputFormatter"' and content type '"application/json"' to write the response.
    dnx.exe Information: 0 : 2016-01-17 19:00:51.582 +01:00 [Information] Executing ObjectResult, writing value "Microsoft.AspNet.Mvc.ActionContext".
    dnx.exe Information: 0 : 2016-01-17 19:00:51.664 +01:00 [Information] Executed action "avsn.api.Controllers.WalkthroughsController.GetWalkthrough" in 0.4812ms
    dnx.exe Information: 0 : 2016-01-17 19:00:51.666 +01:00 [Information] Request finished in 0,4828ms 200 application/json; charset=utf-8

**Comment by ankitbko** [comment] 2016-01-19 05:43
Well.. I am unable to reproduce the issue. Is it possible for you to create a sample repo with code?
What version of dnx are you using and what runtime?

**Comment by Eilon** [comment] 2016-01-19 19:14
Closing this and let's use https://github.com/aspnet/Routing/issues/279 to discuss (I want to avoid having two open bugs on the same issue, and this doesn't *seem* like a Kestrel issue).

**Closed by Eilon** 2016-01-19 19:14 UTC
