### ISSUE TITLE
Upgrade Kestrel 1.1.0 submit POST not responded on behind NGINX with websocket supported

### ISSUE THREAD

**Issue by thohng** [aspnet/KestrelHttpServer#1263] opened 2016-12-19 18:02 UTC
Our services work fine with Kestrel 1.0.0 and 1.0.1 before. We also use `Microsoft.AspNetCore.SignalR.Server 0.1.0`

Got issue when upgrade Kestrel to 1.1.0.

Workaround: 
- downgrade to Kestrel 1.0.2
- or `proxy_set_header Connection $http_connection;`

Further investigation:
- Change `proxy_set_header Connection keep-alive;` then Kestrel 1.1.0 works but websocket not work.
- Ajax POST (json) not get the issue
- ASP.NET pages POST (Form data, Content-Type: application/x-www-form-urlencoded) with content result not get the issue.
- **Only ASP.NET pages POST (Form data) with redirect result get the issue.**

NGINX 1.10.0 / Ubuntu 16.04:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''   '';
}

map $http_x_forwarded_proto $thescheme {
	default $scheme;
	https https;
}

proxy_pass				http://localhost:5000/;
proxy_set_header Host 			$host;
proxy_set_header X-Real-IP 		$remote_addr;
proxy_set_header X-Forwarded-Host       $http_host;
proxy_set_header X-Forwarded-Proto	$thescheme;
proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
proxy_http_version                      1.1;
proxy_set_header Upgrade                $http_upgrade;
proxy_set_header Connection             "upgrade";
```

```
"frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        }
      },
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  }
}
```

**Comment by cesarbs** [comment] 2016-12-19 18:42
What behavior are you seeing when using Kestrel 1.1.0? I'm trying to repro your issue but so far haven't been able to.

**Comment by cesarbs** [comment] 2016-12-19 18:54
Have you tried using `proxy_set_header $http_connection`?

**Comment by thosoft** [comment] 2016-12-19 18:54
I got `504 Gateway Time-out` after 60s

> Have you tried using proxy_set_header $http_connection?
I did not try that

nginx log
access
`1.2.3.4 - - [19/Dec/2016:18:50:07 +0000] "POST /admin/account/login?returnurl=%2Fadmin%2F HTTP/2.0" 504 665 "https://aaa...`

error
```
2016/12/19 18:50:07 [error] 6272#6272: *7943 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 1.1.1.1, server: abc.com, request: "POST /admin/account/login?returnurl=%2Fadmin%2F HTTP/2.0", upstream: "http://127.0.0.1:5000/admin/account/login?returnurl=%2Fadmin%2F", host: "abc.com", referrer: "https://abc.com/admin/account/login?ReturnUrl=%2Fadmin%2F"
```

**Comment by cesarbs** [comment] 2016-12-19 18:57
What client are you using? This is odd: `HTTP/2.0`.

**Comment by thosoft** [comment] 2016-12-19 18:58
> What client are you using? This is odd: HTTP/2.0.

Chrome browser

on NGINX `listen 443 http2 ssl;` => It works before

**Comment by cesarbs** [comment] 2016-12-19 18:59
Ok, so you're sending an HTTP/2 request and nginx should be translating that to 1.1 clear text. I'll try that next.

**Comment by cesarbs** [comment] 2016-12-19 19:01
But let me know if `proxy_set_header $http_connection` helps.

**Comment by thosoft** [comment] 2016-12-19 19:02
I don't know how to setting `proxy_set_header $http_connection`

**Comment by thosoft** [comment] 2016-12-19 19:06
Yes, `proxy_set_header $http_connection` helps work both POST and Websocket.
Thanks @cesarbs !

```
# proxy_set_header Connection             "upgrade";
proxy_set_header Connection $http_connection;
```

**Comment by cesarbs** [comment] 2016-12-20 00:58
@thosoft I haven't been able to repro your exact issue, unfortunately. A couple points though:

- `Microsoft.AspNetCore.SignalR.Server` is a deprecated package. You should switch to `Microsoft.AspNetCore.SignalR` when upgrading to Kestrel 1.1.0.
- On the few occasions that I observed things not working, the reason was that the app I was testing with was making requests to `http` and `ws` endpoints, instead of `https` and `wss`.

I recommend you review your app and address those points.

**Comment by thosoft** [comment] 2016-12-20 02:41
@cesarbs I have updated above for more detail `map $http_upgrade $connection_upgrade` and `map $http_x_forwarded_proto $thescheme`
- For `Microsoft.AspNetCore.SignalR` the latest version 0.2.0-rtm-22752 now is on https://dotnet.myget.org/feed/aspnetcore-master/package/nuget/Microsoft.AspNetCore.SignalR.Server . We will consider upgrade SignalR when it ready with .NETCore 1.1.0.
- Because we got issue with redirection twice (https and http) before http://stackoverflow.com/questions/38748989/deploy-asp-net-core-mvc-behind-nginx-that-does-ssl-termination-redirects-to-no/39383668 . We may revisit it again later.

**Comment by cesarbs** [comment] 2016-12-21 19:43
Just need to confirm one thing: you see the original issue(s) when using Kestrel 1.1.0 and `Microsoft.AspNetCore.SignalR` 0.2.0-rtm-22752. Correct?

The form POST with redirect might be a different issue, but I'll investigate that too.

I think either 

`proxy_set_header Connection keep-alive;`

or

`proxy_set_header Connection upgrade;`

will always lead to some kind of problem, since you're always forcing the `Connection` header to assume a certain value from nginx to Kestrel (i.e. erasing whatever came from the browser). That's why I recommend you use `proxy_set_header Connection $http_connection;`. Admittedly though, I'm surprised that[ nginx's official recommendation](https://www.nginx.com/blog/websocket-nginx/) is to set it to `upgrade` if you want to use WebSockets. That's suboptimal for non-WebSocket requests, because Kestrel will always see a `Connection` header without a `keep-alive` token and will not handle the request as a keep-alive one, and will close the connection after every response is sent, forcing the browser to open a new connection upon every new request.

**Comment by thosoft** [comment] 2016-12-22 06:32
> Just need to confirm one thing: you see the original issue(s) when using Kestrel 1.1.0 and Microsoft.AspNetCore.SignalR 0.2.0-rtm-22752. Correct?

Confirmed original issue when upgrade Kestrel 1.1.0 with `proxy_set_header Connection upgrade;` and
```
"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
"Microsoft.AspNetCore.SignalR.Server": "0.1.0",
"Microsoft.AspNetCore.WebSockets.Server": "0.1.0",
```

I just re-test and receive same issue/behavior when upgrade both below or separated
- `Microsoft.AspNetCore.SignalR.Server 0.2.0-rtm-22752`
- `Microsoft.AspNetCore.WebSockets 1.0.0` (replace `Microsoft.AspNetCore.WebSockets.Server 0.1.0`)

For nginx, if change `proxy_set_header Connection keep-alive;` => resolve POST 504 issue, but Signalr fallback to EventStream.
`/signalr/signalr/negotiate?` return `TryWebSockets:true` but `wss://domain.com/signalr/signalr/connect?transport=webSockets&` return `400 bad request`

**Comment by cesarbs** [comment] 2017-01-10 00:49
@thosoft Thanks. Another thing I'm curious about: do you still see the original issue if you use HTTP/1.1 instead of HTTP/2?

**Comment by thosoft** [comment] 2017-01-10 03:02
Hi @cesarbs , still see the original issue when use HTTP/1.1
```
2017/01/10 02:40:20 [error] 16865#16865: *320842 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 1.2.3.4, server: abc.com, request: "POST /admin/account/edit HTTP/2.0", upstream: "http://127.0.0.1:5000/admin/account/edit", host: "abc.com", referrer: "https://abc.com/admin/account/edit"
2017/01/10 02:55:21 [error] 18222#18222: *321829 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 1.2.3.4, server: abc.com, request: "POST /admin/account/edit HTTP/1.1", upstream: "http://127.0.0.1:5000/admin/account/edit", host: "abc.com", referrer: "https://abc.com/admin/account/edit"
```

When I submit POST, the browser keep waiting 60s before timeout. At the time timeout, Kestrel receive the request from NGINX and NGINX return 504 to client.

**Comment by muratg** [comment] 2017-05-12 22:09
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 22:09 UTC

**Comment by houstondapaz** [comment] 2017-09-21 00:09
I have de same error with aspnet core 2.0
I'm using nginx with
```nginx
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```

and had Bad Request on execute POST 

```
92.168.99.1 - - [20/Sep/2017:23:44:34 +0000] "POST /api/macro/6326dc53-11ff-40d1-9e1f-eb8b023ab9a6/execute HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
macro-microservice-dev_1  |       Connection id "0HL80G47DAVCP" bad request data: "Requests with 'Connection: Upgrade' cannot have content in the request body."
macro-microservice-dev_1  | Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Requests with 'Connection: Upgrade' cannot have content in the request body.
macro-microservice-dev_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ThrowRequestRejected(RequestRejectionReason reason)
macro-microservice-dev_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.For(HttpVersion httpVersion, FrameRequestHeaders headers, Frame context)
macro-microservice-dev_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

This rule, don't could send a body in Connection: Upgrade, is a HTTP rule?

**Comment by cesarbs** [comment] 2017-09-21 19:56
@houstondapaz You can fix that by configured nginx to forward the Connection header it receives from the client:

```nginx
proxy_set_header Connection $http_connection;
```

Our behavior is stricter than what's specified in the HTTP spec. That said, other servers (e.g. http.sys based servers) also reject upgrade requests that indicate the presence of a request body (by including a Transfer-Encoding: chunked or Content-Length header. cc @Tratcher

**Comment by houstondapaz** [comment] 2017-10-03 02:54
@cesarbs Thanks for reply.
But I was configured as ```Connection $http_connection;``` and the error persists, now in the socket system after the first POST requisition (Connection Keep Alive)

To fix I separated the services in a nginx configuration to each

**Comment by cesarbs** [comment] 2017-10-06 02:11
@houstondapaz Are you seeing the exact same error? That means your client might be sending something like `Connection: keep-alive, upgrade`. Can you check if that's the case?

**Comment by JinsPeter** [comment] 2017-12-15 09:13
Similar websocket + http config for apache is solve in [this issue](https://github.com/aspnet/KestrelHttpServer/issues/1263)
