### ISSUE TITLE
Flaky test: TestInvalidHeaders

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2211] opened 2017-12-07 22:40 UTC
Based on [this](http://aspnetci/viewLog.html?buildId=363484&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest) test it looks like in some cases our tests are getting blank responses back.

**Comment by Tratcher** [comment] 2018-06-08 21:31
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/2635

**Closed by Tratcher** 2018-06-08 21:31 UTC
Labels: flaky test
