### ISSUE TITLE
Test failure: RejectsRequestWithContentLengthAndUpgrade 

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1770] opened 2017-04-26 02:12 UTC
```
[xUnit.net 00:00:09.2670338]     RejectsRequestWithContentLengthAndUpgrade [FAIL]
[xUnit.net 00:00:09.2682405]       System.IO.IOException : Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
[xUnit.net 00:00:09.2683390]       ---- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
[xUnit.net 00:00:09.2692419]       Stack Trace:
[xUnit.net 00:00:09.2700061]            at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
[xUnit.net 00:00:09.2700979]            at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
[xUnit.net 00:00:09.2701492]            at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
[xUnit.net 00:00:09.2702132]            at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
[xUnit.net 00:00:09.2702516]            at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
[xUnit.net 00:00:09.2702844]            at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
[xUnit.net 00:00:09.2703167]            at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
[xUnit.net 00:00:09.2703451]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2703768]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2704105]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2704413]            at System.IO.StreamReader.<ReadAsyncInternal>d__64.MoveNext()
[xUnit.net 00:00:09.2704692]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2705000]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2705328]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2705651]            at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
[xUnit.net 00:00:09.2705938]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2706264]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2706589]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2706929]            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
[xUnit.net 00:00:09.2707293]         D:\src\aspnet\KestrelHttpServer\test\shared\TestConnection.cs(89,0): at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__12.MoveNext()
[xUnit.net 00:00:09.2707891]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2708249]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2708580]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2708915]            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
[xUnit.net 00:00:09.2709331]         D:\src\aspnet\KestrelHttpServer\test\shared\TestConnection.cs(112,0): at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveForcedEnd>d__14.MoveNext()
[xUnit.net 00:00:09.2709967]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2710404]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2710750]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2711055]            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
[xUnit.net 00:00:09.2711522]         UpgradeTests.cs(130,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.<RejectsRequestWithContentLengthAndUpgrade>d__2.MoveNext()
[xUnit.net 00:00:09.2712281]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2712656]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2713005]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2713281]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2713598]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2713926]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2714199]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:09.2714516]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:09.2714844]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:09.2715117]         ----- Inner Stack Trace -----
[xUnit.net 00:00:09.2715469]            at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
[xUnit.net 00:00:09.2716049]            at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
[xUnit.net 00:00:09.2858692]   Finished:    Microsoft.AspNetCore.Server.Kestrel.FunctionalTests
Failed   RejectsRequestWithContentLengthAndUpgrade
Error Message:
 System.IO.IOException : Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
---- System.Net.Sockets.SocketException : An established connection was aborted by the software in your host machine
Stack Trace:
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadAsyncInternal>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Testing.TaskExtensions.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Testing.TestConnection.<Receive>d__12.MoveNext() in D:\src\aspnet\KestrelHttpServer\test\shared\TestConnection.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Testing.TestConnection.<ReceiveForcedEnd>d__14.MoveNext() in D:\src\aspnet\KestrelHttpServer\test\shared\TestConnection.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UpgradeTests.<RejectsRequestWithContentLengthAndUpgrade>d__2.MoveNext() in D:\src\aspnet\KestrelHttpServer\test\Microsoft.AspNetCore.Server.Kestrel.FunctionalTests\UpgradeTests.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
```

**Comment by davidfowl** [comment] 2017-04-26 02:31
Dupe of https://github.com/aspnet/KestrelHttpServer/issues/1742

**Closed** 2017-04-26 18:47 UTC
