### ISSUE TITLE
Question. Memory and cpu limits

### ISSUE THREAD

**Issue by oerodriguezn** [aspnet/KestrelHttpServer#2209] opened 2017-12-06 13:15 UTC
How can i configure asp dot net core to have memory and/or cpu usage limits like IIS app pools settings. We would like to use kestrel without IIS but we need to be able to setup that kind of resources usage limits to our applications.

**Comment by Tratcher** [comment] 2017-12-06 16:25
Duplicate of https://github.com/aspnet/Home/issues/2300

**Closed by Tratcher** 2017-12-06 16:25 UTC
