### ISSUE TITLE
HttpConnectionContext add feature to expose RemoteEndPoint

### ISSUE THREAD

**Issue by liuhongbo** [aspnet/KestrelHttpServer#2875] opened 2018-09-01 14:47 UTC
when ConnectionContext passes to ConnectionHandler.OnConnectedAsync,  right now, there is no way to know the information about RemoteEndPoint.

Is it a good idea to add feature to the HttpConnectionContext to be able to access the RemoteEndPoint information?

**Comment by Tratcher** [comment] 2018-09-01 15:03
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/2835 ?

**Comment by halter73** [comment] 2018-09-04 18:36
Also, it's an unfortunate name, but you should be able to get this information [the same way the HttpConnectionMiddleware does](https://github.com/aspnet/KestrelHttpServer/blob/8f6cb72ef27d86c9f691ba39851aa958a265cd5e/src/Kestrel.Core/Internal/HttpConnectionMiddleware.cs#L52-L65) by accessing `ConnectionContext..Features.Get<IHttpConnectionFeature>()`.

**Comment by muratg** [comment] 2018-09-19 22:27
dup of https://github.com/aspnet/KestrelHttpServer/issues/2835

**Closed by muratg** 2018-09-19 22:27 UTC
