### ISSUE TITLE
http/2: Framing

### ISSUE THREAD

**Issue by shirhatti** [aspnet/KestrelHttpServer#2628] opened 2018-05-30 19:42 UTC
Our current http/2 framing work pre-dates Memory/Span and will need to be re-visited for perf/quality

**Comment by Tratcher** [comment] 2018-06-03 15:14
@benaadams any interest in HTTP/2? This one looks right up your ally.

**Comment by Tratcher** [comment] 2018-08-31 17:11
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/2858

**Closed by Tratcher** 2018-08-31 17:11 UTC
Labels: 1 - Ready, HTTP2, cost: M, perf
