### ISSUE TITLE
Travis jamms/hangs

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#338] opened 2015-11-06 09:18 UTC
Frequently Travis will jam when running tests; this is between tests before moving onto the next exec step e.g.

> === TEST EXECUTION SUMMARY ===
   Microsoft.AspNet.Server.KestrelTests  Total: 218, Errors: 0, Failed: 0, Skipped: 4, Time: 19.726s
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated

**Comment by benaadams** [comment] 2015-11-06 09:20
Multiple PRs is unrelated :(

**Comment by benaadams** [comment] 2015-11-06 09:22
For reference next lines should be
> info: Exec
info:   program: cmd
info:   commandline: /C dnx test

**Comment by benaadams** [comment] 2015-11-06 15:11
Looks like this might be fixed in mono 4.2.0

**Comment by akoeplinger** [comment] 2015-11-06 15:58
You can try out 4.2 by adding `mono: alpha` to .travis.yml :)

**Comment by dougbu** [comment] 2015-11-06 16:29
Not recommended since Mono 4.2 has other issues at least when used with Ubuntu 12.04. I will soon migrate our Travis configuration to use the new Ubuntu 14.04 (Trusty) systems. We should look at what works and what doesn't (with stable Mono releases) after that migration.

**Comment by akoeplinger** [comment] 2015-11-06 16:32
@dougbu I'd be interested to hear about the 12.04 vs 14.04 issues? Mono 4.2 will be released very soon.

**Comment by dougbu** [comment] 2015-11-06 16:38
For example https://bugzilla.xamarin.com/show_bug.cgi?id=30018 was only fixed in Mono 4.3 and it breaks `dnu restore` fairly reliably on Ubuntu 14.04.

Further we see significant MVC test regressions when running with the Mono Alpha feed.

Another push toward Ubuntu 14.04 is the fact .NET Core has targeted that specific release.

**Comment by akoeplinger** [comment] 2015-11-06 16:51
> For example https://bugzilla.xamarin.com/show_bug.cgi?id=30018 was only fixed in Mono 4.3 and it breaks dnu restore fairly reliably on Ubuntu 14.04.

I'll make sure this gets into the first service release for Mono 4.2

> Further we see significant MVC test regressions when running with the Mono Alpha feed.

That's unfortunate... MVC would need to stay on 4.0 for the time being then.

**Comment by dougbu** [comment] 2015-11-06 17:03
> MVC would need to stay on 4.0 for the time being then.

To be clear: That was an example of problems we've seen w/ more recent Mono builds than 4.0.4.

Regardless, let's not churn the `mono:` value in `.travis.yml` 'til we're solidly on Ubuntu 14.04 and have worked through _those_ issues (if any).

**Comment by benaadams** [comment] 2015-11-08 20:51
Might not be this as the suggested workaround is ` -parallel none` which its already doing; might still be the same issue though?

**Comment by benaadams** [comment] 2015-11-09 04:57
Occurrence is high, 38 PRs failed in this repository in the last 5 days due to this (mostly just add whitespace, resumbit)

**Comment by benaadams** [comment] 2015-11-09 09:30
Not just this repo though https://github.com/aspnet/dnx/issues/2964

**Comment by benaadams** [comment] 2015-11-10 20:29
It normally hangs after the 218 test project; maybe split it into smaller batches? @halter73

**Comment by halter73** [comment] 2015-11-11 01:11
I don't think splitting the tests in smaller batches will help.

After discussing this with @troydai, I learned that these hangs are caused by test running not exiting after the test run has completed on Mono < 4.2.

**Closed** 2015-11-13 21:34 UTC
Labels: 3 - Done, bug
