### ISSUE TITLE
Configure header parsing to allow non-compliant headers

### ISSUE THREAD

**Issue by blowdart** [aspnet/KestrelHttpServer#1144] opened 2016-10-03 22:50 UTC
Rather than rejecting requests, allow configuration to either ignore UTF8 headers, or, parse them, even if they're illegal. 

I suggest an enum Reject, Ignore, Parse.

However on output we should still be strict, UrlEncoding cookie values etc.

See https://github.com/aspnet/KestrelHttpServer/issues/1076 and https://github.com/aspnet/KestrelHttpServer/issues/1125

edit by @muratg: We should also consider request line when we get to this. https://github.com/aspnet/KestrelHttpServer/issues/2647

**Comment by Tratcher** [comment] 2016-10-03 22:54
In practice I expect this to become an FAQ where most people turn on UTF-8, so we should consider making that the default.

Have we tested how these headers forward through IIS? WebListener?

**Comment by blowdart** [comment] 2016-10-03 23:28
I like how we say "We" Nope, please try it :p

**Comment by muratg** [comment] 2016-10-06 23:11
@halter73 please work with @cesarbs, based on timing this may be load balanced to you.

cc @davidfowl

**Comment by muratg** [comment] 2016-10-31 21:15
A big change (essentially a rewrite in header processing) so moving to 1.2.0.

@Tratcher could you file a corresponding bug on WebListener repo?

**Comment by muratg** [comment] 2016-10-31 21:31
Should also fix: https://github.com/aspnet/KestrelHttpServer/issues/1125

**Comment by cesarbs** [comment] 2017-01-17 18:29
Investigating this. Will check how those headers forward through IIS, and also what other servers do.

**Comment by cesarbs** [comment] 2017-01-18 20:00
Here's what I found so far:

Server | Behavior
-- | --
IIS | accepts UTF-8 in header value, don't know what it does with it
IIS running ASP.NET 4 app | accepts UTF-8, decodes it as such
IIS with ANCM | rejects, not yet sure why, but the request is not forwarded at all
WebListener | accepts UTF-8, decodes it as such
nginx | accepts non-ASCII, haven't checked yet what it does with it
node.js | accepts non-ASCII, it's up to the app to decode it
Apache |accepts non-ASCII, it's up to the app to decode it

A relevant bit from [the RFC](https://tools.ietf.org/html/rfc7230#section-3.2.4):

```
Historically, HTTP has allowed field content with text in the
ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
through use of [RFC2047] encoding.  In practice, most HTTP header
field values use only a subset of the US-ASCII charset [USASCII].
Newly defined header fields SHOULD limit their field values to
US-ASCII octets.  A recipient SHOULD treat other octets in field
content (obs-text) as opaque data.
```

I think the most relevant part here is:

```
A recipient SHOULD treat other octets in field content (obs-text) as opaque data.
```

So it's not forbidding chars above 0x7F. `obs-text` is actually defined in the [next section](https://tools.ietf.org/html/rfc7230#section-3.2.6) as

```
obs-text       = %x80-FF
```

The most correct behavior seems to be to accept characters in the 0x80 - 0xFF range (which we reject at present), but to let the app decide the encoding. Http.sys appears to deviate from this though, by decoding as UTF-8.

**Comment by Tratcher** [comment] 2017-01-18 20:03
For reference, which header did you test? You may get different results for a common header vs a custom header. E.g. Host and Location are often special cased.

**Comment by Tratcher** [comment] 2017-01-18 20:04
How does Apache leave it up to the app to decode it? Does it expose the raw header bytes?

**Comment by cesarbs** [comment] 2017-01-18 20:26
@Tratcher I was testing with Referer, as in #1125.

I tested Apache with a PHP app, which saw the header as raw bytes. You get a "string" for it, but I'd have to manually decode it as UTF-8 to get the right chars.

**Comment by muratg** [comment] 2017-04-07 19:28
@blowdart We're currently rejecting if the header is UTF8, so I don't think this has security implications. Moving to 2.1.0

**Comment by blowdart** [comment] 2017-04-07 19:30
Won't this still reject UTF8 cookies? if so that's a problem

**Comment by Drawaes** [comment] 2017-04-07 21:14
FYI if you care SNI says the host is utf8
> The hostname is represented as a byte
   string using UTF-8 encoding [UTF8], without a trailing dot.
Now a good server should probably check the host header and SNI match, might be impossible if you can't have a utf8 header

**Comment by davidfowl** [comment] 2017-04-07 21:46
> Won't this still reject UTF8 cookies? if so that's a problem

Why is that a problem? We've had 2 complaints overall so far.

**Comment by vinhhrv** [comment] 2017-08-04 06:29
If you provide service for customers, and they allowed to insert javascript,
and If it accidentally inserts a unicode character.
then their customers will have problems forever.

critical problem. please hot fix

**Comment by jlandersen** [comment] 2017-09-01 12:49
IE doesn't encode the referer header. As a result, this breaks our .NET Core APIs when requests are coming from IE users on some of our sites with e.g. Cyrillic characters in the URL. Would be good to have support for this.

**Comment by KLuuKer** [comment] 2017-09-04 09:05
@davidfowl I think you are not getting many complaints because it takes so long to track down what the issue is. Because many different applications might set cookies with utf-8 characters on the root of the domain (.example.com) and thus some developers might blame it on user error because that encoding error is not popping up in the logs and may be hard to reproduce.

**Comment by avaneerd** [comment] 2017-09-04 11:42
We could really use this, we have a site running on a subdomain (site.bigcompany.com) and user navigate to our site through our company site (bigcompany.com). Our company site uses cookies with non-ascii characters that are also sent to the subdomains and causes users that access our site through our company site to receive bad requests. We're now working with the team from our company site to have them fix their cookies.

I believe this is something that can also be misused for a DOS-attacks. If you manage to set a cookie in the users browser then your site (running ANC) will not function anymore.

**Comment by netranger** [comment] 2017-09-20 14:15
As other mentions, the error might originate from javascript cookies and not your own code, so you might not able to correct the error.

In our situation **Google Analytics** sat the malformed/utf-8 cookie.

Our marketing department used the querystring **utm_campaign** to name their campaigns (containing danish characters), so when they made an url to our site, and posted it on facebook or other places, all users that clicked that link was no longer able to view our website after the first page view. Only solution was to clear cookies (or wait the 6 months until cookie expiration) - but not many users told us we had a problem, they just went on to our competitor instead.

* User clicks link http://website/page?utm_campaign=MinKampagneUndersøgelse
* Page loads and user sees it fine
* Google Analytics kicks in on the client side and sees the utm_campaign querystring and stores a __utmz cookie on our domain containing the utf-8 string
* Next pageload by the user is unable to process because of the utf-8 cookie and the user sees a blank page with no error.

It took us ages to track down, because the cookie was actually sat on a parent domain and not the kestrel site (which, at the time, was running on a subdomain). And it was not even sat by our own code, but **third party javascript**, so searching our codebase for the cookie name came out with 0 results.

Since we discovered the error, a newer version of Google Analytics has changed behaviour of storing all their data at their side and only store a user-id cookie on the client side, so the malformed cookie is no longer set. See this for explanation: https://stackoverflow.com/questions/18604715/google-analytics-missing-utmz-cookie

I think you might be  able to reproduce the error if you are using the **old** Google Analytics scripts (ga.js) on your kestrel website (instead of the newer analytics.js), by simply loading a url with a **utm_campaign** querystring containing international characters (we have switched to the newer version, so can't test it on my own anymore).

It would be great to at least have some kind of option to ignore utf8 cookies, so we at least can get around it by programming instead of loosing users forever.

**Comment by TommyRush** [comment] 2017-10-16 13:01
We also had this problem, which was extremely difficult to narrow down to being this. We use shibboleth which is injecting request headers into our application. One of our staff had í in their name, which just resulted in them getting the 400 error and us being confused for a long time.

**Comment by tpeczek** [comment] 2017-11-14 20:48
I also had an issue reported in context of Server-Timing header. The [definition of this header](http://www.w3.org/TR/server-timing/#the-server-timing-header-field) allows using *quoted-string* for *server-timing-param-value* and *quoted-string* allows broader set of characters:

> quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
> qdtext              = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
> obs-text           = %x80-FF

So this header would require an option of relaxing the ascii-only check also for responses.

**Comment by benaadams** [comment] 2017-11-14 22:30
[rfc7230](https://tools.ietf.org/html/rfc7230)
```
3.2.6.  Field Value Components

   Most HTTP header field values are defined using common syntax
   components (token, quoted-string, and comment) separated by
   whitespace or specific delimiting characters.  Delimiters are chosen
   from the set of US-ASCII visual characters not allowed in a token
   (DQUOTE and "(),/:;<=>?@[\]{}").

     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

   A string of text is parsed as a single value if it is quoted using
   double-quote marks.

     quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
     qdtext         = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
*    obs-text       = %x80-FF

   Comments can be included in some HTTP header fields by surrounding
   the comment text with parentheses.  Comments are only allowed in
   fields containing "comment" as part of their field value definition.

     comment        = "(" *( ctext / quoted-pair / comment ) ")"
     ctext          = HTAB / SP / %x21-27 / %x2A-5B / %x5D-7E / obs-text

   The backslash octet ("\") can be used as a single-octet quoting
   mechanism within quoted-string and comment constructs.  Recipients
   that process the value of a quoted-string MUST handle a quoted-pair
   as if it were replaced by the octet following the backslash.

     quoted-pair    = "\" ( HTAB / SP / VCHAR / obs-text )

   A sender SHOULD NOT generate a quoted-pair in a quoted-string except
   where necessary to quote DQUOTE and backslash octets occurring within
   that string.  A sender SHOULD NOT generate a quoted-pair in a comment
   except where necessary to quote parentheses ["(" and ")"] and
   backslash octets occurring within that comment.
```

However
```
3.2.4.  Field Parsing
...
   Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
*  Newly defined header fields SHOULD limit their field values to
*  US-ASCII octets.  A recipient SHOULD treat other octets in field
*  content (obs-text) as opaque data.
```
As string is `UTF-16`; that would suggest the correct approach would be to reject `0x00` and simple widen all other chars converting `ISO-8859-1` -> `UTF-16` - which also mean any `UTF-8` outside the `ASCII` range would not be interpreted correctly?

**Comment by benaadams** [comment] 2017-11-14 22:32
e.g. treat `opaque data` as 8 byte data, converting (byte) `0xDD` -> (char)`0x00 0xDD`

**Comment by KLuuKer** [comment] 2017-12-07 20:41
@muratg you said 
> Moving to 2.1.0

it's still attached to the backlog milestone while a 2.1.0 milestone exists
is this going to get fixed in 2.1.0? or not?

**Comment by muratg** [comment] 2017-12-07 20:45
@KLuuKer bringing this back to triage.

**Comment by muratg** [comment] 2018-01-11 19:05
@shirhatti @DamianEdwards what are your thoughts on this one?

**Comment by muratg** [comment] 2018-02-13 23:45
Backlogging this, no work planned in 2.x.

**Comment by DamianEdwards** [comment] 2018-04-24 14:50
Let's investigate this for 2.2

**Comment by joetherod** [comment] 2018-04-26 00:32
My issue was related to a cookie set on the client and getting sent to server. Had this issue with not encoding cookies on the server, and they were set to empty. If the cookie is set on the client side, and posted, it shouldnt give a Bad Request page with no way to handle it in code. Another gotcha with cookies in aspnet core.

**Comment by axelheer** [comment] 2018-05-14 13:31
I have a similar problem. Our ASP.NET Core applications runs behind a "kind of" reverse proxy, which adds additional headers (for whatever purpose). These headers can contain german umlauts (e.g. "ö"), which lead to "Malformed request: invalid headers." and the requests ends immediately (400).

Is there any workaround to still serve these requests?

**Comment by Tratcher** [comment] 2018-05-14 13:35
No, there's no workaround when the request can't be decoded like this.

**Comment by benaadams** [comment] 2018-05-14 16:29
>  These headers can contain german umlauts (e.g. "ö"), which lead to "Malformed request: invalid headers." and the requests ends immediately (400).

Can you url encode the header? e.g. `ö` is `%C3%B6`

**Comment by davidfowl** [comment] 2018-05-14 17:41
https://www.punycoder.com/ 😄

**Comment by axelheer** [comment] 2018-05-14 17:45
@benaadams  the application setting these headers isn't under my control; I could decode anything. 🤷‍♂️  

But I'm going to ask its vendor; getting an answer there is generally a painful process and often not very helpful, though.

**Comment by DaBeSoft** [comment] 2018-07-02 10:15
I am facing the same problem as @TommyRush. I am using Shibboleth which injects headers. I neither have control over the Shibboleth installation nor over the dataset used by the shibboleth installation. So now MOST users can work without any problems, BUT the poor ones with umlauts in their name or other data can't do anything. 

Would appreciate this being fixed soon.

My Application is running behind IIS, is there any way IIS could parse the headers and "fix" them?

@TommyRush did you ever find a workaround?

**Comment by amrmahdi** [comment] 2018-07-13 19:18
Is there a way to track how many requests are being rejected because of this ? We not add the bad requests in our telemetry, and the request is rejected before any of our code is executed.

**Comment by halter73** [comment] 2018-07-13 22:03
@amrmahdi you can check your logs for info level logs of the form `Connection id "<ID>" bad request data: "Invalid request target: <Invalid Chars>"` and `Connection id "<ID>" bad request data: "Malformed request: invalid headers."`

**Comment by davidfowl** [comment] 2018-07-19 17:07
We're going to drop the entire header if it's not UTF8.

**Comment by benaadams** [comment] 2018-07-19 17:42
> We're going to drop the entire header if the header value not a valid UTF8 sequence.

Do you mean ASCII? UTF8 has never been a valid header encoding for HTTP1.x

**Comment by benaadams** [comment] 2018-07-19 17:44
> We're going to drop the entire header if the header value not a valid UTF8 sequence.

Do you mean ASCII? UTF8 has never been a valid header encoding for HTTP1.x. Closest is treating as opaque bytes, but don't think that helps with them as `string`

**Comment by Tratcher** [comment] 2018-07-19 20:58
> Do you mean ASCII? UTF8 has never been a valid header encoding for HTTP1.x. Closest is treating as opaque bytes, but don't think that helps with them as string

We know, but people keep insisting on sending us UTF-8 headers. Some servers allow it.

**Comment by benaadams** [comment] 2018-07-20 00:26
> > Do you mean ASCII? UTF8 has never been a valid header encoding for HTTP1.x. Closest is treating as opaque bytes, but don't think that helps with them as string

> We know, but people keep insisting on sending us UTF-8 headers. Some servers allow it.

Do they; or are they sending Latin1/IEC 8859-1 as called out by the spec

>    Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].

For example `\xD6\xD0\xCE\xC4` from https://github.com/aspnet/KestrelHttpServer/issues/2647 in UTF8 this is an invalid code sequence resulting in `����` in Latin1/ISO-8859-1 this is `ÖÐÎÄ`

**Comment by benaadams** [comment] 2018-07-20 01:08
Not sure `ÖÐÎÄ` makes much more sense, but `����` is a one way transform to jibberish

**Comment by benaadams** [comment] 2018-07-20 01:18
Looking at the various encoding for that example it looks like its UTF16LE
```csharp
// UTF8
Encoding.UTF8.GetString(new byte[] {0xD6,0xD0,0xCE,0xC4})
// Output: ����
```
```csharp
// UTF16LE
Encoding.Unicode.GetString(new byte[] {0xD6,0xD0,0xCE,0xC4})
// Output: 탖쓎
```
```csharp
// Widen to UTF16 (i.e. Latin1)
new string(new char[] {(char)0xD6,(char)0xD0,(char)0xCE,(char)0xC4})
// Output: ÖÐÎÄ
```

**Comment by KLuuKer** [comment] 2018-07-20 09:11
@DamianEdwards you say
>We're going to drop the entire header if the header value not a valid UTF8 sequence.

But what about the case when some ~~stupid~~ piece of script (usually not changeable because of ~~even more stupid~~ reasons) is inserting incorrect values in the cookies?

**Comment by davidfowl** [comment] 2018-07-21 18:58
There's no way to represent that data so the choices are:
- Drop the header
- Garble the value
- Reject the request.

**Comment by KLuuKer** [comment] 2018-07-23 14:16
for most headers I would choose: drop the header
for some selective headers (like cookie) I would choose: garble the value, and maybe have some way of trying to get the bits I need parsed out manually (at your own risk)

**Comment by benaadams** [comment] 2018-07-23 14:22
> There's no way to represent that data so the choices are ...

Suggesting this should be applied if header is outside the non-printable ascii range, rather than valid utf8; as any encoding outside non-ascii will likely garble the value; as it may not be correct one.

Or... allow an option to specify fallback `Encoding` to be used when ascii fast-path fails (while still rejecting control codes)

**Comment by JunTaoLuo** [comment] 2018-08-20 20:54
Update on the investigation and recommendations. I've tested the following with the `Referer` and `Cookies` headers:

Scenario | Extended Ascii (ISO-8859-1) | UTF-8 | Mixed (both extended ascii and utf-8)
-- | -- | -- | --
Kestrel (currently) | ❌ Request rejected | ❌Request rejected | ❌Request rejected 
IIS + Managed Handler (ASP.NET 4) | ✔️ Parsed correctly | ✔️Parsed correctly | ⚠️ Parsed as Extended ASCII
IIS + ANCM In-Proc | ⚠️ Parsed as UTF-8 | ✔️ Parsed correctly | ⚠️ Parsed as UTF-8
IIS + ANCM Out-of-proc | ✔️  Raw bytes passed on to server | ❌⚠️ May reject request (see below) | ✔️  Raw bytes passed on to the server
Apache  | ✔️  Raw bytes passed on to server | ✔️  Raw bytes passed on to server | ✔️  Raw bytes passed on to server
Apache + PHP | ⚠️ Parsed as UTF-8 | ✔️ Parsed correctly | ⚠️ Parsed as UTF-8
nginx | ✔️  Raw bytes passed on to server | ✔️  Raw bytes passed on to server | ✔️  Raw bytes passed on to server
node.js | ✔️ Parsed correctly | ⚠️ Parsed as Extended ASCII | ⚠️ Parsed as Extended ASCII

A few notes on the behaviours:
- IIS + Managed Handler (ASP.NET 4)
It seems like the managed handler will first attempt to parse all header values as UTF-8 but if that fails, it will fallback to ASCII 
- IIS + ANCM In-Proc
The encoding is hard-coded as UTF-8 https://github.com/aspnet/HttpSysServer/blob/eba2d7e380fef9f75203bb9a1f4d30827451d512/shared/Microsoft.AspNetCore.HttpSys.Sources/RequestProcessing/HeaderEncoding.cs#L10-L13
- IIS + ANCM Out-of-proc
This scenario will go through the WinHttp stack on its way to the out of proc server. During this process what happens will depend on the actual header values instead of only the encoding. Extended ASCII will be passed onto the server correctly. If all the headers are UTF-8 and can be re-encoded as Extended ASCII (for example Franç°isë), the headers will be re-encoded as Extended ASCII and passed onto the server. If all the headers are UTF-8 but they cannot be re-encoded as Extended ASCII (for example 你好世界), the request will fail with a 502.3 from ANCM. If the headers contain a mix of Extended ASCII and UTF-8, there will be no re-encoding attempted and the raw bytes are passed onto the server.
- Apache + PHP
PHP may be able to parse different charsets via configurations and utilities as `mb-strings`. I wasn't able to get it to work in a reasonable amount of time so I didn't verify it as we were more interested in the out-of-box default behaviours here
- Node.js
All strings are parsed as opaque Extended ASCII: https://github.com/nodejs/node/issues/17390

Based on the comparisons, here are the recommendations and proposals:
1. We should, by default, have Kestrel accept and parse headers as UTF-8. UTF-8 encoding is the same as US ASCII for characters 127 and below. In the comparisons above, we are the only server that rejects UTF-8 headers.
2. We could, by default, fallback to Extended ASCII if UTF-8 encoding fails. This will emulate the Managed Handler behaviour. Extended ASCII is a safe fallback since it will parse each byte using a 8-bit character.
3. We could consider making the fallback encoding for failed UTF-8 parsing configurable. 

These 3 points are independent and I think it's reasonable to start with 1 and 2. We can look into 3 if there is enough demand.

Other alternatives that have been proposed:
- expose headers as raw bytes or opaque string
- drop headers with non US ASCII characters
- reject the request (current behaviours)

But I don't think any of these alternatives are as desirable.

**Comment by davidfowl** [comment] 2018-08-21 04:52
@JunTaoLuo Can you look at response headers as well?

**Comment by JunTaoLuo** [comment] 2018-08-22 07:55
I was hoping we could address response headers separately. Although related, apps have more control over the response headers whereas they cannot control what request headers are sent by clients. However, I will add results here as I test each scenario.

Scenario | `Name: François` (Encode-able in UTF-8 and Extended ASCII) | `Message: 你好` (Encode-able in UTF-8 only) 
-- | -- | -- 
Kestrel (currently) | ❌Failed request | ❌Failed request 
IIS + Managed Handler (ASP.NET 4) | ✔️ Encoded as UTF-8 | ✔️Encoded as UTF-8 
IIS + ANCM In-Proc | ✔️ Encoded as UTF-8 | ✔️Encoded as UTF-8 
IIS + ANCM Out-of-proc | Pending | Pending
Apache | Pending | Pending
Apache + PHP | ✔️ Encoded as UTF-8 | ✔️Encoded as UTF-8 
nginx | Pending | Pending
node.js | ✔️ Encoded as Extended ASCII | ❌Failed request

**Comment by effyteva** [comment] 2018-08-25 19:12
Hi, we also ran into this issue.
Is there any temporary fix to ignore invalid request headers? (our issue is in the Referrer header)

**Comment by JunTaoLuo** [comment] 2018-08-31 00:00
Parsing of request headers with UTF-8 encoded values has been merged and will be available in 2.2.0-preview2.

**Comment by effyteva** [comment] 2018-09-05 06:49
I think it's highly critical to address this issue., at least in term of "removing" non-ascii headers.
Currently requests fail in case any header has non-ascii value, which on many cases can occur due to an external factor, such as referrer pointing to a UTF-8 URL.

**Comment by JunTaoLuo** [comment] 2018-09-05 07:40
@effyteva I have already made the changes to accept UTF-8 encoded characters in header values, which means UTF-8 encoded urls in the `Referer` header will now be accepted. However, we are still planning to reject requests containing non-ascii characters in the header names as well as path and query string values.

**Comment by effyteva** [comment] 2018-09-05 08:55
@JunTaoLuo sorry, I didn't understand you already committed those changes for the 2.2 release.
Thanks, and keep up the great work!

**Comment by JunTaoLuo** [comment] 2018-09-05 18:01
We decided to not pursue accepting non-ASCII characters in header names, path and query string at this time. If  there is compelling reason to enable these scenarios, please file another issue and we will re-prioritize. A follow up issue to address UTF-8 values in response header values has been filed at https://github.com/aspnet/KestrelHttpServer/issues/2884.

**Closed by JunTaoLuo** 2018-09-05 18:01 UTC
Labels: 2 - Working, enhancement

**Comment by sandeepchauhan** [comment] 2018-10-11 21:54
Thanks for this fix. Is there an ETA for 2.2.0 release?

**Comment by Tratcher** [comment] 2018-10-11 22:00
See the [roadmap](https://github.com/aspnet/Announcements/issues/307).

**Comment by turgayozgur** [comment] 2018-11-23 16:30
We can encode. It is okay but what if we are migrating an old application to aspnetcore that already have too many customers who has the cookie contains non-ascii characters?

For now, there is a workaround if you are using nginx at the front of your aspnetcore application.

To remove all of the non ascii characters from the request header:
```
server {
    set_by_lua_block $cookie_ascii {
        local cookie = ngx.var.http_cookie
        if cookie == nil or cookie == '' then return cookie end
        local cookie_ascii, n, err = ngx.re.gsub(cookie, "[^\\x00-\\x7F]", "")
        return cookie_ascii
    }

    listen 80;
    server_name example.com;
    
    location / {
        proxy_pass          http://localhost:5000;
        ...
        proxy_set_header    Cookie $cookie_ascii;
        ...
    }    
}
```

**Comment by effyteva** [comment] 2018-12-08 08:24
We still suffer from the issue, after upgrading to ASP.NET Core 2.2.
Is there any setting required to enable this?

**Comment by Tratcher** [comment] 2018-12-08 16:43
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
